dags/build_export_dag.py
dags/variables.py

* Added backup_provider_uri_list variable into variables. It accepts a comma-separated list of backup uris.
* Added a node_watch task at the beginning of export tasks.
* At first, node_watch checks the provider_uri. If it fails to connect, node_watch recursively checks uris from backup_provider_uri_list and sends the healthy uri to downstreaming export tasks using XCOM method.

Issue #14: Implement fallback mechanism in case export task failed

---

dags/ethereumetl_airflow/build_parse_logs_dag.py
dags/resources/stages/parse/sqls/parse_logs.sql
dags/resources/stages/parse/table_definitions/ens/eth_registrar_controller_event_NameRegistered.json
dags/resources/stages/parse/table_definitions/ens/eth_registrar_controller_event_NameRenewed.json
dags/resources/stages/parse/table_definitions/ens/eth_registrar_controller_event_NewPriceOracle.json
dags/resources/stages/parse/table_definitions/ens/eth_registrar_controller_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/ens/old_public_resolver_event_ABIChanged.json
dags/resources/stages/parse/table_definitions/ens/old_public_resolver_event_AddrChanged.json
dags/resources/stages/parse/table_definitions/ens/old_public_resolver_event_ContentChanged.json
dags/resources/stages/parse/table_definitions/ens/old_public_resolver_event_NameChanged.json
dags/resources/stages/parse/table_definitions/ens/old_public_resolver_event_PubkeyChanged.json
dags/resources/stages/parse/table_definitions/ens/old_registrar_event_AuctionStarted.json
dags/resources/stages/parse/table_definitions/ens/old_registrar_event_BidRevealed.json
dags/resources/stages/parse/table_definitions/ens/old_registrar_event_HashInvalidated.json
dags/resources/stages/parse/table_definitions/ens/old_registrar_event_HashRegistered.json
dags/resources/stages/parse/table_definitions/ens/old_registrar_event_HashReleased.json
dags/resources/stages/parse/table_definitions/ens/old_registrar_event_NewBid.json

cf https://github.com/blockchain-etl/ethereum-etl-airflow/issues/19

Added ENS table definitions + fixed protected names in SQL generation

---

dags/resources/stages/parse/table_definitions/kyber/KyberNetworkProxy_event_AdminClaimed.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetworkProxy_event_AlerterAdded.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetworkProxy_event_EtherWithdraw.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetworkProxy_event_ExecuteTrade.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetworkProxy_event_KyberNetworkSet.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetworkProxy_event_OperatorAdded.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetworkProxy_event_TokenWithdraw.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetworkProxy_event_TransferAdminPending.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_AddReserveToNetwork.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_AdminClaimed.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_AlerterAdded.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_EtherReceival.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_EtherWithdraw.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_ExpectedRateContractSet.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_FeeBurnerContractSet.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_KyberNetworkSetEnable.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_KyberNetwrokParamsSet.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_KyberProxySet.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_KyberTrade.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_ListReservePairs.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_OperatorAdded.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_RemoveReserveFromNetwork.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_TokenWithdraw.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_TransferAdminPending.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_event_WhiteListContractSet.json

Using Kyber's developer portal for table descriptions: https://developer.kyber.network/docs/MainnetEnvGuide/
Contracts covered:
1. [x] KyberNetworkProxy `0x818E6FECD516Ecc3849DAf6845e3EC868087B755`
2. [x] KyberNetwork `0x9ae49C0d7F8F9EF4B864e004FE86Ac8294E20950`
There are more contracts in the Kyber project, but I believe these are the key ones to cover.

Add KyberNetwork events

---

dags/resources/stages/parse/table_definitions/uniswap/Uniswap_DAI_event_AddLiquidity.json
dags/resources/stages/parse/table_definitions/uniswap/Uniswap_DAI_event_EthPurchase.json
dags/resources/stages/parse/table_definitions/uniswap/Uniswap_DAI_event_RemoveLiquidity.json
dags/resources/stages/parse/table_definitions/uniswap/Uniswap_DAI_event_TokenPurchase.json

- Add 4 tables in a new  Uniswap directory 
- tracks events on the DAI/ETH exchange

Added basic Dai exchange events for Uniswap DAI/ETH exchange

---

dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogBump.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogBuyEnabled.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogDelete.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogInsert.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogItemUpdate.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogKill.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogMake.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogMatchingEnabled.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogMinSell.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogNote.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogSetAuthority.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogSetOwner.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogSortedOffer.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogTake.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogTrade.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_event_LogUnsortedOffer.json

Events for Oasis (Dex) aka Eth2dai.
Including contract MatchingMarket `0x39755357759ce0d7f32dc8dc45414cca409ae24e`.

Add Oasis events

---

dags/resources/stages/parse/table_definitions/airswap/AirSwapExchange_event_Canceled.json
dags/resources/stages/parse/table_definitions/airswap/AirSwapExchange_event_Failed.json
dags/resources/stages/parse/table_definitions/airswap/AirSwapExchange_event_Filled.json

Events for AirSwapExchange contract `0x8fd3121013a07c57f0d69646e86e7a4880b467b7`

Add AirSwapExchange events

---

dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_ActionPerformed.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_BountyApproversUpdated.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_BountyChanged.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_BountyDataChanged.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_BountyDeadlineChanged.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_BountyDrained.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_BountyFulfilled.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_BountyIssued.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_BountyIssuersUpdated.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_ContributionAdded.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_ContributionRefunded.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_ContributionsRefunded.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_FulfillmentAccepted.json
dags/resources/stages/parse/table_definitions/bounties_network/StandardBounties_event_FulfillmentUpdated.json

Contract from here: https://github.com/Bounties-Network/StandardBounties

Add Bounties Network: StandardBounties contract

---

dags/resources/stages/parse/table_definitions/hex/HEX_event_Approval.json
dags/resources/stages/parse/table_definitions/hex/HEX_event_Claim.json
dags/resources/stages/parse/table_definitions/hex/HEX_event_ClaimAssist.json
dags/resources/stages/parse/table_definitions/hex/HEX_event_DailyDataUpdate.json
dags/resources/stages/parse/table_definitions/hex/HEX_event_ShareRateChange.json
dags/resources/stages/parse/table_definitions/hex/HEX_event_StakeEnd.json
dags/resources/stages/parse/table_definitions/hex/HEX_event_StakeGoodAccounting.json
dags/resources/stages/parse/table_definitions/hex/HEX_event_StakeStart.json
dags/resources/stages/parse/table_definitions/hex/HEX_event_Transfer.json
dags/resources/stages/parse/table_definitions/hex/HEX_event_XfLobbyEnter.json
dags/resources/stages/parse/table_definitions/hex/HEX_event_XfLobbyExit.json

Added Hex events

---

dags/resources/stages/parse/table_definitions/dex_ag/DexTrading_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/dex_ag/DexTrading_event_Trade.json
dags/resources/stages/parse/table_definitions/etherdelta/EtherDelta2_event_Cancel.json
dags/resources/stages/parse/table_definitions/etherdelta/EtherDelta2_event_Deposit.json
dags/resources/stages/parse/table_definitions/etherdelta/EtherDelta2_event_Order.json
dags/resources/stages/parse/table_definitions/etherdelta/EtherDelta2_event_Trade.json
dags/resources/stages/parse/table_definitions/etherdelta/EtherDelta2_event_Withdraw.json
dags/resources/stages/parse/table_definitions/etherdelta/EtherDelta_event_Cancel.json
dags/resources/stages/parse/table_definitions/etherdelta/EtherDelta_event_Deposit.json
dags/resources/stages/parse/table_definitions/etherdelta/EtherDelta_event_Order.json
dags/resources/stages/parse/table_definitions/etherdelta/EtherDelta_event_Trade.json
dags/resources/stages/parse/table_definitions/etherdelta/EtherDelta_event_Withdraw.json
dags/resources/stages/parse/table_definitions/oneinch/OneInchExchange_event_History.json
dags/resources/stages/parse/table_definitions/oneinch/OneInchExchange_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/oneinch/OneInchExchange_event_Shutdown.json
dags/resources/stages/parse/table_definitions/oneinch/OneInchExchange_event_Swapped.json
dags/resources/stages/parse/table_definitions/tokenlon/TokenlonExchange_event_FillOrder.json

Added events for DEXs / DEX aggregators:

Add events for lots of DEXs

---

dags/resources/stages/parse/table_definitions/kleros/KlerosLiquid_event_AppealDecision.json
dags/resources/stages/parse/table_definitions/kleros/KlerosLiquid_event_AppealPossible.json
dags/resources/stages/parse/table_definitions/kleros/KlerosLiquid_event_DisputeCreation.json
dags/resources/stages/parse/table_definitions/kleros/KlerosLiquid_event_Draw.json
dags/resources/stages/parse/table_definitions/kleros/KlerosLiquid_event_NewPeriod.json
dags/resources/stages/parse/table_definitions/kleros/KlerosLiquid_event_NewPhase.json
dags/resources/stages/parse/table_definitions/kleros/KlerosLiquid_event_StakeSet.json
dags/resources/stages/parse/table_definitions/kleros/KlerosLiquid_event_TokenAndETHShift.json

Contract: https://twitter.com/clesaege/status/1205849746088312832?s=20
Used https://contract-parser.d5.ai/ to parse it.

Add events for Kleros main contract

---

dags/resources/stages/parse/table_definitions/superrare/SupeRare_event_AcceptBid.json
dags/resources/stages/parse/table_definitions/superrare/SupeRare_event_Approval.json
dags/resources/stages/parse/table_definitions/superrare/SupeRare_event_Bid.json
dags/resources/stages/parse/table_definitions/superrare/SupeRare_event_CancelBid.json
dags/resources/stages/parse/table_definitions/superrare/SupeRare_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/superrare/SupeRare_event_SalePriceSet.json
dags/resources/stages/parse/table_definitions/superrare/SupeRare_event_Sold.json
dags/resources/stages/parse/table_definitions/superrare/SupeRare_event_Transfer.json
dags/resources/stages/parse/table_definitions/superrare/SupeRare_event_WhitelistCreator.json

Used [Contract Parser](https://contract-parser.d5.ai) on contract `0x41a322b28d0ff354040e2cbc676f0320d8c8850d`

Add events for SupeRare (sic) contract

---

dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_AddReserveToNetwork.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_AdminClaimed.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_AlerterAdded.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_EtherReceival.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_EtherWithdraw.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_ExpectedRateContractSet.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_FeeBurnerContractSet.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_KyberNetworkSetEnable.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_KyberNetwrokParamsSet.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_KyberProxySet.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_KyberTrade.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_ListReservePairs.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_OperatorAdded.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_RemoveReserveFromNetwork.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_TokenWithdraw.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_TransferAdminPending.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetwork_v2_event_WhiteListContractSet.json

0x65bf64ff5f51272f729bdcd7acfb00677ced86cd
Used https://contract-parser.d5.ai/
Manually added `_v2` to the contract name.

Add v2 of the KyberNetwork contract

---

dags/ethereumetl_airflow/build_parse_dag.py
dags/resources/stages/parse/sqls/parse_logs.sql
dags/resources/stages/parse/table_definitions/mintbase/ThingFactory_event_StoreLaunch.json
dags/resources/stages/parse/table_definitions/mintbase/Thing_event_Minted.json

https://github.com/blockchain-etl/ethereum-etl-airflow/issues/51

Implement refs support in contract_address for parsing logs

---

dags/resources/stages/parse/table_definitions/uniswap/Uniswap_event_AddLiquidity.json
dags/resources/stages/parse/table_definitions/uniswap/Uniswap_event_Approval.json
dags/resources/stages/parse/table_definitions/uniswap/Uniswap_event_EthPurchase.json
dags/resources/stages/parse/table_definitions/uniswap/Uniswap_event_RemoveLiquidity.json
dags/resources/stages/parse/table_definitions/uniswap/Uniswap_event_TokenPurchase.json
dags/resources/stages/parse/table_definitions/uniswap/Uniswap_event_Transfer.json
dags/resources/stages/parse/table_definitions/uniswap/Vyper_contract_event_NewExchange.json

Added events for factory contract: `0xc0a47dfe034b400b47bdad5fecda2621de6c4d95`
Plus events for child contracts (pools) - example: `0x077d52b047735976dfda76fef74d4d988ac25196`

Add Uniswap factory + child contract events (pools)

---

dags/resources/stages/parse/table_definitions/airswap/Swap_event_AuthorizeSender.json
dags/resources/stages/parse/table_definitions/airswap/Swap_event_AuthorizeSigner.json
dags/resources/stages/parse/table_definitions/airswap/Swap_event_Cancel.json
dags/resources/stages/parse/table_definitions/airswap/Swap_event_CancelUpTo.json
dags/resources/stages/parse/table_definitions/airswap/Swap_event_RevokeSender.json
dags/resources/stages/parse/table_definitions/airswap/Swap_event_RevokeSigner.json
dags/resources/stages/parse/table_definitions/airswap/Swap_event_Swap.json
dags/resources/stages/parse/table_definitions/idex/Exchange_call_trade.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogBump.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogBuyEnabled.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogDelete.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogInsert.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogItemUpdate.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogKill.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogMake.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogMatchingEnabled.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogMinSell.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogNote.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogSetAuthority.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogSetOwner.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogSortedOffer.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogTake.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogTrade.json
dags/resources/stages/parse/table_definitions/oasis/MatchingMarket_v2_event_LogUnsortedOffer.json

Added event parsers for:
And a trace parser for:

Add more DEX contract parsers

---

dags/resources/stages/parse/table_definitions/gnosis/MultiSigWalletWithDailyLimitFactory_event_ContractInstantiation.json
dags/resources/stages/parse/table_definitions/gnosis/MultiSigWalletWithDailyLimit_event_Confirmation.json
dags/resources/stages/parse/table_definitions/gnosis/MultiSigWalletWithDailyLimit_event_DailyLimitChange.json
dags/resources/stages/parse/table_definitions/gnosis/MultiSigWalletWithDailyLimit_event_Deposit.json
dags/resources/stages/parse/table_definitions/gnosis/MultiSigWalletWithDailyLimit_event_Execution.json
dags/resources/stages/parse/table_definitions/gnosis/MultiSigWalletWithDailyLimit_event_ExecutionFailure.json
dags/resources/stages/parse/table_definitions/gnosis/MultiSigWalletWithDailyLimit_event_OwnerAddition.json
dags/resources/stages/parse/table_definitions/gnosis/MultiSigWalletWithDailyLimit_event_OwnerRemoval.json
dags/resources/stages/parse/table_definitions/gnosis/MultiSigWalletWithDailyLimit_event_RequirementChange.json
dags/resources/stages/parse/table_definitions/gnosis/MultiSigWalletWithDailyLimit_event_Revocation.json
dags/resources/stages/parse/table_definitions/gnosis/MultiSigWalletWithDailyLimit_event_Submission.json

Added parsers for:
Used the [Contract Parser](https://contract-parser.d5.ai/)

Add Gnosis MultiSigWalletWithDailyLimit parsers

---

dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_JurorActivated.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_JurorBalanceLocked.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_JurorBalanceUnlocked.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_JurorDeactivationProcessed.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_JurorDeactivationRequested.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_JurorDeactivationUpdated.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_JurorSlashed.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_JurorTokensAssigned.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_JurorTokensBurned.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_JurorTokensCollected.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_RecoverFunds.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_Staked.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_TotalActiveBalanceLimitChanged.json
dags/resources/stages/parse/table_definitions/aragon/JurorsRegistry_event_Unstaked.json

Contract: `0x0f7471c1df2021ff45f112878f755aabe7aa16bf`
Used [Contract Parser](https://contract-parser.d5.ai/)

Add JurorsRegistry parsers

---

dags/resources/stages/parse/table_definitions/maker/Cat_call_bite.json
dags/resources/stages/parse/table_definitions/maker/Flipper_ETH_call_deal.json
dags/resources/stages/parse/table_definitions/maker/Flipper_ETH_call_tend.json

Adding some call events that will help people analyze Maker liquidations.

Add some Maker function call parsing

---

dags/ethereumetl_airflow/build_parse_dag.py

https://github.com/blockchain-etl/ethereum-etl-airflow/issues/75

Adjust parse DAG scheduling

---

dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_BorrowLiquidated.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_BorrowRepaid.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_BorrowTaken.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_EquityWithdrawn.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_Failure.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_NewAdmin.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_NewOracle.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_NewOriginationFee.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_NewPendingAdmin.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_NewRiskParameters.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_SetMarketInterestRateModel.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_SetPaused.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_SupplyReceived.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_SupplyWithdrawn.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_SupportedMarket.json
dags/resources/stages/parse/table_definitions/lendfme/MoneyMarket_event_SuspendedMarket.json

Used the [Contract Parser](https://contract-parser.d5.ai/) on this address: `0x0eee3e3828a45f7601d5f54bf49bb01d1a9df5ea`

Add Lendfme MoneyMarket events

---

dags/resources/stages/parse/table_definitions/wbtc/WBTC_event_Approval.json
dags/resources/stages/parse/table_definitions/wbtc/WBTC_event_Burn.json
dags/resources/stages/parse/table_definitions/wbtc/WBTC_event_Mint.json
dags/resources/stages/parse/table_definitions/wbtc/WBTC_event_MintFinished.json
dags/resources/stages/parse/table_definitions/wbtc/WBTC_event_OwnershipRenounced.json
dags/resources/stages/parse/table_definitions/wbtc/WBTC_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/wbtc/WBTC_event_Pause.json
dags/resources/stages/parse/table_definitions/wbtc/WBTC_event_Transfer.json
dags/resources/stages/parse/table_definitions/wbtc/WBTC_event_Unpause.json

Used [Contract Parser](https://contract-parser.d5.ai) on `0x2260fac5e5542a773aa44fbcfedf7c193bc2c599`.

Add WBTC event parsing

---

dags/resources/stages/parse/table_definitions/compound/cUSDT_event_AccrueInterest.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_Approval.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_Borrow.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_Failure.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_LiquidateBorrow.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_Mint.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_NewAdmin.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_NewComptroller.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_NewImplementation.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_NewMarketInterestRateModel.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_NewPendingAdmin.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_NewReserveFactor.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_Redeem.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_RepayBorrow.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_ReservesAdded.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_ReservesReduced.json
dags/resources/stages/parse/table_definitions/compound/cUSDT_event_Transfer.json

Add Compound USDT event parsing

---

dags/resources/stages/parse/table_definitions/aave/LendingPool_event_Borrow.json
dags/resources/stages/parse/table_definitions/aave/LendingPool_event_Deposit.json
dags/resources/stages/parse/table_definitions/aave/LendingPool_event_FlashLoan.json
dags/resources/stages/parse/table_definitions/aave/LendingPool_event_LiquidationCall.json
dags/resources/stages/parse/table_definitions/aave/LendingPool_event_OriginationFeeLiquidated.json
dags/resources/stages/parse/table_definitions/aave/LendingPool_event_RebalanceStableBorrowRate.json
dags/resources/stages/parse/table_definitions/aave/LendingPool_event_RedeemUnderlying.json
dags/resources/stages/parse/table_definitions/aave/LendingPool_event_Repay.json
dags/resources/stages/parse/table_definitions/aave/LendingPool_event_ReserveUsedAsCollateralDisabled.json
dags/resources/stages/parse/table_definitions/aave/LendingPool_event_ReserveUsedAsCollateralEnabled.json
dags/resources/stages/parse/table_definitions/aave/LendingPool_event_Swap.json

Fixes https://github.com/blockchain-etl/ethereum-etl-airflow/issues/100

Fix contract address for aave

---

dags/resources/stages/parse/table_definitions/balancer/BFactory_event_LOG_BLABS.json
dags/resources/stages/parse/table_definitions/balancer/BFactory_event_LOG_NEW_POOL.json
dags/resources/stages/parse/table_definitions/balancer/BPool_event_Approval.json
dags/resources/stages/parse/table_definitions/balancer/BPool_event_LOG_CALL.json
dags/resources/stages/parse/table_definitions/balancer/BPool_event_LOG_EXIT.json
dags/resources/stages/parse/table_definitions/balancer/BPool_event_LOG_JOIN.json
dags/resources/stages/parse/table_definitions/balancer/BPool_event_LOG_SWAP.json
dags/resources/stages/parse/table_definitions/balancer/BPool_event_Transfer.json

Used https://contract-parser.d5.ai/
Manually updated contract references in `BPool` to use the pools from `BFactory`.

Add parsing of BFactory and BPool for Balancer

---

dags/resources/stages/parse/table_definitions/compound/Comp_event_Approval.json
dags/resources/stages/parse/table_definitions/compound/Comp_event_DelegateChanged.json
dags/resources/stages/parse/table_definitions/compound/Comp_event_DelegateVotesChanged.json
dags/resources/stages/parse/table_definitions/compound/Comp_event_Transfer.json

Used https://contract-parser.d5.ai on `0xc00e94cb662c3520282e6f5717214004a7f26888`.

Add parsing for COMP token

---

dags/resources/stages/parse/table_definitions/maker/Dai_call_mint.json
dags/resources/stages/parse/table_definitions/maker/Flipper_BAT_call_deal.json
dags/resources/stages/parse/table_definitions/maker/Flipper_BAT_call_dent.json
dags/resources/stages/parse/table_definitions/maker/Flipper_BAT_call_tend.json

* Add Maker BAT auction parsing
* Update the table name of DAI burn and mint calls

Add Maker BAT auction parsing

---

dags/resources/stages/parse/table_definitions/dexblue/dexBlue_event_LogBlockedForSingleSigWithdrawal.json
dags/resources/stages/parse/table_definitions/dexblue/dexBlue_event_LogDelegateStatus.json
dags/resources/stages/parse/table_definitions/dexblue/dexBlue_event_LogDeposit.json
dags/resources/stages/parse/table_definitions/dexblue/dexBlue_event_LogDirectWithdrawal.json
dags/resources/stages/parse/table_definitions/dexblue/dexBlue_event_LogOrderCanceled.json
dags/resources/stages/parse/table_definitions/dexblue/dexBlue_event_LogSingleSigWithdrawal.json
dags/resources/stages/parse/table_definitions/dexblue/dexBlue_event_LogSwap.json
dags/resources/stages/parse/table_definitions/dexblue/dexBlue_event_LogTrade.json
dags/resources/stages/parse/table_definitions/dexblue/dexBlue_event_LogTradeFailed.json
dags/resources/stages/parse/table_definitions/dexblue/dexBlue_event_LogWithdrawal.json

Used https://contract-parser.d5.ai on `0x000000000000541e251335090ac5b47176af4f7e`.

Added dex.blue events

---

dags/resources/stages/parse/table_definitions/aave/EthLendToken_event_Approval.json
dags/resources/stages/parse/table_definitions/aave/EthLendToken_event_LogBurn.json
dags/resources/stages/parse/table_definitions/aave/EthLendToken_event_LogBuy.json
dags/resources/stages/parse/table_definitions/aave/EthLendToken_event_Transfer.json

ETH LEND (Aave)
0x80fB784B7eD66730e8b1DBd9820aFD29931aab03

Added ETHLEND events

---

dags/resources/stages/parse/table_definitions/kyber/KyberNetworkCrystal_event_Approval.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetworkCrystal_event_Burn.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetworkCrystal_event_Transfer.json

Now with correct dataset_name
KyberNetworkCrystal
0xdd974d5c2e2928dea5f71b9825b8b646686bd200

Added kyber network crystal events

---

dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_Approval.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_ApproveMintTokens.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_BurnTokens.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_DisableSetTransferable.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_MintFinished.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_MintTokens.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_SetAElfCommunityMultisig.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_SetAElfDevMultisig.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_SetDurationOfLock.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_SetTransferable.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_Transfer.json
dags/resources/stages/parse/table_definitions/aelf/AElfToken_event_WithdrawMintTokens.json

AELF
0xbf2179859fc6D5BEE9Bf9158632Dc51678a4100e

Added AELF Events

---

dags/resources/stages/parse/table_definitions/livepeertoken/LivepeerToken_event_Approval.json
dags/resources/stages/parse/table_definitions/livepeertoken/LivepeerToken_event_Burn.json
dags/resources/stages/parse/table_definitions/livepeertoken/LivepeerToken_event_Mint.json
dags/resources/stages/parse/table_definitions/livepeertoken/LivepeerToken_event_MintFinished.json
dags/resources/stages/parse/table_definitions/livepeertoken/LivepeerToken_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/livepeertoken/LivepeerToken_event_Transfer.json

LivePeerToken
0x58b6a8a3302369daec383334672404ee733ab239

Added LivePeerToken events

---

dags/resources/stages/parse/table_definitions/rocketpool/RocketPoolToken_event_Approval.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketPoolToken_event_FlagAddress.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketPoolToken_event_FlagUint.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketPoolToken_event_MintToken.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketPoolToken_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketPoolToken_event_SaleFinalised.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketPoolToken_event_Transfer.json

Rocketpool
0xb4efd85c19999d84251304bda99e90b92300bd93

Added rocketpool events

---

dags/resources/stages/parse/table_definitions/qdao/QDAO_event_Approval.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_Burn.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_GovernanceContractAdded.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_GovernanceContractRemoved.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_Mint.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_OperationCancelled.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_OperationCreated.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_OperationDownvoted.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_OperationPerformed.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_OperationUpvoted.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_OwnershipRenounced.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_Pause.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_Transfer.json
dags/resources/stages/parse/table_definitions/qdao/QDAO_event_Unpause.json

QDAO
0x3166c570935a7d8554c8f4ea792ff965d2efe1f2

Added QDAO events

---

dags/resources/stages/parse/table_definitions/xyo_network/TokenERC20_event_Burn.json
dags/resources/stages/parse/table_definitions/xyo_network/TokenERC20_event_Transfer.json

xyo network
0x55296f69f40ea6d20e478533c15a6b08b654e758

Added xyo network events

---

dags/resources/stages/parse/table_definitions/singularitynet/SingularityNetToken_event_Approval.json
dags/resources/stages/parse/table_definitions/singularitynet/SingularityNetToken_event_Burn.json
dags/resources/stages/parse/table_definitions/singularitynet/SingularityNetToken_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/singularitynet/SingularityNetToken_event_Pause.json
dags/resources/stages/parse/table_definitions/singularitynet/SingularityNetToken_event_Transfer.json
dags/resources/stages/parse/table_definitions/singularitynet/SingularityNetToken_event_Unpause.json

SingularityNet
0x8eb24319393716668d768dcec29356ae9cffe285

Added singularity_net events

---

dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_AddCallSpenderWhitelist.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_AllowedTransactorAdded.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_AllowedTransactorRemoved.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_Approval.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_Burn.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_Mint.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_MintFinished.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_OwnershipRenounced.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_Pause.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_RemoveCallSpenderWhitelist.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_SetWhitelistExpiration.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_Transfer.json
dags/resources/stages/parse/table_definitions/origin_protocol/OriginToken_event_Unpause.json

Origin_Protocol
0x8207c1ffc5b6804f6024322ccf34f29c3541ae26

Added Origin_protocol events

---

dags/resources/stages/parse/table_definitions/bancor_network/SmartToken_event_Approval.json
dags/resources/stages/parse/table_definitions/bancor_network/SmartToken_event_Destruction.json
dags/resources/stages/parse/table_definitions/bancor_network/SmartToken_event_Issuance.json
dags/resources/stages/parse/table_definitions/bancor_network/SmartToken_event_NewSmartToken.json
dags/resources/stages/parse/table_definitions/bancor_network/SmartToken_event_OwnerUpdate.json
dags/resources/stages/parse/table_definitions/bancor_network/SmartToken_event_Transfer.json

Bancor BNT
0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c

added bancor events

---

dags/resources/stages/parse/table_definitions/request/RequestToken_event_Approval.json
dags/resources/stages/parse/table_definitions/request/RequestToken_event_Burn.json
dags/resources/stages/parse/table_definitions/request/RequestToken_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/request/RequestToken_event_Transfer.json

Request Network
0x8f8221aFbB33998d8584A2B05749bA73c37a938a

Added RequestToken events

---

dags/resources/stages/parse/table_definitions/ampleforth/UFragments_event_Approval.json
dags/resources/stages/parse/table_definitions/ampleforth/UFragments_event_LogMonetaryPolicyUpdated.json
dags/resources/stages/parse/table_definitions/ampleforth/UFragments_event_LogRebase.json
dags/resources/stages/parse/table_definitions/ampleforth/UFragments_event_LogRebasePaused.json
dags/resources/stages/parse/table_definitions/ampleforth/UFragments_event_LogTokenPaused.json
dags/resources/stages/parse/table_definitions/ampleforth/UFragments_event_OwnershipRenounced.json
dags/resources/stages/parse/table_definitions/ampleforth/UFragments_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/ampleforth/UFragments_event_Transfer.json

Proxy: `0xd46ba6d942050d489dbd938a2c909a5d5039a161`
Target: `0x3222a6c3fd5927437c9e5f4c9eb5c98b22bcde48`

Add AMPL token parsing

---

dags/resources/stages/parse/table_definitions/mooniswap/MooniFactory_event_Deployed.json
dags/resources/stages/parse/table_definitions/mooniswap/MooniFactory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/mooniswap/Mooniswap_event_Approval.json
dags/resources/stages/parse/table_definitions/mooniswap/Mooniswap_event_Deposited.json
dags/resources/stages/parse/table_definitions/mooniswap/Mooniswap_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/mooniswap/Mooniswap_event_Swapped.json
dags/resources/stages/parse/table_definitions/mooniswap/Mooniswap_event_Transfer.json
dags/resources/stages/parse/table_definitions/mooniswap/Mooniswap_event_Withdrawn.json

Used https://contract-parser.d5.ai/

Add MooniFactory + Mooniswap events

---

dags/resources/stages/parse/table_definitions/sushiswap/MasterChef_event_Deposit.json
dags/resources/stages/parse/table_definitions/sushiswap/MasterChef_event_EmergencyWithdraw.json
dags/resources/stages/parse/table_definitions/sushiswap/MasterChef_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/sushiswap/MasterChef_event_Withdraw.json

Used https://contract-parser.d5.ai/

Add SushiSwap events

---

dags/resources/stages/parse/table_definitions/balancer/CRPFactory_event_LogNewCrp.json

“Used the Contract Parser: https://contract-parser.d5.ai”

Added Balancer CRP factory events

---

dags/resources/stages/parse/table_definitions/balancer/CRPFactory_event_LogNewCrp.json

sorry for the misunderstanding

fix dataset name

---

dags/resources/stages/parse/table_definitions/aave/AavePropositionPower_event_Approval.json
dags/resources/stages/parse/table_definitions/aave/AavePropositionPower_event_MinterAdded.json
dags/resources/stages/parse/table_definitions/aave/AavePropositionPower_event_MinterRemoved.json
dags/resources/stages/parse/table_definitions/aave/AavePropositionPower_event_Transfer.json
dags/resources/stages/parse/table_definitions/aave/AaveProtoGovernance_event_AbstainWins.json
dags/resources/stages/parse/table_definitions/aave/AaveProtoGovernance_event_NoWins.json
dags/resources/stages/parse/table_definitions/aave/AaveProtoGovernance_event_ProposalCreated.json
dags/resources/stages/parse/table_definitions/aave/AaveProtoGovernance_event_StatusChangeToExecuted.json
dags/resources/stages/parse/table_definitions/aave/AaveProtoGovernance_event_StatusChangeToValidating.json
dags/resources/stages/parse/table_definitions/aave/AaveProtoGovernance_event_StatusChangeToVoting.json
dags/resources/stages/parse/table_definitions/aave/AaveProtoGovernance_event_VoteCancelled.json
dags/resources/stages/parse/table_definitions/aave/AaveProtoGovernance_event_VoteEmitted.json
dags/resources/stages/parse/table_definitions/aave/AaveProtoGovernance_event_YesWins.json
dags/resources/stages/parse/table_definitions/aave/AssetVotingWeightProvider_event_AssetWeightSet.json
dags/resources/stages/parse/table_definitions/aave/AssetVotingWeightProvider_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/aave/GovernanceParamsProvider_event_AssetVotingWeightProviderSet.json
dags/resources/stages/parse/table_definitions/aave/GovernanceParamsProvider_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/aave/GovernanceParamsProvider_event_PropositionPowerSet.json
dags/resources/stages/parse/table_definitions/aave/GovernanceParamsProvider_event_PropositionPowerThresholdSet.json
dags/resources/stages/parse/table_definitions/aave/StakedAave_event_Approval.json
dags/resources/stages/parse/table_definitions/aave/StakedAave_event_AssetConfigUpdated.json
dags/resources/stages/parse/table_definitions/aave/StakedAave_event_AssetIndexUpdated.json
dags/resources/stages/parse/table_definitions/aave/StakedAave_event_Cooldown.json
dags/resources/stages/parse/table_definitions/aave/StakedAave_event_Redeem.json
dags/resources/stages/parse/table_definitions/aave/StakedAave_event_RewardsAccrued.json
dags/resources/stages/parse/table_definitions/aave/StakedAave_event_RewardsClaimed.json
dags/resources/stages/parse/table_definitions/aave/StakedAave_event_SnapshotDone.json
dags/resources/stages/parse/table_definitions/aave/StakedAave_event_Staked.json
dags/resources/stages/parse/table_definitions/aave/StakedAave_event_Transfer.json
dags/resources/stages/parse/table_definitions/aave/StakedAave_event_UserIndexUpdated.json

Used the Contract Parser: https://contract-parser.d5.ai.
Adding contracts:
- [Staked AAVE (proxy)](https://docs.aave.com/developers/developing-on-aave/the-protocol/safety-module-stkaave)
- [AaveProtoGovernance](https://docs.aave.com/developers/developing-on-aave/the-protocol/governance)
- [AssetVotingWeightProvider](https://docs.aave.com/developers/developing-on-aave/the-protocol/governance)
- [AavePropositionPower](https://docs.aave.com/developers/developing-on-aave/the-protocol/governance)
- [GovernanceParamsProvider](https://docs.aave.com/developers/developing-on-aave/the-protocol/governance)

Add Aave Governance and StakedAave contract events

---

dags/ethereum_extract_dag.py
dags/ethereumetl_airflow/build_extract_dag.py

Partial implementation of https://github.com/blockchain-etl/ethereum-etl-airflow/issues/143

Add DAG for extracting data from BigQuery to GCS in CSV

---

dags/resources/stages/parse/table_definitions/ampleforth/UFragmentsPolicy_event_LogRebase.json

Added Policy Rebase event to Ampleforth table definition

---

dags/resources/stages/parse/table_definitions/balancer/BPool_call_finalize.json

@medvedev1088 one more :-) ready for review, thank you!

add call to finalize

---

dags/ethereum_clean_dag.py
dags/ethereum_parse_dag.py
dags/ethereum_partition_dag.py
dags/ethereumetl_airflow/build_clean_dag.py
dags/ethereumetl_airflow/build_parse_dag.py
dags/ethereumetl_airflow/build_partition_dag.py
dags/ethereumetl_airflow/parse/parse_logic.py
dags/resources/stages/parse/sqls/parse_logs.sql
dags/resources/stages/parse/sqls/parse_traces.sql
tests/ethereumetl_airflow/test_parse.py
tests/resources/ethereumetl_airflow/test_parse/dydx/SoloMargin_event_LogTrade.json_True_1.sql
tests/resources/ethereumetl_airflow/test_parse/dydx/SoloMargin_event_LogTrade.json_True_2.sql
tests/resources/ethereumetl_airflow/test_parse/ens/Registrar0_event_NewBid.json_False_1.sql
tests/resources/ethereumetl_airflow/test_parse/ens/Registrar0_event_NewBid.json_False_2.sql
tests/resources/ethereumetl_airflow/test_parse/ens/Registrar0_event_NewBid.json_True_1.sql
tests/resources/ethereumetl_airflow/test_parse/ens/Registrar0_event_NewBid.json_True_2.sql
tests/resources/ethereumetl_airflow/test_parse/idex/Exchange_call_trade.json_True_1.sql
tests/resources/ethereumetl_airflow/test_parse/idex/Exchange_call_trade.json_True_2.sql
tests/resources/ethereumetl_airflow/test_parse/uniswap/UniswapV2Pair_event_Swap.json_False_0.sql
tests/resources/ethereumetl_airflow/test_parse/uniswap/UniswapV2Pair_event_Swap.json_False_1.sql
tests/resources/ethereumetl_airflow/test_parse/uniswap/UniswapV2Pair_event_Swap.json_False_2.sql
tests/resources/ethereumetl_airflow/test_parse/uniswap/UniswapV2Pair_event_Swap.json_False_3.sql
tests/resources/ethereumetl_airflow/test_parse/uniswap/UniswapV2Pair_event_Swap.json_False_4.sql
tests/resources/ethereumetl_airflow/test_parse/uniswap/Uniswap_event_AddLiquidity.json_True_1.sql
tests/resources/ethereumetl_airflow/test_parse/uniswap/Uniswap_event_AddLiquidity.json_True_2.sql

Parsing jobs query from tables partitioned by selector, which reduces costs 10x

Optimise parsing

---

dags/resources/stages/parse/table_definitions/esd/Implementation_event_Advance.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_Bond.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_Commit.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_CouponApproval.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_CouponExpiration.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_CouponPurchase.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_CouponRedemption.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_CouponTransfer.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_Deposit.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_Incentivization.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_Proposal.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_SupplyDecrease.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_SupplyIncrease.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_SupplyNeutral.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_Transfer.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_Unbond.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_Upgraded.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_Vote.json
dags/resources/stages/parse/table_definitions/esd/Implementation_event_Withdraw.json

Parsing events for this contract: https://etherscan.io/address/0x443D2f2755DB5942601fa062Cc248aAA153313D3#readProxyContract
Used https://contract-parser.d5.ai/ and then replaced occurrences of the implementation address as follows:
```
sed -i '.bak' 's/0xfd6d0c38211f29f6668a3e6886ca7dced0162208/0x443d2f2755db5942601fa062cc248aaa153313d3/g' *
rm *.bak
```

Add Empty Set Dollar Stake (ESDS)

---

dags/resources/stages/parse/table_definitions/balancer/view_pools_controllers.sql
dags/resources/stages/parse/table_definitions/balancer/view_pools_fees.sql
dags/resources/stages/parse/table_definitions/balancer/view_pools_public_swaps.sql
dags/resources/stages/parse/table_definitions/balancer/view_pools_tokens_denorm_weights.sql

@medvedev1088 ready for review, thank you

remove order by from view

---

dags/resources/stages/parse/table_definitions/hegic/HegicERCPool_event_Approval.json
dags/resources/stages/parse/table_definitions/hegic/HegicERCPool_event_Loss.json
dags/resources/stages/parse/table_definitions/hegic/HegicERCPool_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/hegic/HegicERCPool_event_Profit.json
dags/resources/stages/parse/table_definitions/hegic/HegicERCPool_event_Provide.json
dags/resources/stages/parse/table_definitions/hegic/HegicERCPool_event_Transfer.json
dags/resources/stages/parse/table_definitions/hegic/HegicERCPool_event_Withdraw.json
dags/resources/stages/parse/table_definitions/hegic/HegicETHOptions_event_Create.json
dags/resources/stages/parse/table_definitions/hegic/HegicETHOptions_event_Exercise.json
dags/resources/stages/parse/table_definitions/hegic/HegicETHOptions_event_Expire.json
dags/resources/stages/parse/table_definitions/hegic/HegicETHOptions_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/hegic/HegicETHPool_event_Approval.json
dags/resources/stages/parse/table_definitions/hegic/HegicETHPool_event_Loss.json
dags/resources/stages/parse/table_definitions/hegic/HegicETHPool_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/hegic/HegicETHPool_event_Profit.json
dags/resources/stages/parse/table_definitions/hegic/HegicETHPool_event_Provide.json
dags/resources/stages/parse/table_definitions/hegic/HegicETHPool_event_Transfer.json
dags/resources/stages/parse/table_definitions/hegic/HegicETHPool_event_Withdraw.json
dags/resources/stages/parse/table_definitions/hegic/HegicStakingETH_event_Approval.json
dags/resources/stages/parse/table_definitions/hegic/HegicStakingETH_event_Claim.json
dags/resources/stages/parse/table_definitions/hegic/HegicStakingETH_event_Profit.json
dags/resources/stages/parse/table_definitions/hegic/HegicStakingETH_event_Transfer.json
dags/resources/stages/parse/table_definitions/hegic/HegicStakingWBTC_event_Approval.json
dags/resources/stages/parse/table_definitions/hegic/HegicStakingWBTC_event_Claim.json
dags/resources/stages/parse/table_definitions/hegic/HegicStakingWBTC_event_Profit.json
dags/resources/stages/parse/table_definitions/hegic/HegicStakingWBTC_event_Transfer.json
dags/resources/stages/parse/table_definitions/hegic/HegicWBTCOptions_event_Create.json
dags/resources/stages/parse/table_definitions/hegic/HegicWBTCOptions_event_Exercise.json
dags/resources/stages/parse/table_definitions/hegic/HegicWBTCOptions_event_Expire.json
dags/resources/stages/parse/table_definitions/hegic/HegicWBTCOptions_event_OwnershipTransferred.json

Contracts from [this list](https://hegic.gitbook.io/start/developers/contracts) (minus two Chainlink oracles at the bottom).

Add events for Hegic

---

dags/resources/stages/parse/table_definitions/compound/cCOMP_event_AccrueInterest.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_Approval.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_Borrow.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_Failure.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_LiquidateBorrow.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_Mint.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_NewAdmin.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_NewComptroller.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_NewImplementation.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_NewMarketInterestRateModel.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_NewPendingAdmin.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_NewReserveFactor.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_Redeem.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_RepayBorrow.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_ReservesAdded.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_ReservesReduced.json
dags/resources/stages/parse/table_definitions/compound/cCOMP_event_Transfer.json

Added cCOMP to compound dataset

---

dags/resources/stages/parse/table_definitions/fetchai/Staking_event_BindStake.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_DeleteContract.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_ExcessTokenWithdrawal.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_LiquidityDeposited.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_LiquidityUnlocked.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_LockPeriod.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_NewInterestRate.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_Pause.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_RewardsPoolTokenTopUp.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_RewardsPoolTokenWithdrawal.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_RoleAdminChanged.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_RoleGranted.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_RoleRevoked.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_StakeCompoundInterest.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_TokenWithdrawal.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_UnbindStake.json
dags/resources/stages/parse/table_definitions/fetchai/Staking_event_Withdraw.json

“Used the Contract Parser: https://contract-parser.d5.ai”

fetchai staking events

---

dags/resources/stages/parse/table_definitions/lido/Lido_event_Approval.json
dags/resources/stages/parse/table_definitions/lido/Lido_event_FeeDistributionSet.json
dags/resources/stages/parse/table_definitions/lido/Lido_event_FeeSet.json
dags/resources/stages/parse/table_definitions/lido/Lido_event_RecoverToVault.json
dags/resources/stages/parse/table_definitions/lido/Lido_event_Resumed.json
dags/resources/stages/parse/table_definitions/lido/Lido_event_ScriptResult.json
dags/resources/stages/parse/table_definitions/lido/Lido_event_Stopped.json
dags/resources/stages/parse/table_definitions/lido/Lido_event_Submitted.json
dags/resources/stages/parse/table_definitions/lido/Lido_event_Transfer.json
dags/resources/stages/parse/table_definitions/lido/Lido_event_Unbuffered.json
dags/resources/stages/parse/table_definitions/lido/Lido_event_Withdrawal.json
dags/resources/stages/parse/table_definitions/lido/Lido_event_WithdrawalCredentialsSet.json

Used https://contract-parser.d5.ai/ on `0x20dc62d5904633cc6a5e34bec87a048e80c92e97`, then replaced with proxy address `0xae7ab96520de3a18e5e111b5eaab095312d7fe84`:
```
sed -i '.bak' 's/0x20dc62d5904633cc6a5e34bec87a048e80c92e97/0xae7ab96520de3a18e5e111b5eaab095312d7fe84/g' *
rm *.bak
```

Add Lido events

---

dags/resources/stages/parse/table_definitions/mooniswap/MooniswapFactory_event_DefaultDecayPeriodVoteUpdate.json
dags/resources/stages/parse/table_definitions/mooniswap/MooniswapFactory_event_DefaultFeeVoteUpdate.json
dags/resources/stages/parse/table_definitions/mooniswap/MooniswapFactory_event_DefaultSlippageFeeVoteUpdate.json
dags/resources/stages/parse/table_definitions/mooniswap/MooniswapFactory_event_Deployed.json
dags/resources/stages/parse/table_definitions/mooniswap/MooniswapFactory_event_GovernanceFeeReceiverUpdate.json
dags/resources/stages/parse/table_definitions/mooniswap/MooniswapFactory_event_GovernanceShareVoteUpdate.json
dags/resources/stages/parse/table_definitions/mooniswap/MooniswapFactory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/mooniswap/MooniswapFactory_event_Paused.json
dags/resources/stages/parse/table_definitions/mooniswap/MooniswapFactory_event_ReferralFeeReceiverUpdate.json
dags/resources/stages/parse/table_definitions/mooniswap/MooniswapFactory_event_ReferralShareVoteUpdate.json
dags/resources/stages/parse/table_definitions/mooniswap/MooniswapFactory_event_Unpaused.json

Added MooniswapFactory events

---

dags/resources/stages/parse/table_definitions/mooniswap/OneInchExchange_event_Error.json
dags/resources/stages/parse/table_definitions/mooniswap/OneInchExchange_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/mooniswap/OneInchExchange_event_Paused.json
dags/resources/stages/parse/table_definitions/mooniswap/OneInchExchange_event_Swapped.json
dags/resources/stages/parse/table_definitions/mooniswap/OneInchExchange_event_Unpaused.json

Add 1inch v2 : https://etherscan.io/address/0x111111125434b319222CdBf8C261674aDB56F3ae#code

Add OneInchv2

---

dags/resources/stages/parse/table_definitions/optimism/AddressManager_event_AddressSet.json
dags/resources/stages/parse/table_definitions/optimism/AddressManager_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/optimism/OVM_CanonicalTransactionChain_event_QueueBatchAppended.json
dags/resources/stages/parse/table_definitions/optimism/OVM_CanonicalTransactionChain_event_SequencerBatchAppended.json
dags/resources/stages/parse/table_definitions/optimism/OVM_CanonicalTransactionChain_event_TransactionBatchAppended.json
dags/resources/stages/parse/table_definitions/optimism/OVM_CanonicalTransactionChain_event_TransactionEnqueued.json
dags/resources/stages/parse/table_definitions/optimism/OVM_FraudVerifier_event_FraudProofFinalized.json
dags/resources/stages/parse/table_definitions/optimism/OVM_FraudVerifier_event_FraudProofInitialized.json
dags/resources/stages/parse/table_definitions/optimism/OVM_L1CrossDomainMessenger_event_RelayedMessage.json
dags/resources/stages/parse/table_definitions/optimism/OVM_L1CrossDomainMessenger_event_SentMessage.json
dags/resources/stages/parse/table_definitions/optimism/OVM_StateCommitmentChain_event_StateBatchAppended.json
dags/resources/stages/parse/table_definitions/optimism/OVM_StateCommitmentChain_event_StateBatchDeleted.json

Add optimism

---

dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_BuyBaseToken.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_ChargeMaintainerFee.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_ChargePenalty.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_ClaimAssets.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_Deposit.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_Donate.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_OwnershipTransferPrepared.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_SellBaseToken.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_UpdateGasPriceLimit.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_UpdateK.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_UpdateLiquidityProviderFeeRate.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_UpdateMaintainerFeeRate.json
dags/resources/stages/parse/table_definitions/dodo/DODOPool_event_Withdraw.json

- Selected one of the pools 
- Parsed events using https://contract-parser.d5.ai/
- Changed `contract_address` to  ```"SELECT newBorn FROM ref('DODOZoo_event_DODOBirth')"```

Add dodo pool events (swap/withdraw/deposit/..)

---

dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v1_event_Donation.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v1_event_FeeTaken.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v1_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v1_event_Paused.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v1_event_Swapped.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v1_event_Unpaused.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v2_event_Bought.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v2_event_Donation.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v2_event_FeeTaken.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v2_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v2_event_Paused.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v2_event_Swapped.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v2_event_Unpaused.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v3_event_Bought.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v3_event_FeeTaken.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v3_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v3_event_Paused.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v3_event_Swapped.json
dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapper_v3_event_Unpaused.json

Add the 3 version of paraswap contracts listed by etherscan 
https://etherscan.io/accounts/label/paraswap

Add 3 different paraswap contracts

---

dags/resources/stages/parse/table_definitions/airswap/SwapOld_event_Authorize.json
dags/resources/stages/parse/table_definitions/airswap/SwapOld_event_Cancel.json
dags/resources/stages/parse/table_definitions/airswap/SwapOld_event_Invalidate.json
dags/resources/stages/parse/table_definitions/airswap/SwapOld_event_Revoke.json
dags/resources/stages/parse/table_definitions/airswap/SwapOld_event_Swap.json

Added the following contract:
https://etherscan.io/address/0x54d2690e97e477a4b33f40d6e4afdd4832c07c57#code

Add old airswap contract events

---

dags/resources/stages/parse/table_definitions/totle/Light_event_Cancel.json
dags/resources/stages/parse/table_definitions/totle/Light_event_CancelUpTo.json
dags/resources/stages/parse/table_definitions/totle/Light_event_Swap.json

Add following contract for totle: https://etherscan.io/address/0xC50cB225e0F45E814fd41Bcb3a120463aB1f04C3#events

Added missing LIght contract for totle

---

dags/resources/stages/parse/table_definitions/airswap/Light_event_Cancel.json
dags/resources/stages/parse/table_definitions/airswap/Light_event_CancelUpTo.json
dags/resources/stages/parse/table_definitions/airswap/Light_event_Swap.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_v7_event_LogSwap.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_v7_event_LogSwapCollection.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_v7_event_OwnershipRenounced.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_v7_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_v7_event_Paused.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_v7_event_Unpaused.json

- Moved wrong totle contract to airswap 
- Added missing airswap contract

Bugfix -> add totle, move wrong totle contract to airswap

---

dags/resources/stages/parse/table_definitions/bancor/BancorConverterFactory_event_NewConverter.json
dags/resources/stages/parse/table_definitions/bancor/BancorConverter_event_ConversionsEnable.json
dags/resources/stages/parse/table_definitions/bancor/BancorConverter_event_PriceDataUpdate.json

- Note that this pr removes some existing tables 
'0x5ed8c09f98b2b3ed37d07414bb8c3f065bbb802b','0x005f7ed737346941acd68d0292a86f21d173538a','0x9af06fcff3f867caf949ca8d2305795fd7bb2ede','0x0040c769b501805c6ebd77e3e2c64073fe4ebd69','0x009bb5e9fcf28e5e601b7d0e9e821da6365d0a9c','0x0a8079ce1fd9b1ae682d9f1b709609a05bf9b236','0xb6cc59f55d3a68635d07269bf12ba892a73c45aa','0x87558bafcf76866d70569bf36a60d78f0d0067fb'
these should be fixed in the next pr for bancor with older contracts

programmatically determine newConverter and Conversion events

---

dags/resources/stages/parse/table_definitions/oneinch_lp/MooniswapFactory_event_DefaultDecayPeriodVoteUpdate.json
dags/resources/stages/parse/table_definitions/oneinch_lp/MooniswapFactory_event_DefaultFeeVoteUpdate.json
dags/resources/stages/parse/table_definitions/oneinch_lp/MooniswapFactory_event_DefaultSlippageFeeVoteUpdate.json
dags/resources/stages/parse/table_definitions/oneinch_lp/MooniswapFactory_event_Deployed.json
dags/resources/stages/parse/table_definitions/oneinch_lp/MooniswapFactory_event_FeeCollectorUpdate.json
dags/resources/stages/parse/table_definitions/oneinch_lp/MooniswapFactory_event_GovernanceShareVoteUpdate.json
dags/resources/stages/parse/table_definitions/oneinch_lp/MooniswapFactory_event_GovernanceWalletUpdate.json
dags/resources/stages/parse/table_definitions/oneinch_lp/MooniswapFactory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/oneinch_lp/MooniswapFactory_event_Paused.json
dags/resources/stages/parse/table_definitions/oneinch_lp/MooniswapFactory_event_ReferralShareVoteUpdate.json
dags/resources/stages/parse/table_definitions/oneinch_lp/MooniswapFactory_event_Unpaused.json

It seems 1 inch recently [rebranded Mooniswap and deployed a new factory](https://github.com/1inch-exchange/1inch-liquidity-protocol/commit/ca3e0483a81cdee57208558dffbc76dd4c7047d8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

create dataset, add events for the factory

---

dags/resources/stages/parse/table_definitions/curve/ankrETHSwap_event_AddLiquidity.json
dags/resources/stages/parse/table_definitions/curve/ankrETHSwap_event_CommitNewAdmin.json
dags/resources/stages/parse/table_definitions/curve/ankrETHSwap_event_CommitNewFee.json
dags/resources/stages/parse/table_definitions/curve/ankrETHSwap_event_NewAdmin.json
dags/resources/stages/parse/table_definitions/curve/ankrETHSwap_event_NewFee.json
dags/resources/stages/parse/table_definitions/curve/ankrETHSwap_event_RampA.json
dags/resources/stages/parse/table_definitions/curve/ankrETHSwap_event_RemoveLiquidity.json
dags/resources/stages/parse/table_definitions/curve/ankrETHSwap_event_RemoveLiquidityImbalance.json
dags/resources/stages/parse/table_definitions/curve/ankrETHSwap_event_RemoveLiquidityOne.json
dags/resources/stages/parse/table_definitions/curve/ankrETHSwap_event_StopRampA.json
dags/resources/stages/parse/table_definitions/curve/ankrETHSwap_event_TokenExchange.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_AddLiquidity.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_CommitNewAdmin.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_CommitNewFee.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_NewAdmin.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_NewFee.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_RampA.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_RemoveLiquidity.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_RemoveLiquidityImbalance.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_RemoveLiquidityOne.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_StopRampA.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_TokenExchange.json
dags/resources/stages/parse/table_definitions/curve/sAAVESwap_event_TokenExchangeUnderlying.json

Added new Curve pools

---

dags/resources/stages/parse/table_definitions/maker/Vat_call_fold.json
dags/resources/stages/parse/table_definitions/maker/Vat_call_frob.json
dags/resources/stages/parse/table_definitions/maker/Vat_call_grab.json

Added Maker calls for fee calculations

---

dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_AddLiquidity.json
dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_CommitNewAdmin.json
dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_CommitNewFee.json
dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_NewAdmin.json
dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_NewFee.json
dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_RampA.json
dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_RemoveLiquidity.json
dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_RemoveLiquidityImbalance.json
dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_RemoveLiquidityOne.json
dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_StopRampA.json
dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_TokenExchange.json
dags/resources/stages/parse/table_definitions/curve/IronBankSwap_event_TokenExchangeUnderlying.json

Added IronBank Curve pool

---

dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_BRRUpdated.json
dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_BurnConfigSet.json
dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_EthReceived.json
dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_FeeDistributed.json
dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_KncBurned.json
dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_KyberDaoAddressSet.json
dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_KyberNetworkUpdated.json
dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_KyberProxyUpdated.json
dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_PlatformFeePaid.json
dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_RebatePaid.json
dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_RewardPaid.json
dags/resources/stages/parse/table_definitions/kyber/KyberFeeHandler_event_RewardsRemovedToBurn.json

Added Kyber FeeHandler

---

dags/resources/stages/parse/table_definitions/bancor/ConverterFactory_event_NewConverter.json
dags/resources/stages/parse/table_definitions/bancor/ConverterFactory_event_OwnerUpdate.json
dags/resources/stages/parse/table_definitions/bancor/ConverterUpgrader_event_ConverterOwned.json
dags/resources/stages/parse/table_definitions/bancor/ConverterUpgrader_event_ConverterUpgrade.json
dags/resources/stages/parse/table_definitions/bancor/ConverterUpgrader_event_OwnerUpdate.json
dags/resources/stages/parse/table_definitions/bancor/LiquidityPoolV1Converter_event_Activation.json
dags/resources/stages/parse/table_definitions/bancor/LiquidityPoolV1Converter_event_Conversion.json
dags/resources/stages/parse/table_definitions/bancor/LiquidityPoolV1Converter_event_ConversionFeeUpdate.json
dags/resources/stages/parse/table_definitions/bancor/LiquidityPoolV1Converter_event_LiquidityAdded.json
dags/resources/stages/parse/table_definitions/bancor/LiquidityPoolV1Converter_event_LiquidityRemoved.json
dags/resources/stages/parse/table_definitions/bancor/LiquidityPoolV1Converter_event_OwnerUpdate.json
dags/resources/stages/parse/table_definitions/bancor/LiquidityPoolV1Converter_event_PriceDataUpdate.json
dags/resources/stages/parse/table_definitions/bancor/LiquidityPoolV1Converter_event_TokenRateUpdate.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_Activation.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_Conversion.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_ConversionFeeUpdate.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_LiquidityAdded.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_LiquidityRemoved.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_OwnerUpdate.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_TokenRateUpdate.json

Added missing Bancor converters

---

dags/resources/stages/parse/table_definitions/bancor/ConverterFactory_event_NewConverter.json
dags/resources/stages/parse/table_definitions/bancor/ConverterFactory_v2_event_NewConverter.json
dags/resources/stages/parse/table_definitions/bancor/ConverterFactory_v2_event_OwnerUpdate.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_Conversion.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_ConversionFeeUpdate.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_LiquidityAdded.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_LiquidityRemoved.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_OwnerUpdate.json
dags/resources/stages/parse/table_definitions/bancor/StandardPoolConverter_event_TokenRateUpdate.json

Decided to fix bugs and noticed that it was possible to improve the recognition of Bancor converters

Fixed Bancor standard pools

---

dags/resources/stages/parse/table_definitions/bancor_network/BancorConverterFactory_v2_event_NewConverter.json

Bancor bugfix for v2 _contractName

---

dags/resources/stages/parse/table_definitions/bancor_network/Converter_event_Conversion.json

I found extra converter contracts so thought i would add this to v1. 
Looks like this requires deleting dataset and something equivalent to a full refresh

add more contracts to conversion 

---

dags/resources/stages/parse/table_definitions/curve/Registry_v2_event_PoolAdded.json
dags/resources/stages/parse/table_definitions/curve/Registry_v2_event_PoolRemoved.json

Add curev Registry v2

---

dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_batchSwapExactIn.json
dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_batchSwapExactOut.json
dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_multihopBatchSwapExactIn.json
dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_multihopBatchSwapExactOut.json
dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_smartSwapExactIn.json
dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_smartSwapExactOut.json

ready for review @medvedev1088 
Thank you

add balancer exchange proxy

---

dags/resources/stages/parse/table_definitions/opensea/OpenSeaENSResolver_event_ABIChanged.json
dags/resources/stages/parse/table_definitions/opensea/OpenSeaENSResolver_event_AddrChanged.json
dags/resources/stages/parse/table_definitions/opensea/OpenSeaENSResolver_event_AuthorisationChanged.json
dags/resources/stages/parse/table_definitions/opensea/OpenSeaENSResolver_event_ContenthashChanged.json
dags/resources/stages/parse/table_definitions/opensea/OpenSeaENSResolver_event_InterfaceChanged.json
dags/resources/stages/parse/table_definitions/opensea/OpenSeaENSResolver_event_NameChanged.json
dags/resources/stages/parse/table_definitions/opensea/OpenSeaENSResolver_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/opensea/OpenSeaENSResolver_event_PubkeyChanged.json
dags/resources/stages/parse/table_definitions/opensea/OpenSeaENSResolver_event_TextChanged.json
dags/resources/stages/parse/table_definitions/opensea/WyvernExchange_event_OrderApprovedPartOne.json
dags/resources/stages/parse/table_definitions/opensea/WyvernExchange_event_OrderApprovedPartTwo.json
dags/resources/stages/parse/table_definitions/opensea/WyvernExchange_event_OrderCancelled.json
dags/resources/stages/parse/table_definitions/opensea/WyvernExchange_event_OrdersMatched.json
dags/resources/stages/parse/table_definitions/opensea/WyvernExchange_event_OwnershipRenounced.json
dags/resources/stages/parse/table_definitions/opensea/WyvernExchange_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/opensea/WyvernProxyRegistry_event_OwnershipRenounced.json
dags/resources/stages/parse/table_definitions/opensea/WyvernProxyRegistry_event_OwnershipTransferred.json

Address Source: https://etherscan.io/accounts/label/opensea

Add opensea dataset

---

dags/resources/stages/parse/table_definitions/ruler/AdminUpgradeabilityProxy_event_AdminChanged.json
dags/resources/stages/parse/table_definitions/ruler/AdminUpgradeabilityProxy_event_Upgraded.json
dags/resources/stages/parse/table_definitions/ruler/BonusRewards_event_Deposit.json
dags/resources/stages/parse/table_definitions/ruler/BonusRewards_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/ruler/BonusRewards_event_PausedStatusUpdated.json
dags/resources/stages/parse/table_definitions/ruler/BonusRewards_event_Withdraw.json
dags/resources/stages/parse/table_definitions/ruler/Oracle_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/ruler/RULER_event_Approval.json
dags/resources/stages/parse/table_definitions/ruler/RULER_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/ruler/RULER_event_Transfer.json
dags/resources/stages/parse/table_definitions/ruler/RulerZap_event_OwnershipTransferred.json

Add Ruler events

---

dags/resources/stages/parse/table_definitions/rari/AdminUpgradeabilityProxy_event_AdminChanged.json
dags/resources/stages/parse/table_definitions/rari/AdminUpgradeabilityProxy_event_Upgraded.json
dags/resources/stages/parse/table_definitions/rari/RariFundController_event_CurrencyTrade.json
dags/resources/stages/parse/table_definitions/rari/RariFundController_event_FundDisabled.json
dags/resources/stages/parse/table_definitions/rari/RariFundController_event_FundEnabled.json
dags/resources/stages/parse/table_definitions/rari/RariFundController_event_FundManagerSet.json
dags/resources/stages/parse/table_definitions/rari/RariFundController_event_FundRebalancerSet.json
dags/resources/stages/parse/table_definitions/rari/RariFundController_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/rari/RariFundController_event_PoolAllocation.json
dags/resources/stages/parse/table_definitions/rari/RariFundProxy_event_FundManagerSet.json
dags/resources/stages/parse/table_definitions/rari/RariFundProxy_event_GsnTrustedSignerSet.json
dags/resources/stages/parse/table_definitions/rari/RariFundProxy_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/rari/RariFundProxy_event_PostWithdrawalExchange.json
dags/resources/stages/parse/table_definitions/rari/RariFundProxy_event_PreDepositExchange.json
dags/resources/stages/parse/table_definitions/rari/RariFundProxy_event_RelayHubChanged.json

Add Rari events

---

dags/resources/stages/parse/table_definitions/balancer/V2_Vault_event_PoolRegistered.json
dags/resources/stages/parse/table_definitions/balancer/V2_WeightedPoolFactory_call_create.json

sorry @medvedev1088 , a couple more

add tables needed for detecting weights

---

dags/resources/stages/parse/table_definitions/balancer/view_V2_pools_balances.sql
dags/resources/stages/parse/table_definitions/balancer/view_V2_pools_weights.sql

Ready for review @medvedev1088 Thank you!

Balancer v2 views

---

dags/resources/stages/parse/table_definitions/optimism/OVM_L1ETHGateway_event_DepositInitiated.json
dags/resources/stages/parse/table_definitions/optimism/OVM_L1ETHGateway_event_WithdrawalFinalized.json

Added parser for Optimism L1ETHGateway proxy contract. ABI was taken from ETH Gateway implementation contract: `0x384bC62a4bb9aE617c8dD0eC351d7780444EFDc0`

Add Optimism L1ETHGateway events

---

dags/resources/stages/parse/table_definitions/uniswap/NonfungiblePositionManager_event_Approval.json
dags/resources/stages/parse/table_definitions/uniswap/NonfungiblePositionManager_event_ApprovalForAll.json
dags/resources/stages/parse/table_definitions/uniswap/NonfungiblePositionManager_event_Collect.json
dags/resources/stages/parse/table_definitions/uniswap/NonfungiblePositionManager_event_DecreaseLiquidity.json
dags/resources/stages/parse/table_definitions/uniswap/NonfungiblePositionManager_event_IncreaseLiquidity.json
dags/resources/stages/parse/table_definitions/uniswap/NonfungiblePositionManager_event_Transfer.json
dags/resources/stages/parse/table_definitions/uniswap/NonfungibleTokenPositionDescriptor_event_UpdateTokenRatioPriority.json
dags/resources/stages/parse/table_definitions/uniswap/UniswapV3Factory_event_FeeAmountEnabled.json
dags/resources/stages/parse/table_definitions/uniswap/UniswapV3Factory_event_OwnerChanged.json
dags/resources/stages/parse/table_definitions/uniswap/UniswapV3Factory_event_PoolCreated.json

NOTE: Pools not added yet since they're not verified on Etherscan.

Added UniswapV3 contracts

---

dags/resources/stages/parse/table_definitions/balancer/view_V2_pools_weights.sql

Ready for review, @medvedev1088  thanks

add pools from WeightedPool2TokensFactory

---

dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x3179_event_Log.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x3179_event_LogSwap.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x3179_event_LogSwapCollection.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x3179_event_OwnershipRenounced.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x3179_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x3179_event_Paused.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x3179_event_Unpaused.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x7720_event_LogSwap.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x7720_event_LogSwapCollection.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x7720_event_OwnershipRenounced.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x7720_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x7720_event_Paused.json
dags/resources/stages/parse/table_definitions/totle/TotlePrimary_0x7720_event_Unpaused.json

Additional contract addresses are from Rowan (from Totle).

Add more Totle events

---

dags/resources/stages/parse/table_definitions/sablier/Sablier_event_CancelStream.json
dags/resources/stages/parse/table_definitions/sablier/Sablier_event_CreateCompoundingStream.json
dags/resources/stages/parse/table_definitions/sablier/Sablier_event_CreateStream.json
dags/resources/stages/parse/table_definitions/sablier/Sablier_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/sablier/Sablier_event_Paused.json
dags/resources/stages/parse/table_definitions/sablier/Sablier_event_PauserAdded.json
dags/resources/stages/parse/table_definitions/sablier/Sablier_event_PauserRemoved.json
dags/resources/stages/parse/table_definitions/sablier/Sablier_event_PayInterest.json
dags/resources/stages/parse/table_definitions/sablier/Sablier_event_TakeEarnings.json
dags/resources/stages/parse/table_definitions/sablier/Sablier_event_Unpaused.json
dags/resources/stages/parse/table_definitions/sablier/Sablier_event_UpdateFee.json
dags/resources/stages/parse/table_definitions/sablier/Sablier_event_WithdrawFromStream.json

Add Sablier events

---

dags/resources/stages/parse/table_definitions/maker/Clipper_event_Deny.json
dags/resources/stages/parse/table_definitions/maker/Clipper_event_File.json
dags/resources/stages/parse/table_definitions/maker/Clipper_event_Kick.json
dags/resources/stages/parse/table_definitions/maker/Clipper_event_Redo.json
dags/resources/stages/parse/table_definitions/maker/Clipper_event_Rely.json
dags/resources/stages/parse/table_definitions/maker/Clipper_event_Take.json
dags/resources/stages/parse/table_definitions/maker/Clipper_event_Yank.json

Added maker liquidation 2.0 contract events

---

dags/resources/stages/parse/table_definitions/cryptokitties_auction/SaleClockAuction_event_AuctionCancelled.json
dags/resources/stages/parse/table_definitions/cryptokitties_auction/SaleClockAuction_event_AuctionCreated.json
dags/resources/stages/parse/table_definitions/cryptokitties_auction/SaleClockAuction_event_AuctionSuccessful.json
dags/resources/stages/parse/table_definitions/cryptokitties_auction/SaleClockAuction_event_Pause.json
dags/resources/stages/parse/table_definitions/cryptokitties_auction/SaleClockAuction_event_Unpause.json

Added cryptokitties_auction events

---

dags/resources/stages/parse/table_definitions/oneinch/AggregationRouterV3_event_Error.json
dags/resources/stages/parse/table_definitions/oneinch/AggregationRouterV3_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/oneinch/AggregationRouterV3_event_Swapped.json
dags/resources/stages/parse/table_definitions/oneinch/MerkleDistributor_event_Claimed.json

- add v3 AggregationRouterV3 
- add MerkleDistributor for OneInch Airdrops 
- Cant find abi for : https://etherscan.io/address/0xdb38ae75c5f44276803345f7f02e95a0aeef5944

OneInch v3 router + Airdrop Merkle Distributor

---

dags/resources/stages/parse/table_definitions/maker/Dog_event_Bark.json
dags/resources/stages/parse/table_definitions/maker/Dog_event_Cage.json
dags/resources/stages/parse/table_definitions/maker/Dog_event_Deny.json
dags/resources/stages/parse/table_definitions/maker/Dog_event_Digs.json
dags/resources/stages/parse/table_definitions/maker/Dog_event_File.json
dags/resources/stages/parse/table_definitions/maker/Dog_event_Rely.json

Add Dog contracts for Maker liquidation 2.0

---

dags/resources/stages/parse/table_definitions/tornado/TornadoCash_event_Deposit.json
dags/resources/stages/parse/table_definitions/tornado/TornadoCash_event_Withdrawal.json
dags/resources/stages/parse/table_definitions/tornado/TornadoProxy_event_EncryptedNote.json
dags/resources/stages/parse/table_definitions/tornado/TornadoProxy_event_InstanceStateUpdated.json
dags/resources/stages/parse/table_definitions/tornado/TornadoProxy_event_TornadoTreesUpdated.json

Added Tornado events

---

dags/resources/stages/parse/table_definitions/artblocks/GenArt721_event_Approval.json
dags/resources/stages/parse/table_definitions/artblocks/GenArt721_event_ApprovalForAll.json
dags/resources/stages/parse/table_definitions/artblocks/GenArt721_event_Mint.json
dags/resources/stages/parse/table_definitions/artblocks/GenArt721_event_Transfer.json

Added Artblocks events

---

dags/resources/stages/parse/table_definitions/mintable/MintableExchange_event_NFTSold.json
dags/resources/stages/parse/table_definitions/mintable/MintableExchange_event_OwnershipTransferred.json

- nft sold 
- ownership transferred

Add mintable exchange events

---

dags/resources/stages/parse/table_definitions/eden/EdenToken_event_Approval.json
dags/resources/stages/parse/table_definitions/eden/EdenToken_event_AuthorizationUsed.json
dags/resources/stages/parse/table_definitions/eden/EdenToken_event_MetadataManagerChanged.json
dags/resources/stages/parse/table_definitions/eden/EdenToken_event_RoleAdminChanged.json
dags/resources/stages/parse/table_definitions/eden/EdenToken_event_RoleGranted.json
dags/resources/stages/parse/table_definitions/eden/EdenToken_event_RoleRevoked.json
dags/resources/stages/parse/table_definitions/eden/EdenToken_event_TokenMetaUpdated.json
dags/resources/stages/parse/table_definitions/eden/EdenToken_event_Transfer.json

Added Eden contracts for event watching

feat: Added Eden events

---

dags/resources/stages/parse/table_definitions/balancer/V2_MetaStablePoolFactory_call_create.json
dags/resources/stages/parse/table_definitions/balancer/V2_MetaStablePoolFactory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_MetaStablePool_event_Transfer.json
dags/resources/stages/parse/table_definitions/balancer/view_V2_bpt_balances.sql

ready for review, @medvedev1088 , thank you!

add meta stable pools

---

dags/resources/stages/parse/table_definitions/enclaves_dex/EnclavesDEX_event_Cancel.json
dags/resources/stages/parse/table_definitions/enclaves_dex/EnclavesDEX_event_Deposit.json
dags/resources/stages/parse/table_definitions/enclaves_dex/EnclavesDEX_event_Order.json
dags/resources/stages/parse/table_definitions/enclaves_dex/EnclavesDEX_event_Rebalance.json
dags/resources/stages/parse/table_definitions/enclaves_dex/EnclavesDEX_event_Trade.json
dags/resources/stages/parse/table_definitions/enclaves_dex/EnclavesDEX_event_Withdraw.json
dags/resources/stages/parse/table_definitions/enclaves_dex/EnclavesDEX_event_WithdrawPreSigned.json

Add Enclaves DEX events

---

dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogAddPool.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogClaim.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogDeposit.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogEmergencyWithdraw.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogGroPerBlock.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogLpTokenAdded.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogMaxGroPerBlock.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogNewManagment.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogNewMigrator.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogNewVester.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogSetPool.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogUpdatePool.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_LogWithdraw.json
dags/resources/stages/parse/table_definitions/gro/LPTokenStaker_event_OwnershipTransferred.json

@medvedev1088 could you please review and merge? Thank you!

add gro staking contract events

---

dags/resources/stages/parse/table_definitions/genieswap/GenieSwap_event_OwnershipTransferred.json

@medvedev1088 No rush, it's still in beta, but it'd be great to have this one.

Added GenieSwap event

---

dags/resources/stages/parse/table_definitions/olympus/OP_AlchemixCustomTreasury_BondContractToggled.json
dags/resources/stages/parse/table_definitions/olympus/OP_AlchemixCustomTreasury_bondContract.json
dags/resources/stages/parse/table_definitions/olympus/OP_AlchemixCustomTreasury_deposit.json
dags/resources/stages/parse/table_definitions/olympus/OP_AlchemixCustomTreasury_event_BondContractToggled.json
dags/resources/stages/parse/table_definitions/olympus/OP_AlchemixCustomTreasury_event_Withdraw.json
dags/resources/stages/parse/table_definitions/olympus/OP_AlchemixCustomTreasury_payoutToken.json
dags/resources/stages/parse/table_definitions/olympus/OP_AlchemixCustomTreasury_policy.json
dags/resources/stages/parse/table_definitions/olympus/OP_AlchemixCustomTreasury_toggleBondContract.json
dags/resources/stages/parse/table_definitions/olympus/OP_AlchemixCustomTreasury_transferManagment.json
dags/resources/stages/parse/table_definitions/olympus/OP_AlchemixCustomTreasury_valueOfToken.json
dags/resources/stages/parse/table_definitions/olympus/OP_AlchemixCustomTreasury_withdraw.json

“Used the Contract Parser: https://contract-parser.d5.ai”
@medvedev1088 can you review, please?
I made a new PR with the features that you requested.
Thanks

Olympus Pro Alchemix - updated folder system + added variable names.

---

dags/resources/stages/parse/table_definitions/eulerbeats/EulerBeats_event_ApprovalForAll.json
dags/resources/stages/parse/table_definitions/eulerbeats/EulerBeats_event_MintOriginal.json
dags/resources/stages/parse/table_definitions/eulerbeats/EulerBeats_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/eulerbeats/EulerBeats_event_PrintBurned.json
dags/resources/stages/parse/table_definitions/eulerbeats/EulerBeats_event_PrintMinted.json
dags/resources/stages/parse/table_definitions/eulerbeats/EulerBeats_event_TransferBatch.json
dags/resources/stages/parse/table_definitions/eulerbeats/EulerBeats_event_TransferSingle.json
dags/resources/stages/parse/table_definitions/eulerbeats/EulerBeats_event_URI.json

I parsed the Eulerbeats contract as an example ERC1155.

Added Eulerbeats events

---

dags/resources/stages/parse/table_definitions/ethblocks/EthBlocks_event_Approval.json
dags/resources/stages/parse/table_definitions/ethblocks/EthBlocks_event_ApprovalForAll.json
dags/resources/stages/parse/table_definitions/ethblocks/EthBlocks_event_MetaTransactionExecuted.json
dags/resources/stages/parse/table_definitions/ethblocks/EthBlocks_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/ethblocks/EthBlocks_event_RoyaltiesSet.json
dags/resources/stages/parse/table_definitions/ethblocks/EthBlocks_event_Transfer.json
dags/resources/stages/parse/table_definitions/ethblocks/EthBlocks_event_Updated.json

Added EthBlocks events

---

dags/resources/stages/parse/table_definitions/balancer/view_LM_state.sql
dags/resources/stages/parse/table_definitions/balancer/view_LM_transfers.sql

@medvedev1088 we're refactoring our liquidity mining scripts, would appreciate the creation of these new views. Thank you.

Create liquidity mining views

---

dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_allowance.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_approve.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_balanceOf.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_burn.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_decimals.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_decreaseAllowance.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_increaseAllowance.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_mint.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_name.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_owner.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_renounceOwnership.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_symbol.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_totalSupply.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_transfer.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_transferFrom.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_call_transferOwnership.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_event_Approval.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_event_Burn.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/terra/WrappedUST_event_Transfer.json

Added Terra for UST tracking.  Requesting review by @medvedev1088

uses the contract parser: https://nansen-contract-parser-prod.web.app/

---

dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_Approval.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_ApprovalForAll.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_BaseURIUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_Minted.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_NFTCreatorMigrated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_NFTMarketUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_NFTMetadataUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_NFTOwnerMigrated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_PaymentAddressMigrated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_ProxyCallContractUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_TokenCreatorPaymentAddressSet.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_TokenCreatorUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_TokenIPFSPathUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFT721_event_Transfer.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_MarketFeesUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_PrivateSaleFinalized.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionBidPlaced.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionCanceled.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionCanceledByAdmin.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionConfigUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionCreated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionFinalized.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionSellerMigrated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_WithdrawPending.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_Withdrawal.json

Followed these instructions https://medium.com/@ASvanevik/how-to-get-any-ethereum-smart-contract-into-bigquery-in-8-mins-bab5db1fdeee
Foundations two contracts are mentioned here, and they are proxy contracts https://foundation.app/blog/foundations-smart-contracts-are-verified-and-open-source

Include pipeline steps for the Foundation Market and NFT smart contracts

---

dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_MarketFeesUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_PrivateSaleFinalized.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionBidPlaced.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionCanceled.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionCanceledByAdmin.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionConfigUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionCreated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionFinalized.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionSellerMigrated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_ReserveAuctionUpdated.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_WithdrawPending.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_Withdrawal.json

Previously, in #320 I included the incorrect address for the foundation market contract, which made it not add any data to the table. This fixes this issue (pointing it here: https://etherscan.io/address/0xcDA72070E455bb31C7690a170224Ce43623d0B6f)
cc @araa47 who previously looked at this.

[Bug] Fix foundation NFT contract address.

---

dags/resources/stages/parse/table_definitions/common/All_call_setBaseURI.json
dags/resources/stages/parse/table_definitions/common/All_event_Upgraded.json

Allows us to track when erc721 metadata is changed and to what value.

Add setBaseURI call

---

dags/resources/stages/parse/table_definitions/argent/WalletFactory_3_event_WalletCreated.json
dags/resources/stages/parse/table_definitions/argent/WalletFactory_4_event_WalletCreated.json
dags/resources/stages/parse/table_definitions/argent/WalletFactory_5_event_WalletCreated.json

have to add more because they have multiple contracts for this

add more argent WalletCreated events

---

dags/resources/stages/parse/table_definitions/chainlink/Aggregator_ETH_USD_event_AnswerUpdated.json
dags/resources/stages/parse/table_definitions/curve/RegistryProvider_event_AddressModified.json
dags/resources/stages/parse/table_definitions/curve/RegistryProvider_event_NewAddressIdentifier.json

Fix for Chainlink ETH-USD feed

---

dags/resources/stages/parse/table_definitions/curve/tricrypto2_event_AddLiquidity.json
dags/resources/stages/parse/table_definitions/curve/tricrypto2_event_ClaimAdminFee.json
dags/resources/stages/parse/table_definitions/curve/tricrypto2_event_CommitNewAdmin.json
dags/resources/stages/parse/table_definitions/curve/tricrypto2_event_CommitNewParameters.json
dags/resources/stages/parse/table_definitions/curve/tricrypto2_event_NewAdmin.json
dags/resources/stages/parse/table_definitions/curve/tricrypto2_event_NewParameters.json
dags/resources/stages/parse/table_definitions/curve/tricrypto2_event_RampAgamma.json
dags/resources/stages/parse/table_definitions/curve/tricrypto2_event_RemoveLiquidity.json
dags/resources/stages/parse/table_definitions/curve/tricrypto2_event_RemoveLiquidityOne.json
dags/resources/stages/parse/table_definitions/curve/tricrypto2_event_StopRampA.json
dags/resources/stages/parse/table_definitions/curve/tricrypto2_event_TokenExchange.json

Add events for curve tricrypto2 pool 
https://curve.fi/tricrypto2
https://etherscan.io/address/0xD51a44d3FaE010294C616388b506AcdA1bfAAE46

Add Curve tricrypto2 pool events

---

dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_DepositMade.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_GoldfinchConfigUpdated.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_InterestCollected.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_InvestmentMadeInJunior.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_InvestmentMadeInSenior.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_Paused.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_PrincipalCollected.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_PrincipalWrittenDown.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_ReserveFundsCollected.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_RoleGranted.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_RoleRevoked.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_Unpaused.json
dags/resources/stages/parse/table_definitions/goldfinch/SeniorPool_event_WithdrawalMade.json

“Used the Contract Parser: https://contract-parser.d5.ai”

Added goldfinch events

---

dags/resources/stages/parse/table_definitions/common/ERC223_event_Transfer.json

Add ERC223 Transfer event

---

dags/resources/stages/parse/table_definitions/curve/frax_event_AddLiquidity.json
dags/resources/stages/parse/table_definitions/curve/frax_event_Approval.json
dags/resources/stages/parse/table_definitions/curve/frax_event_CommitNewAdmin.json
dags/resources/stages/parse/table_definitions/curve/frax_event_CommitNewFee.json
dags/resources/stages/parse/table_definitions/curve/frax_event_NewAdmin.json
dags/resources/stages/parse/table_definitions/curve/frax_event_NewFee.json
dags/resources/stages/parse/table_definitions/curve/frax_event_RampA.json
dags/resources/stages/parse/table_definitions/curve/frax_event_RemoveLiquidity.json
dags/resources/stages/parse/table_definitions/curve/frax_event_RemoveLiquidityImbalance.json
dags/resources/stages/parse/table_definitions/curve/frax_event_RemoveLiquidityOne.json
dags/resources/stages/parse/table_definitions/curve/frax_event_StopRampA.json
dags/resources/stages/parse/table_definitions/curve/frax_event_TokenExchange.json
dags/resources/stages/parse/table_definitions/curve/frax_event_TokenExchangeUnderlying.json
dags/resources/stages/parse/table_definitions/curve/frax_event_Transfer.json

Adding frax events on curve for Ethereum

Adding frax events on curve for Ethereum

---

dags/resources/stages/parse/table_definitions/convex/CvxLockerV1_event_KickReward.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV1_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV1_event_Recovered.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV1_event_RewardAdded.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV1_event_RewardPaid.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV1_event_Staked.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV1_event_Withdrawn.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV2_event_KickReward.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV2_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV2_event_Recovered.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV2_event_RewardAdded.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV2_event_RewardPaid.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV2_event_Staked.json
dags/resources/stages/parse/table_definitions/convex/CvxLockerV2_event_Withdrawn.json

Add Support for Convex Locker Events (v1/v2) 

Add Convex Locker Events

---

dags/resources/stages/parse/table_definitions/euler/Euler_event_AssetStatus.json

Add Euler AssetStatus event
I used [abi-parser](https://contract-parser.d5.ai/) to build the table definitions

Add Euler AssetStatus event

---

dags/resources/stages/parse/table_definitions/gnosis_safe/GnosisSafe_Mastercopy_v1_3_0_call_setup.json

Add support for Gnosis Safe v1.3 call events
I used [contract-parser](https://contract-parser.d5.ai/)

Add GnosisSafe_Mastercopy_v1_3_0_call_setup.json

---

dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_event_BondingCurveStatusUpdate.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_event_CallTargetStatusUpdate.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_event_NFTDeposit.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_event_NewPair.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_event_ProtocolFeeMultiplierUpdate.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_event_ProtocolFeeRecipientUpdate.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_event_RouterStatusUpdate.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_event_TokenDeposit.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_pairTransferERC20From.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_pairTransferNFTFrom.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_robustSwapERC20ForAnyNFTs.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_robustSwapERC20ForSpecificNFTs.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_robustSwapERC20ForSpecificNFTsAndNFTsToToken.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_robustSwapETHForAnyNFTs.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_robustSwapETHForSpecificNFTs.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_robustSwapETHForSpecificNFTsAndNFTsToToken.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_robustSwapNFTsForToken.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_swapERC20ForAnyNFTs.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_swapERC20ForSpecificNFTs.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_swapETHForAnyNFTs.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_swapETHForSpecificNFTs.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_swapNFTsForAnyNFTsThroughERC20.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_swapNFTsForAnyNFTsThroughETH.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_swapNFTsForSpecificNFTsThroughERC20.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_swapNFTsForSpecificNFTsThroughETH.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMRouter_call_swapNFTsForToken.json

Add Sudoswap Factory events and Router calls
ie: I used cli tools to build the table definitions

Add Sudoswap Factory events and Router calls

---

dags/resources/stages/parse/table_definitions/compound/cToken_event_Approval.json
dags/resources/stages/parse/table_definitions/compound/cToken_event_Transfer.json

Added cToken_event_Approval.json and cToken_event_Transfer.json
cc @medvedev1088

Create cToken_event_Approval.json and cToken_event_Transfer.json

---

dags/resources/stages/parse/table_definitions/tbtc/TBTC_V1_event_Transfer.json
dags/resources/stages/parse/table_definitions/tbtc/TBTC_V2_event_Transfer.json

ie: Add support for TBTC V1 + V2 tansfer events

Added TBTCV1 + V2 events

---

dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_Approval.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_AuthorizationCanceled.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_AuthorizationUsed.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_Blacklisted.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_BlacklisterChanged.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_Burn.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_ExchangeRateUpdated.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_MasterMinterChanged.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_Mint.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_MinterConfigured.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_MinterRemoved.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_OracleUpdated.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_Pause.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_PauserChanged.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_RescuerChanged.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_Transfer.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_UnBlacklisted.json
dags/resources/stages/parse/table_definitions/coinbase/StakedTokenV1_event_Unpause.json
dags/resources/stages/parse/table_definitions/stakehound/StakedTokenV2_event_Approval.json
dags/resources/stages/parse/table_definitions/stakehound/StakedTokenV2_event_Blacklisted.json
dags/resources/stages/parse/table_definitions/stakehound/StakedTokenV2_event_LogSupplyControllerUpdated.json
dags/resources/stages/parse/table_definitions/stakehound/StakedTokenV2_event_LogTokenDistribution.json
dags/resources/stages/parse/table_definitions/stakehound/StakedTokenV2_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/stakehound/StakedTokenV2_event_Paused.json
dags/resources/stages/parse/table_definitions/stakehound/StakedTokenV2_event_Transfer.json
dags/resources/stages/parse/table_definitions/stakehound/StakedTokenV2_event_Unpaused.json
dags/resources/stages/parse/table_definitions/stakehound/StakedTokenV2_event_WarningMaxExpectedSupplyExceeded.json

Add support for Stakehound and Coinbase StakedTokenV1 Contract Events
I Used the Contract Parser: https://contract-parser.d5.ai to build the table definitions

Added Stakehound and Coinbase StakedTokenV1 Events

---

dags/resources/stages/parse/table_definitions/truefi/TrueFiPool2_event_Borrow.json
dags/resources/stages/parse/table_definitions/truefi/TrueFiPool2_event_Repaid.json

Fix query in TrueFi table definitions

Fix TrueFi table definitions

---

dags/resources/stages/parse/table_definitions/stakewise/StakedEthToken_event_Transfer.json

ie: Add support for stakewise stakedethtoken Transfer event
ie: I used [abi-parser](https://contract-parser.d5.ai/)

add stakewise stakedethtoken Transfer event

---

dags/resources/stages/parse/table_definitions/euler/Euler_event_MarketActivated.json

Add support for Euler Market Activated events

Add Euler MarketActivated event

---

dags/resources/stages/parse/table_definitions/rocketpool/RocketMinipoolManager_event_MinipoolCreated.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketMinipoolManager_event_MinipoolDestroyed.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketTokenRETH_event_Approval.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketTokenRETH_event_EtherDeposited.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketTokenRETH_event_TokensBurned.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketTokenRETH_event_TokensMinted.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketTokenRETH_event_Transfer.json

Add support for rocketpool rETH contract events 
ie: I used [abi-parser](https://contract-parser.d5.ai/)

add rocketpool rETH events and Rocketpool MiniPool Manager Events

---

dags/resources/stages/parse/table_definitions/lido/Lido_event_ELRewardsReceived.json
dags/resources/stages/parse/table_definitions/rocketpool/RocketRewardsPool_event_RPLTokensClaimed.json
dags/resources/stages/parse/table_definitions/stakewise/RewardEthToken_event_Approval.json
dags/resources/stages/parse/table_definitions/stakewise/RewardEthToken_event_ProtocolFeeRecipientUpdated.json
dags/resources/stages/parse/table_definitions/stakewise/RewardEthToken_event_ProtocolFeeUpdated.json
dags/resources/stages/parse/table_definitions/stakewise/RewardEthToken_event_RewardsToggled.json
dags/resources/stages/parse/table_definitions/stakewise/RewardEthToken_event_RewardsUpdated.json
dags/resources/stages/parse/table_definitions/stakewise/RewardEthToken_event_RoleAdminChanged.json
dags/resources/stages/parse/table_definitions/stakewise/RewardEthToken_event_RoleGranted.json
dags/resources/stages/parse/table_definitions/stakewise/RewardEthToken_event_RoleRevoked.json
dags/resources/stages/parse/table_definitions/stakewise/RewardEthToken_event_Transfer.json
dags/resources/stages/parse/table_definitions/stakewise/RewardEthToken_event_Unpaused.json

ie: Add support for lido, rocketpool and stakewise reward claimed events
ie: I used [abi-parser](https://contract-parser.d5.ai/)

adding lido, rockpool and stakewise's reward claimed events

---

dags/resources/stages/parse/table_definitions/convex/CrvDepositor_call_deposit.json
dags/resources/stages/parse/table_definitions/convex/CrvDepositor_call_depositAll.json
dags/resources/stages/parse/table_definitions/convex/CurveBooster_event_Deposited.json
dags/resources/stages/parse/table_definitions/convex/CurveBooster_event_Withdrawn.json
dags/resources/stages/parse/table_definitions/convex/FxsDepositor_call_deposit.json
dags/resources/stages/parse/table_definitions/convex/FxsDepositor_call_depositAll.json
dags/resources/stages/parse/table_definitions/convex/cvxCRVRewards_event_RewardAdded.json
dags/resources/stages/parse/table_definitions/convex/cvxCRVRewards_event_RewardPaid.json
dags/resources/stages/parse/table_definitions/convex/cvxCRVRewards_event_Staked.json
dags/resources/stages/parse/table_definitions/convex/cvxCRVRewards_event_Withdrawn.json
dags/resources/stages/parse/table_definitions/convex/cvxFXSRewards_event_RewardAdded.json
dags/resources/stages/parse/table_definitions/convex/cvxFXSRewards_event_RewardPaid.json
dags/resources/stages/parse/table_definitions/convex/cvxFXSRewards_event_Staked.json
dags/resources/stages/parse/table_definitions/convex/cvxFXSRewards_event_Withdrawn.json
dags/resources/stages/parse/table_definitions/convex/cvxRewards_event_RewardAdded.json
dags/resources/stages/parse/table_definitions/convex/cvxRewards_event_RewardPaid.json
dags/resources/stages/parse/table_definitions/convex/cvxRewards_event_Staked.json
dags/resources/stages/parse/table_definitions/convex/cvxRewards_event_Withdrawn.json

Add Convex-Curve & Convex-Frax events for Curve LP Boost,  cvxCRV & cvxFXS deposits, and CVX staking.
I used [abi-parser](https://contract-parser.d5.ai/) to build the table definitions.
None

Add additional Convex-Curve & Convex-Frax events and calls

---

dags/resources/stages/parse/table_definitions/angle/agEUR_event_Transfer.json
dags/resources/stages/parse/table_definitions/circle/EuroCoin_event_Burn.json
dags/resources/stages/parse/table_definitions/circle/EuroCoin_event_Mint.json
dags/resources/stages/parse/table_definitions/circle/EuroCoin_event_Transfer.json
dags/resources/stages/parse/table_definitions/stasis/EURS_event_Transfer.json
dags/resources/stages/parse/table_definitions/tether/EuroTether_event_Mint.json
dags/resources/stages/parse/table_definitions/tether/EuroTether_event_Redeem.json
dags/resources/stages/parse/table_definitions/tether/EuroTether_event_Transfer.json
dags/resources/stages/parse/table_definitions/tether/TetherCNH_event_Issue.json
dags/resources/stages/parse/table_definitions/tether/TetherCNH_event_Redeem.json
dags/resources/stages/parse/table_definitions/tether/TetherCNH_event_Transfer.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueAUD_event_Burn.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueAUD_event_Mint.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueAUD_event_Transfer.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueCAD_event_Burn.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueCAD_event_Mint.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueCAD_event_Transfer.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueGBP_event_Burn.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueGBP_event_Mint.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueGBP_event_Transfer.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueHKD_event_Burn.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueHKD_event_Mint.json
dags/resources/stages/parse/table_definitions/trusttoken/TrueHKD_event_Transfer.json

Add support for the following stablecoins: 
- agEUR
- EUROC
- EURS
- EURT
- CNHT
- TGBP
- TAUD
- TCAD
- THKD

add support for fiat stablecoins

---

dags/resources/stages/parse/table_definitions/arrakis/factory_event_PoolCreated.json

Add Arrakis finance base table for pool events
This PR must be merged before the related [#413] PR

Add arrakis base table for pool events

---

dags/resources/stages/parse/table_definitions/abracadabra/BentoBoxV1_event_LogDeploy.json
dags/resources/stages/parse/table_definitions/abracadabra/DegenBox_event_LogDeploy.json

Add base tables for the Abracadabra markets
I used [abi-parser](https://contract-parser.d5.ai/) to build the table definitions
This PR must be merged before #424

Add base tables for Abracadabra markets

---

dags/resources/stages/parse/table_definitions/stakewise/StakeWiseToken_event_Transfer.json

ie: Add support for stakewise transfer events
ie: I used [abi-parser](https://contract-parser.d5.ai/)

add stakewise transfer event

---

dags/resources/stages/parse/table_definitions/opensea/SeaDrop_event_AllowListUpdated.json
dags/resources/stages/parse/table_definitions/opensea/SeaDrop_event_AllowedFeeRecipientUpdated.json
dags/resources/stages/parse/table_definitions/opensea/SeaDrop_event_CreatorPayoutAddressUpdated.json
dags/resources/stages/parse/table_definitions/opensea/SeaDrop_event_DropURIUpdated.json
dags/resources/stages/parse/table_definitions/opensea/SeaDrop_event_PayerUpdated.json
dags/resources/stages/parse/table_definitions/opensea/SeaDrop_event_PublicDropUpdated.json
dags/resources/stages/parse/table_definitions/opensea/SeaDrop_event_SeaDropMint.json
dags/resources/stages/parse/table_definitions/opensea/SeaDrop_event_SignedMintValidationParamsUpdated.json
dags/resources/stages/parse/table_definitions/opensea/SeaDrop_event_TokenGatedDropStageUpdated.json

Adding Seadrop, OpenSea's Airdrop Implementation
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/) do download the table definitions
None

Adding Seadrop (OpenSea's Airdrop implementation)

---

dags/resources/stages/parse/table_definitions/convex/CurveVoterProxy_call_claimCrv.json
dags/resources/stages/parse/table_definitions/convex/CurveVoterProxy_call_claimFees.json
dags/resources/stages/parse/table_definitions/convex/CurveVoterProxy_call_claimRewards.json
dags/resources/stages/parse/table_definitions/convex/CurveVoterProxy_call_deposit.json
dags/resources/stages/parse/table_definitions/convex/CurveVoterProxy_call_withdraw.json
dags/resources/stages/parse/table_definitions/convex/CurveVoterProxy_call_withdrawAll.json

Add additional Convex Finance calls
ie: I used [abi-parser](https://contract-parser.d5.ai/) to build the table definitions
None

Add additional Convex Finance calls

---

dags/resources/stages/parse/table_definitions/maker/IlkRegistry_call_add.json
dags/resources/stages/parse/table_definitions/maker/JoinFab_event_NewJoin.json
dags/resources/stages/parse/table_definitions/yearn/Vault_Deployer_event_NewExperimentalVault.json
dags/resources/stages/parse/table_definitions/yearn/VeCurveVault_call_claim.json
dags/resources/stages/parse/table_definitions/yearn/VeCurveVault_call_claimFor.json
dags/resources/stages/parse/table_definitions/yearn/Woofy_call_unwoof.json
dags/resources/stages/parse/table_definitions/yearn/Woofy_call_woof.json
dags/resources/stages/parse/table_definitions/yearn/Woofy_event_Transfer.json

ie: Add Yearn and Maker Vaults and MCDs creation events and calls
ie: I used [abi-parser](https://contract-parser.d5.ai/) to build the table definitions
---

Add Yearn and Maker Vaults and MCDs

---

dags/resources/stages/parse/table_definitions/maker/mcdFab_call_exit.json
dags/resources/stages/parse/table_definitions/maker/mcdFab_call_join.json
dags/resources/stages/parse/table_definitions/maker/mcdIlk_call_exit.json
dags/resources/stages/parse/table_definitions/maker/mcdIlk_call_join.json
dags/resources/stages/parse/table_definitions/maker/mcdPSM_call_exit.json
dags/resources/stages/parse/table_definitions/maker/mcdPSM_call_join.json
dags/resources/stages/parse/table_definitions/maker/mcd_call_exit.json
dags/resources/stages/parse/table_definitions/maker/mcd_call_join.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_call_deposit.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_call_redeem.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_call_supplyAave.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_call_supplyCompound.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_call_supplyDydx.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_call_supplyFulcrum.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_call_withdraw.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_call_withdrawAave.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_call_withdrawDydx.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_call_withdrawSomeCompound.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_call_withdrawSomeFulcrum.json
dags/resources/stages/parse/table_definitions/yearn/V0Vault_event_Transfer.json
dags/resources/stages/parse/table_definitions/yearn/V1Vault_call_deposit.json
dags/resources/stages/parse/table_definitions/yearn/V1Vault_call_depositAll.json
dags/resources/stages/parse/table_definitions/yearn/V1Vault_call_earn.json
dags/resources/stages/parse/table_definitions/yearn/V1Vault_call_withdraw.json
dags/resources/stages/parse/table_definitions/yearn/V1Vault_call_withdrawAll.json
dags/resources/stages/parse/table_definitions/yearn/V1Vault_event_Transfer.json
dags/resources/stages/parse/table_definitions/yearn/V2Vault_call_deposit.json
dags/resources/stages/parse/table_definitions/yearn/V2Vault_call_withdraw.json
dags/resources/stages/parse/table_definitions/yearn/V2Vault_event_Transfer.json

ie: Add Yearn and Maker events and calls for Vaults and MCDs (based on #436)
ie: I used [abi-parser](https://contract-parser.d5.ai/) to build the table definitions
Please merge #436 before merging this PR. Thank you

Add Yearn and Maker events and calls

---

dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_call_createPairERC20.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_call_createPairETH.json

added calls to the factory for new pairs into the existing sudoswap folder
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table defenitions

added calls to the sudoswap factory for new pairs

---

dags/resources/stages/parse/table_definitions/tether/XAUt_v2_TetherToken_event_Mint.json
dags/resources/stages/parse/table_definitions/tether/XAUt_v2_TetherToken_event_Redeem.json

ABI for XAUt_v2 that I merged yesterday needed a fix

Fixed ABI bug with v2 of XAUt token

---

dags/resources/stages/parse/table_definitions/reflexer/CoinJoin_event_Exit.json
dags/resources/stages/parse/table_definitions/reflexer/CoinJoin_event_Join.json
dags/resources/stages/parse/table_definitions/reflexer/CollateralETHJoin1_event_Exit.json
dags/resources/stages/parse/table_definitions/reflexer/CollateralETHJoin1_event_Join.json
dags/resources/stages/parse/table_definitions/reflexer/DSProxyFactory_event_Created.json
dags/resources/stages/parse/table_definitions/reflexer/GebSafeManager_event_AllowSAFE.json
dags/resources/stages/parse/table_definitions/reflexer/GebSafeManager_event_EnterSystem.json
dags/resources/stages/parse/table_definitions/reflexer/GebSafeManager_event_ModifySAFECollateralization.json
dags/resources/stages/parse/table_definitions/reflexer/GebSafeManager_event_MoveSAFE.json
dags/resources/stages/parse/table_definitions/reflexer/GebSafeManager_event_OpenSAFE.json
dags/resources/stages/parse/table_definitions/reflexer/GebSafeManager_event_ProtectSAFE.json
dags/resources/stages/parse/table_definitions/reflexer/GebSafeManager_event_QuitSystem.json
dags/resources/stages/parse/table_definitions/reflexer/GebSafeManager_event_TransferCollateral.json
dags/resources/stages/parse/table_definitions/reflexer/GebSafeManager_event_TransferInternalCoins.json
dags/resources/stages/parse/table_definitions/reflexer/LiquidationEngine_event_Liquidate.json
dags/resources/stages/parse/table_definitions/reflexer/RAI_call_burn.json
dags/resources/stages/parse/table_definitions/reflexer/RAI_call_mint.json
dags/resources/stages/parse/table_definitions/reflexer/RAI_event_Transfer.json
dags/resources/stages/parse/table_definitions/reflexer/SAFEEngine_event_ConfiscateSAFECollateralAndDebt.json
dags/resources/stages/parse/table_definitions/reflexer/SAFEEngine_event_CreateUnbackedDebt.json
dags/resources/stages/parse/table_definitions/reflexer/SAFEEngine_event_InitializeCollateralType.json
dags/resources/stages/parse/table_definitions/reflexer/SAFEEngine_event_ModifyCollateralBalance.json
dags/resources/stages/parse/table_definitions/reflexer/SAFEEngine_event_ModifySAFECollateralization.json
dags/resources/stages/parse/table_definitions/reflexer/SAFEEngine_event_SettleDebt.json
dags/resources/stages/parse/table_definitions/reflexer/SAFEEngine_event_TransferCollateral.json
dags/resources/stages/parse/table_definitions/reflexer/SAFEEngine_event_TransferInternalCoins.json
dags/resources/stages/parse/table_definitions/reflexer/SAFEEngine_event_TransferSAFECollateralAndDebt.json
dags/resources/stages/parse/table_definitions/reflexer/SAFEEngine_event_UpdateAccumulatedRate.json

Add support for Reflexer Finance
I used [abi-parser](https://contract-parser.d5.ai/) to build the table definitions
None

Add support for Reflexer

---

dags/resources/stages/parse/table_definitions/reflexer/DSProxy_event_LogSetOwner.json
dags/resources/stages/parse/table_definitions/yearn/V2AdditionalVaults_event_Transfer.json

Add events for Reflexer and Yearn
ie: I used [abi-parser](https://contract-parser.d5.ai/) to build the table definitions
This PR is dependent on #446 
Please Merge #446 before merging this PR. Thank you

Add events for Reflexer and Yearn

---

dags/resources/stages/parse/table_definitions/airswap/SwapV3_event_Swap.json
dags/resources/stages/parse/table_definitions/bancor/BancorNetwork_event_TokensTraded.json
dags/resources/stages/parse/table_definitions/clipper/ClipperExchangeInterface_event_Swapped.json
dags/resources/stages/parse/table_definitions/clipper/ClipperVerifiedCaravelExchange_event_Swapped.json
dags/resources/stages/parse/table_definitions/dodo/DSPFactory_event_NewDSP.json
dags/resources/stages/parse/table_definitions/dodo/DSP_event_DODOFlashLoan.json
dags/resources/stages/parse/table_definitions/dodo/DSP_event_DODOSwap.json
dags/resources/stages/parse/table_definitions/dodo/DVMFactory_event_NewDVM.json
dags/resources/stages/parse/table_definitions/dodo/DVM_event_DODOFlashLoan.json
dags/resources/stages/parse/table_definitions/dodo/DVM_event_DODOSwap.json
dags/resources/stages/parse/table_definitions/kyber/DMMFactory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/kyber/DMMPool_event_Swap.json
dags/resources/stages/parse/table_definitions/kyber/Factory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/kyber/KyberNetworkProxyV2_event_ExecuteTrade.json
dags/resources/stages/parse/table_definitions/kyber/Pool_event_Flash.json
dags/resources/stages/parse/table_definitions/kyber/Pool_event_Swap.json
dags/resources/stages/parse/table_definitions/maker/DssPsm_event_BuyGem.json
dags/resources/stages/parse/table_definitions/maker/DssPsm_event_SellGem.json
dags/resources/stages/parse/table_definitions/mstable/MassetProxy_event_Swapped.json
dags/resources/stages/parse/table_definitions/oneinch_lp/Mooniswap_event_Swapped.json
dags/resources/stages/parse/table_definitions/shibaswap/UniswapV2Factory_event_PairCreated.json
dags/resources/stages/parse/table_definitions/shibaswap/UniswapV2Pair_event_Swap.json
dags/resources/stages/parse/table_definitions/synthetix/Synthetix_event_SynthExchange.json
dags/resources/stages/parse/table_definitions/zeroex/Exchange_v4_0_event_LiquidityProviderSwap.json
dags/resources/stages/parse/table_definitions/zeroex/Exchange_v4_0_event_OtcOrderFilled.json

- Dodo V2
- Maker PSM
- Synthetix
- Shibaswap
- 1inch LP v2
- Kyber
- 0x v4
- Clipper
- Airswap v3
- MStable
- Bancor v3

Missing dexes

---

dags/resources/stages/parse/table_definitions/shibaswap/UniswapV2Factory_event_PairCreated.json

Fix unnamed field in UniswapV2Factory_event_PairCreated.json

Fix unnamed field in UniswapV2Factory_event_PairCreated.json

---

dags/ethereumetl_airflow/parse/parse_dataset_folder_logic.py

Fix null pointer

---

dags/resources/stages/parse/table_definitions/lido/WstETH_call_getStETHByWstETH.json
dags/resources/stages/parse/table_definitions/lido/WstETH_call_getWstETHByStETH.json
dags/resources/stages/parse/table_definitions/lido/WstETH_call_unwrap.json
dags/resources/stages/parse/table_definitions/lido/WstETH_call_wrap.json
dags/resources/stages/parse/table_definitions/lido/WstETH_event_Transfer.json
dags/resources/stages/parse/table_definitions/maker/mcd_call_exit.json
dags/resources/stages/parse/table_definitions/maker/mcd_call_join.json

Add events and calls for wrapped stETH --lido--
& add additional Maker MCDs to maker mcd calls
I used [abi-parser](https://contract-parser.d5.ai/) to build the table definitions
None

Add events and calls for wrapped stETH & Maker

---

dags/resources/stages/verify/sqls/logs_count.sql

Fix logs_count.sql

---

dags/resources/stages/parse/table_definitions/uniswap/NonfungiblePositionManager_call_Mint.json

ie: Add support for uniswap nonfungiblepositionmanager mint call
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/)

Uniswap nonfungiblepositionmanager mint call

---

dags/resources/stages/parse/table_definitions/convex/ConvexFraxPool_event_LockedAdditional.json
dags/resources/stages/parse/table_definitions/convex/ConvexFraxPool_event_LockedLonger.json
dags/resources/stages/parse/table_definitions/convex/ConvexFraxPool_event_RewardPaid.json
dags/resources/stages/parse/table_definitions/convex/ConvexFraxPool_event_StakeLocked.json
dags/resources/stages/parse/table_definitions/convex/ConvexFraxPool_event_WithdrawLocked.json

Add events for Convex-Frax booster pools
#478 is related (contains pools table) and must be merged first before this PR.

add events for Convex-Frax booster pools

---

README.md

Update docs on package dependencies
- Add section 'Updating package requirements'
- Include link to recent issue
https://github.com/blockchain-etl/ethereum-etl-airflow/issues/481
Closing https://github.com/blockchain-etl/ethereum-etl-airflow/pull/482 in favour of this one.
Thanks to @crash-absolutelabs

Update docs  on package dependencies

---

dags/resources/stages/parse/table_definitions/angle/Treasury_event_VaultManagerToggled.json
dags/resources/stages/parse/table_definitions/angle/VaultManager_call_angle.json
dags/resources/stages/parse/table_definitions/angle/VaultManager_event_AccruedToTreasury.json
dags/resources/stages/parse/table_definitions/angle/VaultManager_event_CollateralAmountUpdated.json
dags/resources/stages/parse/table_definitions/angle/VaultManager_event_DebtCeilingUpdated.json
dags/resources/stages/parse/table_definitions/angle/VaultManager_event_DebtTransferred.json
dags/resources/stages/parse/table_definitions/angle/VaultManager_event_InterestAccumulatorUpdated.json
dags/resources/stages/parse/table_definitions/angle/VaultManager_event_InternalDebtUpdated.json
dags/resources/stages/parse/table_definitions/angle/VaultManager_event_LiquidatedVaults.json
dags/resources/stages/parse/table_definitions/angle/VaultManager_event_LiquidationBoostParametersUpdated.json
dags/resources/stages/parse/table_definitions/angle/VaultManager_event_Transfer.json

Add Angle.money vaults events and calls
This PR is dependent on #485 - please merge #485 before merging this PR

Add angle collateral vaults events and calls

---

dags/resources/stages/parse/table_definitions/balancer/V2_Vault_event_AuthorizerChanged.json
dags/resources/stages/parse/table_definitions/balancer/V2_Vault_event_ExternalBalanceTransfer.json
dags/resources/stages/parse/table_definitions/balancer/V2_Vault_event_PausedStateChanged.json
dags/resources/stages/parse/table_definitions/balancer/V2_Vault_event_RelayerApprovalChanged.json
dags/resources/stages/parse/table_definitions/balancer/V2_Vault_event_TokensDeregistered.json
dags/resources/stages/parse/table_definitions/balancer/V2_Vault_event_TokensRegistered.json

Add missing [balancer v2 vault](https://etherscan.io/address/0xba12222222228d8ba445958a75a0704d566bf2c8) logs
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) or cli tools to build the table defenitions

add balancer v2 vault logs

---

dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePoolFactory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_InvestmentPoolFactory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_ProtocolFeesCollector_call_getFlashLoanFeePercentage.json
dags/resources/stages/parse/table_definitions/balancer/V2_ProtocolFeesCollector_call_getSwapFeePercentage.json
dags/resources/stages/parse/table_definitions/balancer/V2_ProtocolFeesCollector_call_setSwapFeePercentage.json
dags/resources/stages/parse/table_definitions/balancer/V2_ProtocolFeesCollector_event_SwapFeePercentageChanged.json
dags/resources/stages/parse/table_definitions/copper/CopperProxyV2_event_GradualWeightUpdateScheduled.json
dags/resources/stages/parse/table_definitions/copper/CopperProxyV2_event_JoinedPool.json
dags/resources/stages/parse/table_definitions/copper/CopperProxyV2_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/copper/CopperProxyV2_event_PoolCreated.json

ie: Add support for ComposableStableFactory, InvestmentPoolFactory and ProtocolFeesCollector for Balancer and CopperProxyV2 contract
There is another PR related to this (this one needs to be approved first)

add balancer factory contracts and copper proxy contract

---

dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePool_event_AmpUpdateStarted.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePool_event_AmpUpdateStopped.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePool_event_Approval.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePool_event_PausedStateChanged.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePool_event_ProtocolFeePercentageCacheUpdated.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePool_event_RecoveryModeStateChanged.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePool_event_SwapFeePercentageChanged.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePool_event_TokenRateCacheUpdated.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePool_event_TokenRateProviderSet.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePool_event_Transfer.json
dags/resources/stages/parse/table_definitions/balancer/V2_InvestmentPool_event_Approval.json
dags/resources/stages/parse/table_definitions/balancer/V2_InvestmentPool_event_GradualWeightUpdateScheduled.json
dags/resources/stages/parse/table_definitions/balancer/V2_InvestmentPool_event_ManagementFeePercentageChanged.json
dags/resources/stages/parse/table_definitions/balancer/V2_InvestmentPool_event_ManagementFeesCollected.json
dags/resources/stages/parse/table_definitions/balancer/V2_InvestmentPool_event_PausedStateChanged.json
dags/resources/stages/parse/table_definitions/balancer/V2_InvestmentPool_event_SwapEnabledSet.json
dags/resources/stages/parse/table_definitions/balancer/V2_InvestmentPool_event_SwapFeePercentageChanged.json
dags/resources/stages/parse/table_definitions/balancer/V2_InvestmentPool_event_Transfer.json

adding support for composablestable and investment pools on balancer
PR #490 needs to be approved first

adding support for composablestable and investment pools on balancer

---

pytest.ini
test_cases/schema/default_schema.json
tests/test_validate_json.py

Closes https://github.com/blockchain-etl/ethereum-etl-airflow/issues/458.

Test for empty input/column names

---

dags/resources/stages/parse/table_definitions/aura/BaseRewardPoolV2_event_RewardAdded.json
dags/resources/stages/parse/table_definitions/aura/BaseRewardPoolV2_event_RewardPaid.json
dags/resources/stages/parse/table_definitions/aura/BaseRewardPoolV2_event_Staked.json
dags/resources/stages/parse/table_definitions/aura/BaseRewardPoolV2_event_Transfer.json
dags/resources/stages/parse/table_definitions/aura/BaseRewardPoolV2_event_Withdrawn.json
dags/resources/stages/parse/table_definitions/aura/BoosterV2_event_Deposited.json
dags/resources/stages/parse/table_definitions/aura/BoosterV2_event_PoolAdded.json
dags/resources/stages/parse/table_definitions/aura/BoosterV2_event_Withdrawn.json
dags/resources/stages/parse/table_definitions/aura/PoolMigrator_call_migrate.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV1_event_Deposit.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV1_event_RewardAdded.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV1_event_RewardPaid.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV1_event_Staked.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV1_event_Transfer.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV1_event_Withdraw.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV1_event_Withdrawn.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV2_event_Deposit.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV2_event_RewardAdded.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV2_event_RewardPaid.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV2_event_Staked.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV2_event_Transfer.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV2_event_Withdraw.json
dags/resources/stages/parse/table_definitions/aura/RewardPoolV2_event_Withdrawn.json

Add support for aura v2 booster and reward pools
None

add aura v2 booster and reward pool events

---

dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_call_closePerpetual.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_call_forceClosePerpetuals.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_call_liquidatePerpetuals.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_call_openPerpetual.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_call_removeFromPerpetual.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_event_HAFeesUpdated.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_event_KeeperTransferred.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_event_PerpetualClosed.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_event_PerpetualUpdated.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_event_PerpetualsForceClosed.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_event_Recovered.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_event_RewardAdded.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_event_RewardPaid.json
dags/resources/stages/parse/table_definitions/angle/PerpetualManagerFront_event_Transfer.json
dags/resources/stages/parse/table_definitions/angle/StableMasterFront_call_withdraw.json

Add additional angle calls and change the contract source for perpetual events/calls

angle additional calls

---

dags/resources/stages/parse/table_definitions/abracadabra/BentoBoxMarkets_event_LogRepayForAll.json
dags/resources/stages/parse/table_definitions/abracadabra/DegenBoxMarkets_event_LogRepayForAll.json

Add abracadabra v4 cauldron repay events
None

add abracadabra v4 cauldron-specific events

---

dags/resources/stages/parse/table_definitions/abracadabra/BentoBoxMarkets_call_cook.json
dags/resources/stages/parse/table_definitions/abracadabra/BentoBoxMarkets_call_liquidate.json
dags/resources/stages/parse/table_definitions/abracadabra/BentoBoxMarkets_call_liquidateV3_4.json
dags/resources/stages/parse/table_definitions/abracadabra/DegenBoxMarkets_call_cook.json
dags/resources/stages/parse/table_definitions/abracadabra/DegenBoxMarkets_call_liquidate.json
dags/resources/stages/parse/table_definitions/abracadabra/DegenBoxMarkets_call_liquidateV3_4.json

Add Cauldron liquidate and cook functions
None

add cauldron liquidate and cook 

---

dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_BuyPriceAccepted.json
dags/resources/stages/parse/table_definitions/foundation/FNDNFTMarket_event_OfferAccepted.json

ie: Add support for foundation contract events 
ie: I used cli tools to build the table definitions
Used 0x5363827a66224541224decf96378fdd0f110ac46 to generate the ABI but passed in 0xcda72070e455bb31c7690a170224ce43623d0b6f as the contract address in the CLI bc its a proxy

add buy price accepted + offer accepted events for foundation

---

dags/resources/stages/parse/table_definitions/superrare/SuperRareBazaar_event_AcceptOffer.json
dags/resources/stages/parse/table_definitions/superrare/SuperRareBazaar_event_AuctionBid.json
dags/resources/stages/parse/table_definitions/superrare/SuperRareBazaar_event_AuctionSettled.json
dags/resources/stages/parse/table_definitions/superrare/SuperRareBazaar_event_CancelAuction.json
dags/resources/stages/parse/table_definitions/superrare/SuperRareBazaar_event_CancelOffer.json
dags/resources/stages/parse/table_definitions/superrare/SuperRareBazaar_event_NewAuction.json
dags/resources/stages/parse/table_definitions/superrare/SuperRareBazaar_event_OfferPlaced.json
dags/resources/stages/parse/table_definitions/superrare/SuperRareBazaar_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/superrare/SuperRareBazaar_event_SetSalePrice.json
dags/resources/stages/parse/table_definitions/superrare/SuperRareBazaar_event_Sold.json

ie: Add support for SuperRare Bazaar Events

ADDING BAZAAR EVENTS

---

dags/resources/stages/parse/table_definitions/seaport/SeaportV21_call_fulfillAdvancedOrder.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_call_fulfillAvailableAdvancedOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_call_fulfillAvailableOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_call_fulfillBasicOrder.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_call_fulfillBasicOrder_efficient_6GL6yc.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_call_fulfillOrder.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_call_getOrderHash.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_call_information.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_call_matchAdvancedOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_call_matchOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_call_validate.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_event_CounterIncremented.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_event_OrderCancelled.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_event_OrderFulfilled.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_event_OrderValidated.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV21_event_OrdersMatched.json

ie: Add support for seaport v2.1 contract events 

adding seaport v2.1 contract events and calls

---

dags/resources/stages/parse/table_definitions/seaport/SeaportV12_call_fulfillAdvancedOrder.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_call_fulfillAvailableAdvancedOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_call_fulfillAvailableOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_call_fulfillBasicOrder.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_call_fulfillBasicOrder_efficient_6GL6yc.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_call_fulfillOrder.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_call_getOrderHash.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_call_information.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_call_matchAdvancedOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_call_matchOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_call_validate.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_event_CounterIncremented.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_event_OrderCancelled.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_event_OrderFulfilled.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_event_OrderValidated.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV12_event_OrdersMatched.json

ie: Renamed new seaport contract decoding from 2.1 to 1.2

changed seaport 2.1 to 1.2

---

dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_cancel.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_fulfillAdvancedOrder.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_fulfillAvailableAdvancedOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_fulfillAvailableOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_fulfillBasicOrder.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_fulfillBasicOrder_efficient_6GL6yc.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_fulfillOrder.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_getContractOffererNonce.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_getCounter.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_getOrderHash.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_getOrderStatus.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_incrementCounter.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_information.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_matchAdvancedOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_matchOrders.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_name.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_call_validate.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_event_CounterIncremented.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_event_OrderCancelled.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_event_OrderFulfilled.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_event_OrderValidated.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV13_event_OrdersMatched.json

ie: Add support for Seaport 1.3 contract events 
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/) 
https://twitter.com/z0age/status/1626583847751266316?s=46&t=qDL9C8e1ebL4wr06y-XhtA

Add Seaport V1.3 files

---

dags/resources/stages/parse/table_definitions/seaport/SeaportV14_event_CounterIncremented.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV14_event_OrderCancelled.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV14_event_OrderFulfilled.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV14_event_OrderValidated.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV14_event_OrdersMatched.json

Add the new Seaport contract, currently at V1.4
I used cli tools to build the table defenitions

Add new Seaport contract V1.4

---

dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_AdminChanged.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_Approval.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_ApprovalForAll.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_BatchMetadataUpdate.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_BeaconUpgraded.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_FundsReceived.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_FundsRecipientChanged.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_FundsWithdrawn.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_MetadataUpdate.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_MintFeePayout.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_OpenMintFinalized.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_OwnerCanceled.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_OwnerPending.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_RoleAdminChanged.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_RoleGranted.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_RoleRevoked.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_Sale.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_SalesConfigChanged.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_Transfer.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_UpdatedMetadataRenderer.json
dags/resources/stages/parse/table_definitions/base/BaseIntroduced_event_Upgraded.json

Add support for Base, Introduced contract events 
ie: I used cli tools to build the table definitions
(Contract address is [0xd4307](https://etherscan.io/address/0xd4307e0acd12cf46fd6cf93bc264f5d5d1598792) but used [0x5eb5b](https://etherscan.io/address/0x5eb5babcefea846b220c82f222f00df95934f5f0) to generate the ABI (proxy implementation)

add events for Base, Introduced NFT

---

dags/resources/stages/parse/table_definitions/truefi/LoanFactory2_event_LoanTokenCreated.json
dags/resources/stages/parse/table_definitions/truefi/ManagedPortfolioFactory_event_AdminChanged.json
dags/resources/stages/parse/table_definitions/truefi/ManagedPortfolioFactory_event_BeaconUpgraded.json
dags/resources/stages/parse/table_definitions/truefi/ManagedPortfolioFactory_event_ManagementTransferred.json
dags/resources/stages/parse/table_definitions/truefi/ManagedPortfolioFactory_event_PortfolioCreated.json
dags/resources/stages/parse/table_definitions/truefi/ManagedPortfolioFactory_event_PortfolioImplementationChanged.json
dags/resources/stages/parse/table_definitions/truefi/ManagedPortfolioFactory_event_Upgraded.json
dags/resources/stages/parse/table_definitions/truefi/ManagedPortfolioFactory_event_WhitelistChanged.json
dags/resources/stages/parse/table_definitions/truefi/PoolFactory_event_AllowAllStatusChanged.json
dags/resources/stages/parse/table_definitions/truefi/PoolFactory_event_AllowedStatusChanged.json
dags/resources/stages/parse/table_definitions/truefi/PoolFactory_event_BorrowerWhitelistStatusChanged.json
dags/resources/stages/parse/table_definitions/truefi/PoolFactory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/truefi/PoolFactory_event_SafuChanged.json
dags/resources/stages/parse/table_definitions/truefi/PoolFactory_event_SingleBorrowerPoolCreated.json
dags/resources/stages/parse/table_definitions/truefi/PoolFactory_event_TrueLenderChanged.json

ie: Add support for truefi factory contracts 
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/)

add truefi poolfactory and managedportfoliofactory events

---

dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_CurrencySet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_Initialized.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_InsuranceFactorSet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_InterestRateModelSet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_KeeperSet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_ManagerInfoSet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_MaxInactivePeriodSet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_PeriodToStartAuctionSet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_PoolBeaconSet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_PoolClosed.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_PoolRewardPerSecondSet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_PoolTransferred.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_ProvisionalDefaultUtilizationSet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_ReserveFactorSet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_TreasurySet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_WarningGracePeriodSet.json
dags/resources/stages/parse/table_definitions/ribbon/PoolFactory_event_WarningUtilizationSet.json

ie: Add support for Ribbon Finance -  PoolFactory contract events 
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/)

Ribbon Finance -  PoolFactory contract events

---

dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_CurrencySet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_InsuranceFactorSet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_InterestRateModelSet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_ManagerInfoSet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_MaxInactivePeriodSet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_PeriodToStartAuctionSet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_PoolBeaconSet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_PoolClosed.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_PoolRewardPerSecondSet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_PoolTransferred.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_ProvisionalDefaultUtilizationSet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_ReserveFactorSet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_TreasurySet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_WarningGracePeriodSet.json
dags/resources/stages/parse/table_definitions/clearpool/PoolFactory_event_WarningUtilizationSet.json

ie: Add support for Clearpool poolFactory events
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/)

clearpool poolFactory contract events

---

dags/resources/stages/parse/table_definitions/multichain/AnyswapV6Router_event_LogAnySwapIn.json
dags/resources/stages/parse/table_definitions/multichain/AnyswapV6Router_event_LogAnySwapOut.json
dags/resources/stages/parse/table_definitions/multichain/AnyswapV6Router_event_LogAnySwapTradeTokensForNative.json
dags/resources/stages/parse/table_definitions/multichain/AnyswapV6Router_event_LogAnySwapTradeTokensForTokens.json

Add support for Multichain bridge contract events 

Added multichain events

---

dags/resources/stages/parse/table_definitions/balancer/V2_AaveLinearPoolFactoryV1_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_AaveLinearPoolFactoryV2_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_AaveLinearPoolFactoryV3_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_AaveLinearPoolFactoryV4_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePoolFactoryV1_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePoolFactoryV2_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePoolFactoryV3_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePoolFactoryV4_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_ERC4626LinearPoolFactory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_EulerLinearPoolFactory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_StablePoolFactoryV1_call_create.json
dags/resources/stages/parse/table_definitions/balancer/V2_StablePoolFactoryV1_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_StablePoolFactoryV2_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_WeightedPoolFactoryV1_call_create.json
dags/resources/stages/parse/table_definitions/balancer/V2_WeightedPoolFactoryV1_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_WeightedPoolFactoryV2_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_WeightedPoolFactoryV3_event_PoolCreated.json

Add support for PoolCreated contract events on several PoolFactory contracts, including older and newer versions of already decoded contracts

Added PoolCreated events for several PoolFactory contract versions

---

dags/resources/stages/parse/table_definitions/curve/CurvePool_event_NewFee.json
dags/resources/stages/parse/table_definitions/curve/CurvePool_event_NewParameters.json

Add Curve Pool events NewFee and NewParameters across all relevant pools 

add Curve events

---

dags/resources/stages/parse/table_definitions/dodo/DPPFactoryProxy_createDODOPrivatePool.json
dags/resources/stages/parse/table_definitions/dodo/DPSFactory_createDODOStablePool.json
dags/resources/stages/parse/table_definitions/dodo/DVMFactory_createDODOVendingMachine.json

Add support for pool creation function calls on DODO v2

Add DODO pool creation calls

---

dags/resources/stages/parse/table_definitions/balancer/V2_BalancerPool_event_PoolCreated.json

Add support for Balancer PoolCreated events
Used the Contract Parser: https://contract-parser.d5.ai/
Must be merged before PR #538

add Balancer pool events

---

dags/resources/stages/parse/table_definitions/compound/cToken_event_AccrueInterest.json
dags/resources/stages/parse/table_definitions/creamfinance/cToken_event_AccrueInterest.json
dags/resources/stages/parse/table_definitions/creamfinance/cToken_event_Transfer.json
dags/resources/stages/parse/table_definitions/dforce/iToken_event_AccrueInterest.json
dags/resources/stages/parse/table_definitions/dforce/iToken_event_Transfer.json
dags/resources/stages/parse/table_definitions/ironbank/cToken_event_AccrueInterest.json
dags/resources/stages/parse/table_definitions/ironbank/cToken_event_Flashloan.json
dags/resources/stages/parse/table_definitions/ironbank/cToken_event_Transfer.json
dags/resources/stages/parse/table_definitions/rari_capital/cToken_event_AccrueInterest.json
dags/resources/stages/parse/table_definitions/rari_capital/cToken_event_Transfer.json

Add additional events for Compound and Compound forks 

Compound & forks events

---

dags/resources/stages/parse/table_definitions/arbitrum/SequencerInbox_event_SequencerBatchDelivered.json
dags/resources/stages/parse/table_definitions/arbitrum/SequencerInbox_event_SequencerBatchDeliveredFromOrigin.json
dags/resources/stages/parse/table_definitions/aztec/RollupProcessorV2_event_RollupProcessed.json
dags/resources/stages/parse/table_definitions/aztec/RollupProcessor_event_RollupProcessed.json
dags/resources/stages/parse/table_definitions/boba/OVM_CanonicalTransactionChain_event_SequencerBatchAppended.json
dags/resources/stages/parse/table_definitions/boba/StateCommitmentChain_event_StateBatchAppended.json
dags/resources/stages/parse/table_definitions/dydx/GpsStatementVerifier_event_LogMemoryPagesHashes.json
dags/resources/stages/parse/table_definitions/loopring/ExchangeV3_event_BlockSubmitted.json
dags/resources/stages/parse/table_definitions/polygon/PolygonZkEVM_event_SequenceBatches.json
dags/resources/stages/parse/table_definitions/polygon/PolygonZkEVM_event_VerifyBatches.json
dags/resources/stages/parse/table_definitions/polygon/PolygonZkEVM_event_VerifyBatchesTrustedAggregator.json
dags/resources/stages/parse/table_definitions/zksync/ZKSyncEra_event_BlockCommit.json
dags/resources/stages/parse/table_definitions/zksync/ZKSyncEra_event_BlockExecution.json
dags/resources/stages/parse/table_definitions/zksync/ZKSyncEra_event_BlocksVerification.json
dags/resources/stages/parse/table_definitions/zksync/zkSyncLite_event_BlockCommit.json
dags/resources/stages/parse/table_definitions/zksync/zkSyncLite_event_BlockVerification.json

add events for L2 batches posting to mainnet
I used the contract parser at https://contract-parser.d5.ai
Requested to update a couple of Optimism tables to include all the versions of the relevant contracts

add events for L2 batches posting to mainnet

---

dags/resources/stages/parse/table_definitions/arbitrum/SequencerInbox_event_SequencerBatchDelivered.json
dags/resources/stages/parse/table_definitions/zksync/ZKSyncEra_event_BlocksVerification.json

fix a couple of mistakes in PR #549 
I used the contract parser at https://contract-parser.d5.ai/
PRs that are related to this or may need to be deployed before this PR #549

update events for L2 batches

---

dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_AffiliatePayment.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_CancelOwnershipTransfer.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_CurrencyStatusUpdated.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_InitiateOwnershipRenouncement.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_InitiateOwnershipTransfer.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_NewAffiliateController.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_NewAffiliateProgramStatus.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_NewAffiliateRate.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_NewBidAskNonces.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_NewCreatorFeeManager.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_NewDomainSeparator.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_NewGasLimitETHTransfer.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_NewMaxCreatorFeeBp.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_NewOwner.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_NewProtocolFeeRecipient.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_NewStrategy.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_OrderNoncesCancelled.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_StrategyUpdated.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_SubsetNoncesCancelled.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_TakerAsk.json
dags/resources/stages/parse/table_definitions/looksrare/LooksRareProtocolV2_event_TakerBid.json

ie: Add support for LooksRare v2 contract events 
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/) or to build the table defenitions
nope!! thank you!

add looksrare v2 events

---

dags/resources/stages/parse/table_definitions/seaport/SeaportV14_event_CounterIncremented.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV14_event_OrderCancelled.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV14_event_OrderFulfilled.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV14_event_OrderValidated.json
dags/resources/stages/parse/table_definitions/seaport/SeaportV14_event_OrdersMatched.json

ie: Add Seaport V1.5 contract address. The contract interface is the same as on V1.4 so just adding the address is sufficient.
ie: Just adding the address.

Add Seaport V1.5 address

---

dags/resources/stages/parse/table_definitions/circle/MessageTransmitter_event_AttesterDisabled.json
dags/resources/stages/parse/table_definitions/circle/MessageTransmitter_event_AttesterEnabled.json
dags/resources/stages/parse/table_definitions/circle/MessageTransmitter_event_AttesterManagerUpdated.json
dags/resources/stages/parse/table_definitions/circle/MessageTransmitter_event_MaxMessageBodySizeUpdated.json
dags/resources/stages/parse/table_definitions/circle/MessageTransmitter_event_MessageReceived.json
dags/resources/stages/parse/table_definitions/circle/MessageTransmitter_event_MessageSent.json
dags/resources/stages/parse/table_definitions/circle/MessageTransmitter_event_RescuerChanged.json
dags/resources/stages/parse/table_definitions/circle/MessageTransmitter_event_SignatureThresholdUpdated.json
dags/resources/stages/parse/table_definitions/circle/TokenMessenger_event_DepositForBurn.json
dags/resources/stages/parse/table_definitions/circle/TokenMessenger_event_LocalMinterAdded.json
dags/resources/stages/parse/table_definitions/circle/TokenMessenger_event_LocalMinterRemoved.json
dags/resources/stages/parse/table_definitions/circle/TokenMessenger_event_MintAndWithdraw.json
dags/resources/stages/parse/table_definitions/circle/TokenMessenger_event_RemoteTokenMessengerAdded.json
dags/resources/stages/parse/table_definitions/circle/TokenMessenger_event_RemoteTokenMessengerRemoved.json
dags/resources/stages/parse/table_definitions/circle/TokenMessenger_event_RescuerChanged.json

Add support for Circle's Cross-chain USDC Transfer contracts

Circle Cross-chain Transfer Protocol

---

dags/resources/stages/parse/table_definitions/blur/Blend_event_LoanOfferTaken.json
dags/resources/stages/parse/table_definitions/blur/Blend_event_Refinance.json
dags/resources/stages/parse/table_definitions/blur/Blend_event_Repay.json
dags/resources/stages/parse/table_definitions/blur/Blend_event_Seize.json
dags/resources/stages/parse/table_definitions/blur/Blend_event_StartAuction.json

add Blend events
I used https://contract-parser.d5.ai/ to build the table definitions

add Blur Lending events

---

dags/resources/stages/parse/table_definitions/blur/Blend_event_LoanOfferTaken.json
dags/resources/stages/parse/table_definitions/blur/Blend_event_Refinance.json
dags/resources/stages/parse/table_definitions/blur/Blend_event_Repay.json
dags/resources/stages/parse/table_definitions/blur/Blend_event_Seize.json
dags/resources/stages/parse/table_definitions/blur/Blend_event_StartAuction.json

update contract address for Blur Lending events (PR #554). i mistakenly put the proxy address initially

update contract address

---

dags/resources/stages/parse/table_definitions/blur/Blend_call_BuyLocked.json
dags/resources/stages/parse/table_definitions/blur/Blend_call_buyLockedETH.json
dags/resources/stages/parse/table_definitions/blur/Blend_call_buyToBorrow.json
dags/resources/stages/parse/table_definitions/blur/Blend_call_buyToBorrowETH.json
dags/resources/stages/parse/table_definitions/blur/Blend_call_buyToBorrowLocked.json
dags/resources/stages/parse/table_definitions/blur/Blend_call_buyToBorrowLockedETH.json
dags/resources/stages/parse/table_definitions/blur/Blend_call_takeBid.json

ie: Added Blur Blend call functions
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table defenitions

Added Blur Blend call functions

---

dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactoryV2_event_NewERC1155Pair.json
dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactoryV2_event_NewERC721Pair.json

add support for sudoswap v2 pool creation events 
used [abi-parser](https://contract-parser.d5.ai/)

add sudoswap v2 pair factory events

---

dags/resources/stages/parse/table_definitions/curve/WBETH_event_AddLiquidity.json
dags/resources/stages/parse/table_definitions/curve/WBETH_event_ApplyNewFee.json
dags/resources/stages/parse/table_definitions/curve/WBETH_event_Approval.json
dags/resources/stages/parse/table_definitions/curve/WBETH_event_CommitNewFee.json
dags/resources/stages/parse/table_definitions/curve/WBETH_event_RampA.json
dags/resources/stages/parse/table_definitions/curve/WBETH_event_RemoveLiquidity.json
dags/resources/stages/parse/table_definitions/curve/WBETH_event_RemoveLiquidityImbalance.json
dags/resources/stages/parse/table_definitions/curve/WBETH_event_RemoveLiquidityOne.json
dags/resources/stages/parse/table_definitions/curve/WBETH_event_StopRampA.json
dags/resources/stages/parse/table_definitions/curve/WBETH_event_TokenExchange.json
dags/resources/stages/parse/table_definitions/curve/WBETH_event_Transfer.json

add wbeth events

---

dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Factory_event_FeeAmountEnabled.json
dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Factory_event_OwnerChanged.json
dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Factory_event_PoolCreated.json

pancakeswap v3 on ethereum

---

dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Pool_event_Burn.json
dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Pool_event_Collect.json
dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Pool_event_CollectProtocol.json
dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Pool_event_Flash.json
dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Pool_event_IncreaseObservationCardinalityNext.json
dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Pool_event_Initialize.json
dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Pool_event_Mint.json
dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Pool_event_SetFeeProtocol.json
dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Pool_event_Swap.json

pancakeswap v3 pr2

---

dags/resources/stages/parse/table_definitions/pancakeswap/UniswapV3Pool_event_Swap.json

adding missing fields

---

dags/resources/stages/parse/table_definitions/bend/bend_LendPoolLoan_event_LoanCreated.json
dags/resources/stages/parse/table_definitions/bend/bend_LendPoolLoan_event_LoanLiquidated.json
dags/resources/stages/parse/table_definitions/bend/bend_LendPoolLoan_event_LoanRedeemed.json
dags/resources/stages/parse/table_definitions/bend/bend_LendPoolLoan_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/bend/bend_LendPool_event_Borrow.json
dags/resources/stages/parse/table_definitions/bend/bend_LendPool_event_Liquidate.json
dags/resources/stages/parse/table_definitions/bend/bend_LendPool_event_Redeem.json
dags/resources/stages/parse/table_definitions/bend/bend_LendPool_event_Repay.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_DirectLoanFixedCollectionOffer_event_LoanLiquidated.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_DirectLoanFixedCollectionOffer_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_DirectLoanFixedCollectionOffer_event_LoanStarted.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_DirectLoanFixedOfferRedeploy_event_LoanLiquidated.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_DirectLoanFixedOfferRedeploy_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_DirectLoanFixedOfferRedeploy_event_LoanStarted.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_DirectLoanFixedOffer_event_LoanLiquidated.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_DirectLoanFixedOffer_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_DirectLoanFixedOffer_event_LoanStarted.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_NFTfi_event_LoanLiquidated.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_NFTfi_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/nftfi/nftfi_NFTfi_event_LoanStarted.json
dags/resources/stages/parse/table_definitions/x2y2/x2y2_XY3_V2_event_LoanLiquidated.json
dags/resources/stages/parse/table_definitions/x2y2/x2y2_XY3_V2_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/x2y2/x2y2_XY3_V2_event_LoanStarted.json
dags/resources/stages/parse/table_definitions/x2y2/x2y2_XY3_V3_event_LoanLiquidated.json
dags/resources/stages/parse/table_definitions/x2y2/x2y2_XY3_V3_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/x2y2/x2y2_XY3_V3_event_LoanStarted.json
dags/resources/stages/parse/table_definitions/x2y2/x2y2_XY3_event_LoanLiquidated.json
dags/resources/stages/parse/table_definitions/x2y2/x2y2_XY3_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/x2y2/x2y2_XY3_event_LoanStarted.json

Add support for nft lending marketplaces (bend, nftfi, x2y2)
I used [nansen abi parser](https://nansen-contract-parser-prod.web.app/)

add events for nft lending marketplaces (bend, nftfi, x2y2)

---

dags/resources/stages/parse/table_definitions/aave/StableDebtToken_v2_event_Approval.json
dags/resources/stages/parse/table_definitions/aave/StableDebtToken_v2_event_BorrowAllowanceDelegated.json
dags/resources/stages/parse/table_definitions/aave/StableDebtToken_v2_event_Burn.json
dags/resources/stages/parse/table_definitions/aave/StableDebtToken_v2_event_Mint.json
dags/resources/stages/parse/table_definitions/aave/StableDebtToken_v2_event_Transfer.json
dags/resources/stages/parse/table_definitions/aave/VariableDebtToken_v2_event_Approval.json
dags/resources/stages/parse/table_definitions/aave/VariableDebtToken_v2_event_BorrowAllowanceDelegated.json
dags/resources/stages/parse/table_definitions/aave/VariableDebtToken_v2_event_Burn.json
dags/resources/stages/parse/table_definitions/aave/VariableDebtToken_v2_event_Mint.json
dags/resources/stages/parse/table_definitions/aave/VariableDebtToken_v2_event_Transfer.json

Use refs for Aave v2 debt tokens

---

dags/resources/stages/parse/table_definitions/starknet/GpsStatementVerifier_call_verifyProofAndRegister.json
dags/resources/stages/parse/table_definitions/starknet/StarknetCore_event_LogStateUpdate.json
dags/resources/stages/parse/table_definitions/starknet/Starknet_event_LogStateUpdate.json

Add support for starknet state update and proof verification on mainnet

add support for starknet state update and proof verification on mainnet

---

dags/resources/stages/parse/table_definitions/bend/bend_LendPool_event_Borrow.json
dags/resources/stages/parse/table_definitions/bend/bend_LendPool_event_Liquidate.json
dags/resources/stages/parse/table_definitions/bend/bend_LendPool_event_Redeem.json
dags/resources/stages/parse/table_definitions/bend/bend_LendPool_event_Repay.json

fix bend lendpool contract address

fix bend lendpool contract

---

dags/resources/stages/parse/table_definitions/bend/bend_InterestRate_call_calculateInterestRates.json

Add support for bend InterestRate contract which outputs outstanding debt

add bend debt function call

---

dags/resources/stages/parse/table_definitions/bend/InterestRate_call_calculateInterestRates.json
dags/resources/stages/parse/table_definitions/bend/LendPoolLoan_event_LoanCreated.json
dags/resources/stages/parse/table_definitions/bend/LendPoolLoan_event_LoanLiquidated.json
dags/resources/stages/parse/table_definitions/bend/LendPoolLoan_event_LoanRedeemed.json
dags/resources/stages/parse/table_definitions/bend/LendPoolLoan_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/bend/LendPool_event_Borrow.json
dags/resources/stages/parse/table_definitions/bend/LendPool_event_Liquidate.json
dags/resources/stages/parse/table_definitions/bend/LendPool_event_Redeem.json
dags/resources/stages/parse/table_definitions/bend/LendPool_event_Repay.json

add alternate contract addresses for Bend InterestRate contract. Fix naming of bend tables (remove bend_ prefix)

add alternate contract addresses for InterestRate contract

---

dags/ethereumetl_airflow/build_load_dag.py
dags/resources/stages/load_metadata/schemas/load_metadata.json
dags/resources/stages/load_metadata/sqls/load_metadata.sql

Add the `load_metadata` table with information of when load jobs complete

Add load_metadata tasks

---

dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_LoanClaimed.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_LoanCreated.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_LoanRepaid.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_LoanRolledOver.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_LoanStarted.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_getFullInterestAmount.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_getLoan.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_pause.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_repay.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_repayPart.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_rollover.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_startLoan.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_LoanClaimed.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_LoanCreated.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_LoanRolledOver.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_LoanStarted.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_Unpaused.json
dags/resources/stages/parse/table_definitions/arcade/LoanCore_call_claim.json
dags/resources/stages/parse/table_definitions/arcade/LoanCore_call_createLoan.json
dags/resources/stages/parse/table_definitions/arcade/LoanCore_call_getLoan.json
dags/resources/stages/parse/table_definitions/arcade/LoanCore_call_repay.json
dags/resources/stages/parse/table_definitions/arcade/LoanCore_call_startLoan.json
dags/resources/stages/parse/table_definitions/arcade/LoanCore_event_LoanClaimed.json
dags/resources/stages/parse/table_definitions/arcade/LoanCore_event_LoanCreated.json
dags/resources/stages/parse/table_definitions/arcade/LoanCore_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/arcade/LoanCore_event_LoanStarted.json

Add support for arcade nft lending
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table defenitions

add support for arcade nft lending

---

dags/resources/stages/parse/table_definitions/curve/LDOETH_event_AddLiquidity.json
dags/resources/stages/parse/table_definitions/curve/LDOETH_event_ClaimAdminFee.json
dags/resources/stages/parse/table_definitions/curve/LDOETH_event_CommitNewParameters.json
dags/resources/stages/parse/table_definitions/curve/LDOETH_event_NewParameters.json
dags/resources/stages/parse/table_definitions/curve/LDOETH_event_RampAgamma.json
dags/resources/stages/parse/table_definitions/curve/LDOETH_event_RemoveLiquidity.json
dags/resources/stages/parse/table_definitions/curve/LDOETH_event_RemoveLiquidityOne.json
dags/resources/stages/parse/table_definitions/curve/LDOETH_event_StopRampA.json
dags/resources/stages/parse/table_definitions/curve/LDOETH_event_TokenExchange.json
dags/resources/stages/parse/table_definitions/curve/stETHng_event_AddLiquidity.json
dags/resources/stages/parse/table_definitions/curve/stETHng_event_ApplyNewFee.json
dags/resources/stages/parse/table_definitions/curve/stETHng_event_Approval.json
dags/resources/stages/parse/table_definitions/curve/stETHng_event_CommitNewFee.json
dags/resources/stages/parse/table_definitions/curve/stETHng_event_RampA.json
dags/resources/stages/parse/table_definitions/curve/stETHng_event_RemoveLiquidity.json
dags/resources/stages/parse/table_definitions/curve/stETHng_event_RemoveLiquidityImbalance.json
dags/resources/stages/parse/table_definitions/curve/stETHng_event_RemoveLiquidityOne.json
dags/resources/stages/parse/table_definitions/curve/stETHng_event_StopRampA.json
dags/resources/stages/parse/table_definitions/curve/stETHng_event_TokenExchange.json
dags/resources/stages/parse/table_definitions/curve/stETHng_event_Transfer.json

Added contract events for the stETH-ng and LDO/ETH Curve pools
I used the abi parser to build the table definitions
n/a

Events for stETH-ng and LDO/ETH on Curve

---

dags/resources/stages/parse/table_definitions/raft/RaftMarket_event_CollateralChanged.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_event_CollateralTokenAdded.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_event_CollateralTokenModified.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_event_Liquidation.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_event_PositionClosed.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_event_PositionCreated.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_event_Redemption.json

Add support for stETH contract events 
Used CLI tools to build the table definitions

ECSOL-267 RAFT Dashboard

---

dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_LoanClaimed.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_LoanCreated.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_LoanRepaid.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_LoanRolledOver.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_LoanStarted.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_getFullInterestAmount.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_getLoan.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_pause.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_repay.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_repayPart.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_rollover.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_call_startLoan.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_LoanClaimed.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_LoanCreated.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_LoanRepaid.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_LoanRolledOver.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_LoanStarted.json
dags/resources/stages/parse/table_definitions/arcade/LoanCoreV2_event_Unpaused.json

Change Arcade LoanCore V2 CA to correct address

fix arcade v2 CA

---

dags/ethereumetl_airflow/build_parse_dag.py
dags/ethereumetl_airflow/common.py
dags/ethereumetl_airflow/parse/parse_dataset_folder_logic.py

We need the ability to reference views in table definitions, see this PRhttps://github.com/blockchain-etl/ethereum-etl-airflow/pull/588 as an example. 
Move view creating inside the parsing so it's included in the topological sorting and validation based on refs

Allow refs to views

---

dags/resources/stages/parse/table_definitions/arcade/AssetWrapper_event_Approval.json
dags/resources/stages/parse/table_definitions/arcade/AssetWrapper_event_DepositERC1155.json
dags/resources/stages/parse/table_definitions/arcade/AssetWrapper_event_DepositERC20.json
dags/resources/stages/parse/table_definitions/arcade/AssetWrapper_event_DepositERC721.json
dags/resources/stages/parse/table_definitions/arcade/AssetWrapper_event_DepositETH.json
dags/resources/stages/parse/table_definitions/arcade/AssetWrapper_event_Transfer.json
dags/resources/stages/parse/table_definitions/arcade/AssetWrapper_event_Withdraw.json

add support for arcade asset wrapper

add support for arcade asset wrapper

---

dags/resources/stages/parse/table_definitions/raft/RaftMarket_WrETH_event_WrappedCollateralTokenPositionChanged.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_WstETH_event_ETHPositionChanged.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_WstETH_event_StETHPositionChanged.json

Added Raft asset position events
[Adding on to the events from this PR](https://github.com/blockchain-etl/ethereum-etl-airflow/pull/586)

ECSOL-267 Raft Events (Manage Positions)

---

dags/resources/stages/parse/table_definitions/raft/RaftMarket_r_event_OwnershipTransferStarted.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_r_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_r_event_RDeployed.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_r_event_Transfer.json

Adding additional events for R token to capture protocol fees, minting and overall supply
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) or cli tools to build the table defenitions
[Following up from this PR](https://github.com/blockchain-etl/ethereum-etl-airflow/pull/600)

ECSOL-267 Raft Events (R Token Events)

---

dags/ethereumetl_airflow/parse/parse_dataset_folder_logic.py
dags/ethereumetl_airflow/parse/parse_state_manager.py

Add _last_ds and _version to parse state
They will be used in CI/CD for deploying table definitions

Add _last_ds and _version to parse state

---

dags/resources/stages/parse/table_definitions/raft/RaftMarket_OneStopLeverage_event_LeveragedPositionAdjusted.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_OneStopLeverage_event_StETHLeveragedPositionChange.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_event_DebtChanged.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_event_DelegateWhitelisted.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_event_RBorrowingFeePaid.json
dags/resources/stages/parse/table_definitions/raft/RaftMarket_event_SplitLiquidationCollateralChanged.json

Adding OneStopLiquidation contract and WhitelistedDelegate event for main contract
Previous [PR](https://github.com/blockchain-etl/ethereum-etl-airflow/pull/601)

Adding raft events

---

dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_AmountUsedInPeriodReset.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_BlockFinalized.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_BlocksVerificationDone.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_Initialized.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_L1L2MessagesReceivedOnL2.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_L2L1MessageHashAddedToInbox.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_LimitAmountChanged.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_MessageClaimed.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_MessageSent.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_Paused.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_RoleAdminChanged.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_RoleGranted.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_RoleRevoked.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_UnPaused.json
dags/resources/stages/parse/table_definitions/linea/ZkEvmV2_event_VerifierAddressChanged.json

Add linea dataset
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) or cli tools to build the table defenitions

Add linea dataset

---

dags/ethereumetl_airflow/parse/parse_dataset_folder_logic.py
dags/ethereumetl_airflow/parse/parse_state_manager.py

Use fallback dataset to determine last_ds when deploying table definitions
There is on other way to determine last_ds for new datasets

Use fallback dataset to determine last_ds when deploying table defs

---

dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_AddressFrozen.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_AddressUnfrozen.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_Approval.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_AssetProtectionRoleSet.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_BetaDelegateUnwhitelisted.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_BetaDelegateWhitelisted.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_BetaDelegateWhitelisterSet.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_BetaDelegatedTransfer.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_FrozenAddressWiped.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_OwnershipTransferDisregarded.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_OwnershipTransferProposed.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_Pause.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_SupplyControllerSet.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_SupplyDecreased.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_SupplyIncreased.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_Transfer.json
dags/resources/stages/parse/table_definitions/paypal/PYUSDImplementation_event_Unpause.json

Added PYUSD events

---

dags/resources/stages/parse/table_definitions/chainlink/view_AccessControlledOffchainAggregator_info.sql

Reverts blockchain-etl/ethereum-etl-airflow#613

Revert "Deprecate inj usd chainlink feed"

---

dags/resources/stages/parse/table_definitions/chainlink/view_AccessControlledOffchainAggregator_info.sql

Fix PR613.

---

dags/resources/stages/parse/table_definitions/apestake/ApeCoinStaking_event_ClaimRewards.json
dags/resources/stages/parse/table_definitions/apestake/ApeCoinStaking_event_ClaimRewardsNft.json
dags/resources/stages/parse/table_definitions/apestake/ApeCoinStaking_event_ClaimRewardsPairNft.json
dags/resources/stages/parse/table_definitions/apestake/ApeCoinStaking_event_Deposit.json
dags/resources/stages/parse/table_definitions/apestake/ApeCoinStaking_event_DepositNft.json
dags/resources/stages/parse/table_definitions/apestake/ApeCoinStaking_event_DepositPairNft.json
dags/resources/stages/parse/table_definitions/apestake/ApeCoinStaking_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/apestake/ApeCoinStaking_event_UpdatePool.json
dags/resources/stages/parse/table_definitions/apestake/ApeCoinStaking_event_Withdraw.json
dags/resources/stages/parse/table_definitions/apestake/ApeCoinStaking_event_WithdrawNft.json
dags/resources/stages/parse/table_definitions/apestake/ApeCoinStaking_event_WithdrawPairNft.json

Upload 11 apestakeio events files for apestaking
ie: Add apestake.io event files
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to download the event files

Upload apestakeio events files for apestaking

---

dags/resources/stages/parse/table_definitions/aave/GhoVariableDebtToken_event_ATokenSet.json
dags/resources/stages/parse/table_definitions/aave/GhoVariableDebtToken_event_Approval.json
dags/resources/stages/parse/table_definitions/aave/GhoVariableDebtToken_event_BorrowAllowanceDelegated.json
dags/resources/stages/parse/table_definitions/aave/GhoVariableDebtToken_event_Burn.json
dags/resources/stages/parse/table_definitions/aave/GhoVariableDebtToken_event_DiscountPercentUpdated.json
dags/resources/stages/parse/table_definitions/aave/GhoVariableDebtToken_event_DiscountRateStrategyUpdated.json
dags/resources/stages/parse/table_definitions/aave/GhoVariableDebtToken_event_DiscountTokenUpdated.json
dags/resources/stages/parse/table_definitions/aave/GhoVariableDebtToken_event_Initialized.json
dags/resources/stages/parse/table_definitions/aave/GhoVariableDebtToken_event_Mint.json
dags/resources/stages/parse/table_definitions/aave/GhoVariableDebtToken_event_Transfer.json

Add support for GHO variable token contract events 

[Gauntlet] Add GHO variable debt token events

---

dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_AddAsset.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_CometDeployed.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_GovernorTransferred.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBaseBorrowMin.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBaseMinForRewards.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBaseTokenPriceFeed.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBaseTrackingBorrowSpeed.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBaseTrackingSupplySpeed.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBorrowKink.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBorrowPerYearInterestRateBase.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBorrowPerYearInterestRateSlopeHigh.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBorrowPerYearInterestRateSlopeLow.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetConfiguration.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetExtensionDelegate.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetFactory.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetGovernor.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetPauseGuardian.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetStoreFrontPriceFactor.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetSupplyKink.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetSupplyPerYearInterestRateBase.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetSupplyPerYearInterestRateSlopeHigh.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetSupplyPerYearInterestRateSlopeLow.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetTargetReserves.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAsset.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAssetBorrowCollateralFactor.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAssetLiquidateCollateralFactor.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAssetLiquidationFactor.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAssetPriceFeed.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAssetSupplyCap.json

Compound use impl address instead of proxy

---

dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_AddAsset.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_CometDeployed.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_GovernorTransferred.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBaseBorrowMin.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBaseMinForRewards.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBaseTokenPriceFeed.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBaseTrackingBorrowSpeed.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBaseTrackingSupplySpeed.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBorrowKink.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBorrowPerYearInterestRateBase.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBorrowPerYearInterestRateSlopeHigh.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetBorrowPerYearInterestRateSlopeLow.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetConfiguration.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetExtensionDelegate.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetFactory.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetGovernor.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetPauseGuardian.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetStoreFrontPriceFactor.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetSupplyKink.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetSupplyPerYearInterestRateBase.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetSupplyPerYearInterestRateSlopeHigh.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetSupplyPerYearInterestRateSlopeLow.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_SetTargetReserves.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAsset.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAssetBorrowCollateralFactor.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAssetLiquidateCollateralFactor.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAssetLiquidationFactor.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAssetPriceFeed.json
dags/resources/stages/parse/table_definitions/compound/Configurator_v3_event_UpdateAssetSupplyCap.json

This reverts commit f99e58cb56b7c0d684961db342fc39cb07a68cb5.
The implementation contract doesn't emit any events https://etherscan.io/address/0x316f9708bb98af7da9c68c1c3b5e79039cd336e3#events

Revert "use impl address instead of proxy (#626)"

---

dags/resources/stages/parse/table_definitions/ens/ETHRegistrarController4_event_NameRegistered.json
dags/resources/stages/parse/table_definitions/ens/ETHRegistrarController4_event_NameRenewed.json
dags/resources/stages/parse/table_definitions/ens/ETHRegistrarController4_event_OwnershipTransferred.json

Add support for ENS Registrar Controller 4 events
Used contract parser to get the events

ECSOL-34: Add ETHRegistrarController4 events

---

dags/resources/stages/parse/table_definitions/optimism/L2OutputOracle_event_OutputProposed.json

add support for Optimism Sequencer Batches post-Bedrock

Optimism sequencer batches

---

dags/resources/stages/parse/table_definitions/uniswap/ExclusiveDutchOrderReactor_event_Fill.json

Added support for Uniswap X fill events

Fill event for Uniswap X

---

dags/resources/stages/parse/table_definitions/abracadabra/Spell_call_mint.json
dags/resources/stages/parse/table_definitions/abracadabra/Spell_call_transfer.json
dags/resources/stages/parse/table_definitions/abracadabra/Spell_call_transferFrom.json
dags/resources/stages/parse/table_definitions/abracadabra/Spell_event_Approval.json
dags/resources/stages/parse/table_definitions/abracadabra/Spell_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/abracadabra/Spell_event_Transfer.json
dags/resources/stages/parse/table_definitions/abracadabra/mSpellStaking_call_deposit.json
dags/resources/stages/parse/table_definitions/abracadabra/mSpellStaking_call_withdraw.json
dags/resources/stages/parse/table_definitions/abracadabra/mSpellStaking_event_ClaimReward.json
dags/resources/stages/parse/table_definitions/abracadabra/mSpellStaking_event_Deposit.json
dags/resources/stages/parse/table_definitions/abracadabra/mSpellStaking_event_EmergencyWithdraw.json
dags/resources/stages/parse/table_definitions/abracadabra/mSpellStaking_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/abracadabra/mSpellStaking_event_Withdraw.json
dags/resources/stages/parse/table_definitions/abracadabra/sSpellV1_call_burn.json
dags/resources/stages/parse/table_definitions/abracadabra/sSpellV1_call_burnFrom.json
dags/resources/stages/parse/table_definitions/abracadabra/sSpellV1_call_mint.json
dags/resources/stages/parse/table_definitions/abracadabra/sSpellV1_call_transfer.json
dags/resources/stages/parse/table_definitions/abracadabra/sSpellV1_call_transferFrom.json
dags/resources/stages/parse/table_definitions/abracadabra/sSpellV1_event_Approval.json
dags/resources/stages/parse/table_definitions/abracadabra/sSpellV1_event_Transfer.json

Add support for Abracadabra tokens (Spell, sSpell, and Spell staking contract)
None

Abracadabra tokens and staking 

---

dags/resources/stages/parse/table_definitions/compound/cFEI_event_AccrueInterest.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_Approval.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_Borrow.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_Failure.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_LiquidateBorrow.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_Mint.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_NewAdmin.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_NewComptroller.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_NewImplementation.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_NewMarketInterestRateModel.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_NewPendingAdmin.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_NewReserveFactor.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_Redeem.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_RepayBorrow.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_ReservesAdded.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_ReservesReduced.json
dags/resources/stages/parse/table_definitions/compound/cFEI_event_Transfer.json

add cFEI to ethereum compound

---

dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_AddCollateral.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_AddQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_ApproveLPTransferors.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_AuctionNFTSettle.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_AuctionSettle.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_BondWithdrawn.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_BucketBankruptcy.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_BucketTake.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_BucketTakeLPAwarded.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_DecreaseLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_DrawDebt.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_Flashloan.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_IncreaseLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_Kick.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_KickReserveAuction.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_LoanStamped.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_MoveQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_RemoveCollateral.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_RemoveQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_RepayDebt.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_ReserveAuction.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_ResetInterestRate.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_RevokeLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_RevokeLPTransferors.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_Settle.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_Take.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_TransferLP.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_UpdateInterestRate.json

Fix the column name of the dynamic contract address for ERC20 pool addresses

Fix: Change pool column name for erc20 pool addresses for Ajna

---

dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1CustomGateway_event_DepositInitiated.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1CustomGateway_event_TokenSet.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1CustomGateway_event_TxToL2.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1CustomGateway_event_WithdrawRedirected.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1CustomGateway_event_WithdrawalFinalized.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1ERC20Gateway_event_DepositInitiated.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1ERC20Gateway_event_TxToL2.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1ERC20Gateway_event_WithdrawRedirected.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1ERC20Gateway_event_WithdrawalFinalized.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1GatewayRouter_event_DefaultGatewayUpdated.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1GatewayRouter_event_GatewaySet.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1GatewayRouter_event_TransferRouted.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1GatewayRouter_event_TxToL2.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1GatewayRouter_event_WhitelistSourceUpdated.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1WethGateway_event_DepositInitiated.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1WethGateway_event_TxToL2.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1WethGateway_event_WithdrawRedirected.json
dags/resources/stages/parse/table_definitions/arbitrum_bridge/L1WethGateway_event_WithdrawalFinalized.json

Add support for arbitrum bridge contract events 
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/) and [these](https://docs.arbitrum.io/for-devs/useful-addresses#core-contracts-1) contract addresses

added arbitrum bridge parsed events

---

dags/resources/stages/parse/table_definitions/sdai/SavingsDai_event_Deposit.json
dags/resources/stages/parse/table_definitions/sdai/SavingsDai_event_Withdraw.json

Add Deposit and Withdrawal events for sDai.

Added sDai events

---

dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ActivatedOperator.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ChangedAdmin.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ChangedDepositsStopped.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ChangedGlobalFee.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ChangedOperatorAddresses.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ChangedOperatorFee.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ChangedOperatorLimit.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ChangedTreasury.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ChangedWithdrawer.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_DeactivatedOperator.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_Deposit.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ExitRequest.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_NewOperator.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_SetWithdrawerCustomizationStatus.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ValidatorKeyRemoved.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ValidatorKeysAdded.json
dags/resources/stages/parse/table_definitions/consensys/StakingContract_event_ValidatorsEdited.json

- Added support for Consensys staking contract events
- I used [abi-parser](https://nansen-contract-parser-prod.web.app/)
- N/A
- N/A

feat: add Consensys staking contract events

---

dags/resources/stages/parse/table_definitions/wormhole/BridgeImplementation_event_AdminChanged.json
dags/resources/stages/parse/table_definitions/wormhole/BridgeImplementation_event_BeaconUpgraded.json
dags/resources/stages/parse/table_definitions/wormhole/BridgeImplementation_event_ContractUpgraded.json
dags/resources/stages/parse/table_definitions/wormhole/BridgeImplementation_event_TransferRedeemed.json
dags/resources/stages/parse/table_definitions/wormhole/BridgeImplementation_event_Upgraded.json
dags/resources/stages/parse/table_definitions/wormhole/Implementation_event_AdminChanged.json
dags/resources/stages/parse/table_definitions/wormhole/Implementation_event_BeaconUpgraded.json
dags/resources/stages/parse/table_definitions/wormhole/Implementation_event_ContractUpgraded.json
dags/resources/stages/parse/table_definitions/wormhole/Implementation_event_GuardianSetAdded.json
dags/resources/stages/parse/table_definitions/wormhole/Implementation_event_LogMessagePublished.json
dags/resources/stages/parse/table_definitions/wormhole/Implementation_event_Upgraded.json

Add support for wormhole contract events 

[Gauntlet] Wormhole core and token bridge contracts

---

dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_AddBank.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_Borrow.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_Execute.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_Initialized.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_Lend.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_Liquidate.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_ModifyBank.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_OwnershipTransferStarted.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_PutCollateral.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_Repay.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_SetOracle.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_SetWhitelistERC1155.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_SetWhitelistToken.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_TakeCollateral.json
dags/resources/stages/parse/table_definitions/blueberry/BlueberryBank_event_WithdrawLend.json
dags/resources/stages/parse/table_definitions/blueberry/HardVault_event_ApprovalForAll.json
dags/resources/stages/parse/table_definitions/blueberry/HardVault_event_Deposited.json
dags/resources/stages/parse/table_definitions/blueberry/HardVault_event_Initialized.json
dags/resources/stages/parse/table_definitions/blueberry/HardVault_event_OwnershipTransferStarted.json
dags/resources/stages/parse/table_definitions/blueberry/HardVault_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/blueberry/HardVault_event_TransferBatch.json
dags/resources/stages/parse/table_definitions/blueberry/HardVault_event_TransferSingle.json
dags/resources/stages/parse/table_definitions/blueberry/HardVault_event_URI.json
dags/resources/stages/parse/table_definitions/blueberry/HardVault_event_Withdrawn.json

Add support for Blueberry contract events (Blueberry Bank and Hard Vault)

[Gauntlet] Blueberry ingestion: Blueberry Bank and Hard Vault

---

dags/resources/stages/parse/table_definitions/etherfi/LiquidityPool_event_Deposit.json
dags/resources/stages/parse/table_definitions/etherfi/LiquidityPool_event_Withdraw.json

Add support for etherfi deposits and withdrawals

add Etherfi deposits and withdrawals

---

dags/resources/stages/parse/table_definitions/swell/RswETH_event_AddedToWhitelist.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_Approval.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_ETHDepositReceived.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_ETHWithdrawn.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_Initialized.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_MaximumRepriceDifferencePercentageUpdated.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_MaximumRepricerswETHDifferencePercentageUpdated.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_MinimumRepriceTimeUpdated.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_NodeOperatorRewardPercentageUpdate.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_RemovedFromWhitelist.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_Reprice.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_SwellTreasuryRewardPercentageUpdate.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_Transfer.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_WhitelistDisabled.json
dags/resources/stages/parse/table_definitions/swell/RswETH_event_WhitelistEnabled.json

ie: Add support for swell rswETH contract events 

add swell rswETH events

---

dags/resources/stages/parse/table_definitions/puffer/PufferVault_event_Approval.json
dags/resources/stages/parse/table_definitions/puffer/PufferVault_event_AuthorityUpdated.json
dags/resources/stages/parse/table_definitions/puffer/PufferVault_event_ClaimedWithdrawals.json
dags/resources/stages/parse/table_definitions/puffer/PufferVault_event_Deposit.json
dags/resources/stages/parse/table_definitions/puffer/PufferVault_event_EIP712DomainChanged.json
dags/resources/stages/parse/table_definitions/puffer/PufferVault_event_Initialized.json
dags/resources/stages/parse/table_definitions/puffer/PufferVault_event_RequestedWithdrawals.json
dags/resources/stages/parse/table_definitions/puffer/PufferVault_event_Transfer.json
dags/resources/stages/parse/table_definitions/puffer/PufferVault_event_Upgraded.json
dags/resources/stages/parse/table_definitions/puffer/PufferVault_event_Withdraw.json

Add support for puffer pufETH contract events 

add puffer pufETH events

---

dags/resources/stages/parse/table_definitions/kelpdao/LRTDepositPool_event_AssetDeposit.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTDepositPool_event_ETHDeposit.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTDepositPool_event_ETHSwappedForLST.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTDepositPool_event_Initialized.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTDepositPool_event_MaxNodeDelegatorLimitUpdated.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTDepositPool_event_MinAmountToDepositUpdated.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTDepositPool_event_NodeDelegatorAddedinQueue.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTDepositPool_event_NodeDelegatorRemovedFromQueue.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTDepositPool_event_Paused.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTDepositPool_event_Unpaused.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTDepositPool_event_UpdatedLRTConfig.json

Add support for kelp dao contract events 

add kelp dao events

---

dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStaking_event_AssetDeposit.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStaking_event_Initialized.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStaking_event_MaxNodeDelegatorLimitUpdated.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStaking_event_MinAmountToDepositUpdated.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStaking_event_NodeDelegatorAddedinQueue.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStaking_event_Paused.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStaking_event_PreDepositHelperChanged.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStaking_event_PreDepositStatusChanged.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStaking_event_Unpaused.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStaking_event_UpdatedEigenpieConfig.json

ie: Add support for eigenpie contract events 

add eigenpie events

---

dags/resources/stages/parse/table_definitions/morpho/Morpho_event_Initialized.json
dags/resources/stages/parse/table_definitions/morpho/Morpho_event_OwnershipTransferStarted.json
dags/resources/stages/parse/table_definitions/morpho/Morpho_event_OwnershipTransferred.json

[Gauntlet] Add morpho contract

---

dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_AddedNewSupportedAsset.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_AssetBoostUpdate.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_AssetDepositLimitUpdate.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_AssetStrategyUpdate.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_Initialized.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_ReceiptTokenUpdated.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_ReferralUpdate.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_RemovedSupportedAsset.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_RoleAdminChanged.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_RoleGranted.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_RoleRevoked.json
dags/resources/stages/parse/table_definitions/eigenpie/EigenpieConfig_event_SetContract.json

Adds Eigenpie Config contract events
None

Eigenpie-config contract events

---

dags/resources/stages/parse/table_definitions/arbitrum/SequencerInbox_call_addSequencerL2Batch.json
dags/resources/stages/parse/table_definitions/arbitrum/SequencerInbox_call_addSequencerL2BatchFromOriginWithGasRefunder.json

add support for Arbitrum Sequencer calls

add arbitrum sequencer calls

---

dags/resources/stages/parse/table_definitions/arbitrum_uniswap_v3_positions_nft/NonfungiblePositionManager_event_Approval.json
dags/resources/stages/parse/table_definitions/arbitrum_uniswap_v3_positions_nft/NonfungiblePositionManager_event_ApprovalForAll.json
dags/resources/stages/parse/table_definitions/arbitrum_uniswap_v3_positions_nft/NonfungiblePositionManager_event_Collect.json
dags/resources/stages/parse/table_definitions/arbitrum_uniswap_v3_positions_nft/NonfungiblePositionManager_event_DecreaseLiquidity.json
dags/resources/stages/parse/table_definitions/arbitrum_uniswap_v3_positions_nft/NonfungiblePositionManager_event_IncreaseLiquidity.json
dags/resources/stages/parse/table_definitions/arbitrum_uniswap_v3_positions_nft/NonfungiblePositionManager_event_Transfer.json

ie: Add support for arbitrum uniswap v3 contract events 

Used the Contract Parser: https://contract-parser.d5.ai to create arbitrum uniswap v3 events

---

dags/resources/stages/parse/table_definitions/spark/AToken_event_Approval.json
dags/resources/stages/parse/table_definitions/spark/AToken_event_BalanceTransfer.json
dags/resources/stages/parse/table_definitions/spark/AToken_event_Burn.json
dags/resources/stages/parse/table_definitions/spark/AToken_event_Initialized.json
dags/resources/stages/parse/table_definitions/spark/AToken_event_Mint.json
dags/resources/stages/parse/table_definitions/spark/AToken_event_Transfer.json
dags/resources/stages/parse/table_definitions/spark/StableDebtToken_event_Approval.json
dags/resources/stages/parse/table_definitions/spark/StableDebtToken_event_BorrowAllowanceDelegated.json
dags/resources/stages/parse/table_definitions/spark/StableDebtToken_event_Burn.json
dags/resources/stages/parse/table_definitions/spark/StableDebtToken_event_Initialized.json
dags/resources/stages/parse/table_definitions/spark/StableDebtToken_event_Mint.json
dags/resources/stages/parse/table_definitions/spark/StableDebtToken_event_Transfer.json
dags/resources/stages/parse/table_definitions/spark/VariableDebtToken_event_Approval.json
dags/resources/stages/parse/table_definitions/spark/VariableDebtToken_event_BorrowAllowanceDelegated.json
dags/resources/stages/parse/table_definitions/spark/VariableDebtToken_event_Burn.json
dags/resources/stages/parse/table_definitions/spark/VariableDebtToken_event_Initialized.json
dags/resources/stages/parse/table_definitions/spark/VariableDebtToken_event_Mint.json
dags/resources/stages/parse/table_definitions/spark/VariableDebtToken_event_Transfer.json

Add support for [Spark](https://spark.fi/) token events
PR #690 should be merged first, as this PR depends on one of its events

(Dependent on #690) Spark Protocol Tokens events

---

dags/resources/stages/parse/table_definitions/morpho/MorphoChainlinkOracleV2Factory_event_CreateMorphoChainlinkOracleV2.json

Add support for morpho chainlink factory contract events 

[Gauntlet] Add Morphochainlink factory v2

---

dags/resources/stages/enrich/schemas/blocks.json
dags/resources/stages/enrich/schemas/transactions.json
dags/resources/stages/enrich/sqls/blocks.sql
dags/resources/stages/enrich/sqls/merge/merge_blocks.sql
dags/resources/stages/enrich/sqls/merge/merge_transactions.sql
dags/resources/stages/enrich/sqls/transactions.sql
dags/resources/stages/raw/schemas/blocks.json
dags/resources/stages/raw/schemas/receipts.json
dags/resources/stages/raw/schemas/transactions.json
docs/eip_4844_migration.md
requirements_airflow.txt
requirements_parse.txt

- Added new fields for EIP-4844 txs, blocks, and receipts

Add EIP-4844 (Dencun) fields

---

dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_Initialized.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_MinWithdrawalDelayBlocksSet.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_OperatorDetailsModified.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_OperatorMetadataURIUpdated.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_OperatorRegistered.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_OperatorSharesDecreased.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_OperatorSharesIncreased.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_Paused.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_PauserRegistrySet.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_StakerDelegated.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_StakerForceUndelegated.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_StakerUndelegated.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_StrategyWithdrawalDelayBlocksSet.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_Unpaused.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_WithdrawalCompleted.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_WithdrawalMigrated.json
dags/resources/stages/parse/table_definitions/eigenlayer/DelegationManager_event_WithdrawalQueued.json

Add support for eigenlayer delegation manager events 

added eigenlayer delegation manager events

---

dags/ethereumetl_airflow/build_partition_dag.py
dags/resources/stages/enrich/sqls/balances.sql

- Fix balance calculation after Dencun upgrade
https://github.com/blockchain-etl/ethereum-etl-airflow/pull/694

Fix balance calculation after Dencun upgrade

---

dags/resources/stages/parse/table_definitions/eigenlayer/AVSDirectory_event_AVSMetadataURIUpdated.json
dags/resources/stages/parse/table_definitions/eigenlayer/AVSDirectory_event_Initialized.json
dags/resources/stages/parse/table_definitions/eigenlayer/AVSDirectory_event_OperatorAVSRegistrationStatusUpdated.json
dags/resources/stages/parse/table_definitions/eigenlayer/AVSDirectory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/eigenlayer/AVSDirectory_event_Paused.json
dags/resources/stages/parse/table_definitions/eigenlayer/AVSDirectory_event_PauserRegistrySet.json
dags/resources/stages/parse/table_definitions/eigenlayer/AVSDirectory_event_Unpaused.json

add eigenlayer avs directory events

add eigenlayer avs directory events

---

dags/resources/stages/parse/table_definitions/eigenlayer/EigenPodManager_event_BeaconChainETHWithdrawalCompleted.json
dags/resources/stages/parse/table_definitions/eigenlayer/EigenPodManager_event_DenebForkTimestampUpdated.json
dags/resources/stages/parse/table_definitions/eigenlayer/EigenPodManager_event_PodSharesUpdated.json

Add support for eigenlayer m2 mainnet eigenpod manager contract events

m2 eigenpod manager events

---

dags/resources/stages/parse/table_definitions/weeth/WEETHToken_event_AdminChanged.json
dags/resources/stages/parse/table_definitions/weeth/WEETHToken_event_Approval.json
dags/resources/stages/parse/table_definitions/weeth/WEETHToken_event_BeaconUpgraded.json
dags/resources/stages/parse/table_definitions/weeth/WEETHToken_event_Initialized.json
dags/resources/stages/parse/table_definitions/weeth/WEETHToken_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/weeth/WEETHToken_event_Transfer.json
dags/resources/stages/parse/table_definitions/weeth/WEETHToken_event_Upgraded.json

add weeth events

---

dags/resources/stages/parse/table_definitions/curve/CurveStableswapFactoryNG_event_Transfer.json

Add support for CurveStableswapFactoryNG plain pool transfers

add transfer event

---

dags/resources/stages/parse/table_definitions/curve/CurveStableswapFactoryNG_event_Transfer.json
dags/resources/stages/parse/table_definitions/curve/view_stable_swap_factory_ng_pools.sql

Curve plain pool transfers

---

dags/resources/stages/parse/table_definitions/maker/McdFlash_call_flashLoan.json
dags/resources/stages/parse/table_definitions/maker/McdFlash_call_vatDaiFlashLoan.json
dags/resources/stages/parse/table_definitions/maker/McdFlash_event_Deny.json
dags/resources/stages/parse/table_definitions/maker/McdFlash_event_File.json
dags/resources/stages/parse/table_definitions/maker/McdFlash_event_FlashLoan.json
dags/resources/stages/parse/table_definitions/maker/McdFlash_event_Rely.json
dags/resources/stages/parse/table_definitions/maker/McdFlash_event_VatDaiFlashLoan.json

Add support for Maker's Mcd Flash loan contract events and calls
None

Maker Mcd Flash loan events and calls

---

dags/resources/stages/parse/table_definitions/pancakeswap/NonfungiblePositionManager_call_Mint.json
dags/resources/stages/parse/table_definitions/pancakeswap/NonfungiblePositionManager_event_Approval.json
dags/resources/stages/parse/table_definitions/pancakeswap/NonfungiblePositionManager_event_ApprovalForAll.json
dags/resources/stages/parse/table_definitions/pancakeswap/NonfungiblePositionManager_event_Collect.json
dags/resources/stages/parse/table_definitions/pancakeswap/NonfungiblePositionManager_event_DecreaseLiquidity.json
dags/resources/stages/parse/table_definitions/pancakeswap/NonfungiblePositionManager_event_IncreaseLiquidity.json
dags/resources/stages/parse/table_definitions/pancakeswap/NonfungiblePositionManager_event_Transfer.json

ie: Add support for pancake swap v3 contract events 
copied from uniswap

add events for pancake swap 3

---

dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_AdaptorCalled.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_AdaptorCatalogueAltered.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_AlternativeAssetDropped.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_AlternativeAssetUpdated.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_Approval.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_AuthorityUpdated.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_Deposit.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_MultiAssetDeposit.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_PositionAdded.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_PositionCatalogueAltered.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_PositionRemoved.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_PositionSwapped.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_RebalanceDeviationChanged.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_SharePriceOracleUpdated.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_ShutdownChanged.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_StrategistPayoutAddressChanged.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_StrategistPlatformCutChanged.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_Transfer.json
dags/resources/stages/parse/table_definitions/lqidethfiv1/LQIDETHFIV1Token_event_Withdraw.json

add etherfi liquid token events

add etherfi liquid token events

---

dags/resources/stages/parse/table_definitions/balancer/V2_LiquidityGaugeFactory_event_GaugeCreated.json
dags/resources/stages/parse/table_definitions/balancer/V2_LiquidityGaugeV5_event_Approval.json
dags/resources/stages/parse/table_definitions/balancer/V2_LiquidityGaugeV5_event_Deposit.json
dags/resources/stages/parse/table_definitions/balancer/V2_LiquidityGaugeV5_event_RelativeWeightCapChanged.json
dags/resources/stages/parse/table_definitions/balancer/V2_LiquidityGaugeV5_event_RewardDistributorUpdated.json
dags/resources/stages/parse/table_definitions/balancer/V2_LiquidityGaugeV5_event_Transfer.json
dags/resources/stages/parse/table_definitions/balancer/V2_LiquidityGaugeV5_event_UpdateLiquidityLimit.json
dags/resources/stages/parse/table_definitions/balancer/V2_LiquidityGaugeV5_event_Withdraw.json

add balancer v2 gauge events

---

dags/resources/stages/parse/table_definitions/gearbox/PoolQuotaKeeperV3_event_AddCreditManager.json
dags/resources/stages/parse/table_definitions/gearbox/PoolQuotaKeeperV3_event_AddQuotaToken.json
dags/resources/stages/parse/table_definitions/gearbox/PoolQuotaKeeperV3_event_NewController.json
dags/resources/stages/parse/table_definitions/gearbox/PoolQuotaKeeperV3_event_Paused.json
dags/resources/stages/parse/table_definitions/gearbox/PoolQuotaKeeperV3_event_SetGauge.json
dags/resources/stages/parse/table_definitions/gearbox/PoolQuotaKeeperV3_event_SetQuotaIncreaseFee.json
dags/resources/stages/parse/table_definitions/gearbox/PoolQuotaKeeperV3_event_SetTokenLimit.json
dags/resources/stages/parse/table_definitions/gearbox/PoolQuotaKeeperV3_event_Unpaused.json
dags/resources/stages/parse/table_definitions/gearbox/PoolQuotaKeeperV3_event_UpdateQuota.json
dags/resources/stages/parse/table_definitions/gearbox/PoolQuotaKeeperV3_event_UpdateTokenQuotaRate.json

ie: Add support for gearbox contract events 

add gearbox pool quota events

---

dags/resources/stages/parse/table_definitions/echelon/PrimeCaching_event_DepositCreated.json
dags/resources/stages/parse/table_definitions/echelon/PrimeCaching_event_DepositExtended.json
dags/resources/stages/parse/table_definitions/echelon/PrimeCaching_event_DepositsWithdrawn.json

Add support for echelon prime caching contract events 

add echelon prime caching events

---

dags/resources/stages/parse/table_definitions/kelpdao/ProxyFactory_call_computeAddress.json
dags/resources/stages/parse/table_definitions/kelpdao/ProxyFactory_call_create.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_AuthorityUpdated.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_Initialized.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_MinimumVTAmountChanged.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_ModuleWeightsChanged.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_NewPufferModuleCreated.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_NumberOfRegisteredValidatorsChanged.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_SuccessfullyProvisioned.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_Upgraded.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_VTPenaltyChanged.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_ValidatorExited.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_ValidatorKeyRegistered.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_ValidatorLimitPerModuleChanged.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_ValidatorSkipped.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_ValidatorTicketsDeposited.json
dags/resources/stages/parse/table_definitions/puffer/PufferProtocol_event_ValidatorTicketsWithdrawn.json

ie: Add support for puffer and kelpdao events contract events 

puffer and kelpdao events

---

dags/resources/stages/parse/table_definitions/renzo/WithdrawQueue_event_CoolDownPeriodUpdated.json
dags/resources/stages/parse/table_definitions/renzo/WithdrawQueue_event_ERC20BufferFilled.json
dags/resources/stages/parse/table_definitions/renzo/WithdrawQueue_event_EthBufferFilled.json
dags/resources/stages/parse/table_definitions/renzo/WithdrawQueue_event_Initialized.json
dags/resources/stages/parse/table_definitions/renzo/WithdrawQueue_event_Paused.json
dags/resources/stages/parse/table_definitions/renzo/WithdrawQueue_event_Unpaused.json
dags/resources/stages/parse/table_definitions/renzo/WithdrawQueue_event_WithdrawBufferTargetUpdated.json
dags/resources/stages/parse/table_definitions/renzo/WithdrawQueue_event_WithdrawRequestClaimed.json
dags/resources/stages/parse/table_definitions/renzo/WithdrawQueue_event_WithdrawRequestCreated.json

ie: Add support for ezeth withdrawal events

ezeth withdrawal events

---

README.md
dags/ethereumetl_airflow/build_export_dag.py
dags/ethereumetl_airflow/parse/table_definition_reader.py
dags/ethereumetl_airflow/parse/toposort.py
docker/webserver_config_local.py

Rectify typographical inaccuracies
This PR addresses several typographical errors across various files in the project. The changes improve readability and maintain the professional standard of the documentation and code comments.
Justification
Typographical errors, while minor, can detract from the overall quality of the project. Correcting these errors ensures clarity and professionalism, making the project more accessible and understandable for current and future contributors.

Docs improvements

---

dags/resources/stages/parse/table_definitions/curve/CurveStableswapFactoryNGLiquidityGauge_event_Transfer.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_AddPool.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_Deposit.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_Harvest.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_NewLMPoolDeployerAddress.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_NewOperatorAddress.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_NewPeriodDuration.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_NewReceiver.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_NewUpkeepPeriod.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_SetEmergency.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_SetPool.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_UpdateFarmBoostContract.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_UpdateLiquidity.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_UpdateUpkeepPeriod.json
dags/resources/stages/parse/table_definitions/pancakeswap/MasterChefV3_event_Withdraw.json

ie: Add support for pancakeswap contract events 

add pancakeswap events

---

dags/resources/stages/parse/table_definitions/ajna/ERC20PoolFactory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/ajna/ERC721PoolFactory_event_PoolCreated.json

ie: Update Ajna ERC20 & ERC721 factory pool contract addresses
Edited existing table definitions

Update Ajna Factory Pool Addresses

---

dags/resources/stages/parse/table_definitions/weeth/WeETH_call_getRate.json

ie: Add support for weeth rate call

add weeth rate call

---

dags/resources/stages/parse/table_definitions/etherfi/LQIDETHFIV1_event_Approval.json
dags/resources/stages/parse/table_definitions/etherfi/LQIDETHFIV1_event_AuthorityUpdated.json
dags/resources/stages/parse/table_definitions/etherfi/LQIDETHFIV1_event_Enter.json
dags/resources/stages/parse/table_definitions/etherfi/LQIDETHFIV1_event_Exit.json
dags/resources/stages/parse/table_definitions/etherfi/LQIDETHFIV1_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/etherfi/LQIDETHFIV1_event_Transfer.json

ie: Add support for etherfi vault contract events 

add etherfi veda vault events

---

dags/resources/stages/parse/table_definitions/ajna/ERC20PoolFactory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/ajna/ERC721PoolFactory_event_PoolCreated.json

Reverts blockchain-etl/ethereum-etl-airflow#739
- going to revert this merge
- then make a new PR to redo the commit and merge
Inelegant, but a solution to making CI/CD fire and update these tables after last time it got stuck.

Revert "Update Ajna Factory Pool Addresses"

---

dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_AddCollateral.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_AddQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_ApproveLPTransferors.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_AuctionNFTSettle.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_AuctionSettle.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_BondWithdrawn.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_BucketBankruptcy.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_BucketTake.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_BucketTakeLPAwarded.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_DecreaseLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_DrawDebt.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_Flashloan.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_IncreaseLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_InterestUpdateFailure.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_Kick.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_KickReserveAuction.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_LoanStamped.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_MoveQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_RemoveCollateral.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_RemoveQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_RepayDebt.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_ReserveAuction.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_ResetInterestRate.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_RevokeLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_RevokeLPTransferors.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_Settle.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_Take.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_TransferLP.json
dags/resources/stages/parse/table_definitions/ajna_v2/ERC20Pool_event_UpdateInterestRate.json

Add v2 pool events for Ajna 
NOTE: need to wait for previous PR to be built and tables to be ready before merging!

Add ajdna v2 pool events

---

.github/workflows/cicd-on-pr.yml
dags/ethereumetl_airflow/parse/parse_dataset_folder_logic.py

The file change limit was increased while deleting ajna v1 datsets, this simply reverts the file change limit back to 50

Bring back fill change limit to 50

---

dags/resources/stages/parse/table_definitions/ajna/ERC20PoolFactory_event_PoolCreated.json
dags/resources/stages/parse/table_definitions/ajna/ERC721PoolFactory_event_PoolCreated.json

Add v1 ajna pool factory contracts

---

dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_AddCollateral.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_AddQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_ApproveLPTransferors.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_AuctionNFTSettle.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_AuctionSettle.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_BondWithdrawn.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_BucketBankruptcy.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_BucketTake.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_BucketTakeLPAwarded.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_DecreaseLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_DrawDebt.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_Flashloan.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_IncreaseLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_Kick.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_KickReserveAuction.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_LoanStamped.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_MoveQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_RemoveCollateral.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_RemoveQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_RepayDebt.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_ReserveAuction.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_ResetInterestRate.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_RevokeLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_RevokeLPTransferors.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_Settle.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_Take.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_TransferLP.json
dags/resources/stages/parse/table_definitions/ajna/ERC20Pool_event_UpdateInterestRate.json

v1 pool events for ajna erc20

---

dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_AddCollateralNFT.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_AddQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_ApproveLPTransferors.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_AuctionNFTSettle.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_AuctionSettle.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_BondWithdrawn.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_BucketBankruptcy.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_BucketTake.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_BucketTakeLPAwarded.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_DecreaseLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_DrawDebtNFT.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_Flashloan.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_IncreaseLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_Kick.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_KickReserveAuction.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_LoanStamped.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_MergeOrRemoveCollateralNFT.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_MoveQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_RemoveCollateral.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_RemoveQuoteToken.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_RepayDebt.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_ReserveAuction.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_ResetInterestRate.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_RevokeLPAllowance.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_RevokeLPTransferors.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_Settle.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_Take.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_TransferLP.json
dags/resources/stages/parse/table_definitions/ajna/ERC721Pool_event_UpdateInterestRate.json

Ajna V1 721 events

---

dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_event_AssetWithdrawalQueued_Upgrade.json

Make table_name match file name in LRTWithdrawalManager_event_AssetWithdrawalQueued_Upgrade.json

Fix table_name in LRTWithdrawalManager_event_AssetWithdrawalQueued_Upgrade.json

---

dags/resources/stages/parse/table_definitions/pendle/PendleSYToken_event_Approval.json
dags/resources/stages/parse/table_definitions/pendle/PendleSYToken_event_ClaimRewards.json
dags/resources/stages/parse/table_definitions/pendle/PendleSYToken_event_Deposit.json
dags/resources/stages/parse/table_definitions/pendle/PendleSYToken_event_EIP712DomainChanged.json
dags/resources/stages/parse/table_definitions/pendle/PendleSYToken_event_Initialized.json
dags/resources/stages/parse/table_definitions/pendle/PendleSYToken_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/pendle/PendleSYToken_event_Paused.json
dags/resources/stages/parse/table_definitions/pendle/PendleSYToken_event_Redeem.json
dags/resources/stages/parse/table_definitions/pendle/PendleSYToken_event_SetNewExchangeRateOracle.json
dags/resources/stages/parse/table_definitions/pendle/PendleSYToken_event_Transfer.json
dags/resources/stages/parse/table_definitions/pendle/PendleSYToken_event_Unpaused.json

Added support for Pendle SY token events

add Pendle SY token events

---

dags/resources/stages/parse/table_definitions/renzo/WithdrawQueue_event_WithdrawRequestCreated_Upgrade.json

ie: Add support for ezETH contract events 

Update ezETH withdrawqueue event

---

dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_AddedToWhitelist.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_Approval.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_ApprovalForAll.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_BaseURIUpdated.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_ETHReceived.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_Initialized.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_RemovedFromWhitelist.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_Transfer.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_WhitelistDisabled.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_WhitelistEnabled.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_WithdrawRequestCreated.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_WithdrawalClaimed.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_WithdrawalRequestMaximumUpdated.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_WithdrawalRequestMinimumUpdated.json
dags/resources/stages/parse/table_definitions/swell/RswEXIT_event_WithdrawalsProcessed.json

ie: Add support for rsweth withdrawal contract events 

Add RSWETH Withdrawal Manager Contract

---

dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_Approval.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_DebtPurchased.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_DebtUpdated.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_Deposit.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_RoleSet.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_Shutdown.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_StrategyChanged.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_StrategyReported.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_Transfer.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_UpdateAccountant.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_UpdateDefaultQueue.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_UpdateDepositLimit.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_UpdateDepositLimitModule.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_UpdateMinimumTotalIdle.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_UpdateProfitMaxUnlockTime.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_UpdateRoleManager.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_UpdateUseDefaultQueue.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_UpdateWithdrawLimitModule.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_UpdatedMaxDebtForStrategy.json
dags/resources/stages/parse/table_definitions/swell/YearnV3Vault_event_Withdraw.json
dags/resources/stages/parse/table_definitions/swell/YearnVaultFactory_event_FactoryShutdown.json
dags/resources/stages/parse/table_definitions/swell/YearnVaultFactory_event_NewPendingGovernance.json
dags/resources/stages/parse/table_definitions/swell/YearnVaultFactory_event_NewVault.json
dags/resources/stages/parse/table_definitions/swell/YearnVaultFactory_event_RemovedCustomProtocolFee.json
dags/resources/stages/parse/table_definitions/swell/YearnVaultFactory_event_UpdateCustomProtocolFee.json
dags/resources/stages/parse/table_definitions/swell/YearnVaultFactory_event_UpdateGovernance.json
dags/resources/stages/parse/table_definitions/swell/YearnVaultFactory_event_UpdateProtocolFeeBps.json
dags/resources/stages/parse/table_definitions/swell/YearnVaultFactory_event_UpdateProtocolFeeRecipient.json

Add Swell Vault Factory, Vault Event Logs

---

dags/resources/stages/parse/table_definitions/etherfi/EtherFiAdmin_event_AdminChanged.json
dags/resources/stages/parse/table_definitions/etherfi/EtherFiAdmin_event_AdminOperationsExecuted.json
dags/resources/stages/parse/table_definitions/etherfi/EtherFiAdmin_event_AdminUpdated.json
dags/resources/stages/parse/table_definitions/etherfi/EtherFiAdmin_event_BeaconUpgraded.json
dags/resources/stages/parse/table_definitions/etherfi/EtherFiAdmin_event_Initialized.json
dags/resources/stages/parse/table_definitions/etherfi/EtherFiAdmin_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/etherfi/EtherFiAdmin_event_Upgraded.json

ie: Add support for etherfi admin contract events 

Etherfi Admin Events

---

dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_assetsCommitted.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_completeWithdrawal.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_getAvailableAssetAmount.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_getExpectedAssetAmount.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_getRequestId.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_getUserWithdrawalRequest.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_initialize.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_initiateWithdrawal.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_lrtConfig.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_minRsEthAmountToWithdraw.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_nextLockedNonce.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_nextUnusedNonce.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_pause.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_paused.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_receiveFromLRTUnstakingVault.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_setMinRsEthAmountToWithdraw.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_setWithdrawalDelayBlocks.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_unlockQueue.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_unpause.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_updateLRTConfig.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_userAssociatedNonces.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_withdrawalDelayBlocks.json
dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_call_withdrawalRequests.json

ie: Add support for kelpdao contract calls 

Kelp withdrawal contract calls

---

dags/resources/stages/parse/table_definitions/sbtc/SBTC_event_Approval.json
dags/resources/stages/parse/table_definitions/sbtc/SBTC_event_OwnerChanged.json
dags/resources/stages/parse/table_definitions/sbtc/SBTC_event_OwnerNominated.json
dags/resources/stages/parse/table_definitions/sbtc/SBTC_event_TargetUpdated.json
dags/resources/stages/parse/table_definitions/sbtc/SBTC_event_Transfer.json

Add support for sBTC contract events 
I used abi-parser(https://contract-parser.d5.ai) to build the table definitions

Added SBTC events

---

dags/resources/stages/parse/table_definitions/eigenpie/EigenpieWithdrawManager_event_UserQueuingForWithdrawal.json

add support for Eigenpie WithdrawManager event

Add Eigenpie UserQueuingForWithdrawal event

---

dags/resources/stages/parse/table_definitions/bebop/BebopAggregationContract_call_SettleAggregateOrder.json
dags/resources/stages/parse/table_definitions/bebop/BebopAggregationContract_event_AggregateOrderExecuted.json
dags/resources/stages/parse/table_definitions/bebop/BebopSettlement_call_SettleAggregateOrder.json
dags/resources/stages/parse/table_definitions/bebop/BebopSettlement_call_SettleAggregateOrderWithTakerPermits.json
dags/resources/stages/parse/table_definitions/bebop/BebopSettlement_event_AggregateOrderExecuted.json

Add support for Bebop RFQ trades

add support for Bebop RFQ

---

dags/resources/stages/parse/table_definitions/maker/USDS_event_Transfer.sql

Add suport for USDS transfers

---

dags/resources/stages/parse/table_definitions/compound/cwstETHv3_event_AbsorbCollateral.json
dags/resources/stages/parse/table_definitions/compound/cwstETHv3_event_AbsorbDebt.json
dags/resources/stages/parse/table_definitions/compound/cwstETHv3_event_BuyCollateral.json
dags/resources/stages/parse/table_definitions/compound/cwstETHv3_event_PauseAction.json
dags/resources/stages/parse/table_definitions/compound/cwstETHv3_event_Supply.json
dags/resources/stages/parse/table_definitions/compound/cwstETHv3_event_SupplyCollateral.json
dags/resources/stages/parse/table_definitions/compound/cwstETHv3_event_Transfer.json
dags/resources/stages/parse/table_definitions/compound/cwstETHv3_event_TransferCollateral.json
dags/resources/stages/parse/table_definitions/compound/cwstETHv3_event_Withdraw.json
dags/resources/stages/parse/table_definitions/compound/cwstETHv3_event_WithdrawCollateral.json
dags/resources/stages/parse/table_definitions/compound/cwstETHv3_event_WithdrawReserves.json

ie: Add support for compound V3 wstETH mainnet comet events

[Gauntlet] - add compound v3 wstETH mainnet comet events

---

dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_AVSRewardsSubmissionCreated.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_ActivationDelaySet.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_ClaimerForSet.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_DistributionRootDisabled.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_DistributionRootSubmitted.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_GlobalCommissionBipsSet.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_Initialized.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_Paused.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_PauserRegistrySet.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_RewardsClaimed.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_RewardsForAllSubmitterSet.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_RewardsSubmissionForAllCreated.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_RewardsSubmissionForAllEarnersCreated.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_RewardsUpdaterSet.json
dags/resources/stages/parse/table_definitions/eigenlayer/RewardsCoordinator_event_Unpaused.json
dags/resources/stages/parse/table_definitions/eigenlayer/StrategyFactory_event_Initialized.json
dags/resources/stages/parse/table_definitions/eigenlayer/StrategyFactory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/eigenlayer/StrategyFactory_event_Paused.json
dags/resources/stages/parse/table_definitions/eigenlayer/StrategyFactory_event_PauserRegistrySet.json
dags/resources/stages/parse/table_definitions/eigenlayer/StrategyFactory_event_StrategyBeaconModified.json
dags/resources/stages/parse/table_definitions/eigenlayer/StrategyFactory_event_TokenBlacklisted.json
dags/resources/stages/parse/table_definitions/eigenlayer/StrategyFactory_event_Unpaused.json

I accidentally put in testnet addresses into the jsons instead of the mainnet + adding back in file I removed previously for file limit purposes

revise EL addresses

---

dags/resources/stages/parse/table_definitions/arrakis/ArrakisV2_event_LogBurn.json
dags/resources/stages/parse/table_definitions/arrakis/ArrakisV2_event_LogMint.json

- Adding support for arrakisV2 mint and burn events to improve performance tracking.
- I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table definitions

Adding ArrakisV2 Mint and Burn

---

dags/resources/stages/parse/table_definitions/puffer/PufferWithdrawalManager_event_AuthorityUpdated.json
dags/resources/stages/parse/table_definitions/puffer/PufferWithdrawalManager_event_BatchFinalized.json
dags/resources/stages/parse/table_definitions/puffer/PufferWithdrawalManager_event_ExcessETHReturned.json
dags/resources/stages/parse/table_definitions/puffer/PufferWithdrawalManager_event_Initialized.json
dags/resources/stages/parse/table_definitions/puffer/PufferWithdrawalManager_event_MaxWithdrawalAmountChanged.json
dags/resources/stages/parse/table_definitions/puffer/PufferWithdrawalManager_event_Upgraded.json
dags/resources/stages/parse/table_definitions/puffer/PufferWithdrawalManager_event_WithdrawalCompleted.json
dags/resources/stages/parse/table_definitions/puffer/PufferWithdrawalManager_event_WithdrawalRequested.json

ie: Add Puffer withdrawal manager events
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/)  build the table definitions

[Gauntlet] add puffer withdrawal manager events

---

dags/resources/stages/parse/table_definitions/compound/cUSDSv3_event_AbsorbCollateral.json
dags/resources/stages/parse/table_definitions/compound/cUSDSv3_event_AbsorbDebt.json
dags/resources/stages/parse/table_definitions/compound/cUSDSv3_event_BuyCollateral.json
dags/resources/stages/parse/table_definitions/compound/cUSDSv3_event_PauseAction.json
dags/resources/stages/parse/table_definitions/compound/cUSDSv3_event_Supply.json
dags/resources/stages/parse/table_definitions/compound/cUSDSv3_event_SupplyCollateral.json
dags/resources/stages/parse/table_definitions/compound/cUSDSv3_event_Transfer.json
dags/resources/stages/parse/table_definitions/compound/cUSDSv3_event_TransferCollateral.json
dags/resources/stages/parse/table_definitions/compound/cUSDSv3_event_Withdraw.json
dags/resources/stages/parse/table_definitions/compound/cUSDSv3_event_WithdrawCollateral.json
dags/resources/stages/parse/table_definitions/compound/cUSDSv3_event_WithdrawReserves.json

ie: Add Compound V3 USDS comet event ingestion

[Gauntlet] Compound V3 USDS event ingestion

---

dags/resources/stages/parse/table_definitions/milkman/Milkman_event_SwapRequested.json

ie: Add support for Milkman contract events 

Add Milkman events

---

dags/resources/stages/parse/table_definitions/cowswap/Cowswap_event_Settlement.json
dags/resources/stages/parse/table_definitions/cowswap/Cowswap_event_Trade.json
dags/resources/stages/parse/table_definitions/odos/Odos_event_Swap.json
dags/resources/stages/parse/table_definitions/odos/Odos_event_SwapMulti.json

Add CoWswap and Odos swap events on mainnet
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) or to build the table definitions

add cowswap and odos swap events

---

dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Approval.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_BalanceForwarderStatus.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Borrow.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_ConvertFees.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_DebtSocialized.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Deposit.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_EVaultCreated.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetCaps.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetConfigFlags.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetFeeReceiver.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetGovernorAdmin.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetHookConfig.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetInterestFee.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetInterestRateModel.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetLTV.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetLiquidationCoolOffTime.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetMaxLiquidationDiscount.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_InterestAccrued.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Liquidate.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_PullDebt.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Repay.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Transfer.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_VaultStatus.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Withdraw.json

ie: Add support for Euler V2 EVault events

[Gauntlet] Euler V2 EVault events

---

dags/resources/stages/parse/table_definitions/morpho/MetaMorphoFactory_event_CreateMetaMorpho.json
dags/resources/stages/parse/table_definitions/morpho/MetaMorphoV1_1_event_SetName.json
dags/resources/stages/parse/table_definitions/morpho/MetaMorphoV1_1_event_SetSymbol.json
dags/resources/stages/parse/table_definitions/morpho/MetaMorphoV1_1_event_UpdateLostAssets.json

Add support for MetaMorpho V1.1 contract events 

[Gauntlet] Add morpho factory v1.1

---

dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Approval.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_BalanceForwarderStatus.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Borrow.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_ConvertFees.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_DebtSocialized.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Deposit.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_EVaultCreated.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetCaps.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetConfigFlags.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetFeeReceiver.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetGovernorAdmin.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetHookConfig.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetInterestFee.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetInterestRateModel.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetLTV.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetLiquidationCoolOffTime.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_GovSetMaxLiquidationDiscount.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_InterestAccrued.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Liquidate.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_PullDebt.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Repay.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Transfer.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_VaultStatus.json
dags/resources/stages/parse/table_definitions/euler_v2/EVault_event_Withdraw.json

Fixing the casing to be uppercase for keywords in the query to fix the CI/CD JSON checker.

Fix casing in query

---

dags/resources/stages/parse/table_definitions/symbiotic/BurnerRouterFactory_event_AddEntity.json
dags/resources/stages/parse/table_definitions/symbiotic/DefaultOperatorRewardsFactory_event_AddEntity.json
dags/resources/stages/parse/table_definitions/symbiotic/DefaultStakerRewardsFactory_event_AddEntity.json
dags/resources/stages/parse/table_definitions/symbiotic/DelegatorFactory_event_AddEntity.json
dags/resources/stages/parse/table_definitions/symbiotic/DelegatorFactory_event_Blacklist.json
dags/resources/stages/parse/table_definitions/symbiotic/DelegatorFactory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/symbiotic/DelegatorFactory_event_Whitelist.json
dags/resources/stages/parse/table_definitions/symbiotic/NetworkMiddlewareService_event_SetMiddleware.json
dags/resources/stages/parse/table_definitions/symbiotic/NetworkRegistry_event_AddEntity.json
dags/resources/stages/parse/table_definitions/symbiotic/OperatorNetworkOptInService_event_EIP712DomainChanged.json
dags/resources/stages/parse/table_definitions/symbiotic/OperatorNetworkOptInService_event_IncreaseNonce.json
dags/resources/stages/parse/table_definitions/symbiotic/OperatorNetworkOptInService_event_OptIn.json
dags/resources/stages/parse/table_definitions/symbiotic/OperatorNetworkOptInService_event_OptOut.json
dags/resources/stages/parse/table_definitions/symbiotic/OperatorRegistry_event_AddEntity.json
dags/resources/stages/parse/table_definitions/symbiotic/OperatorVaultOptInService_event_EIP712DomainChanged.json
dags/resources/stages/parse/table_definitions/symbiotic/OperatorVaultOptInService_event_IncreaseNonce.json
dags/resources/stages/parse/table_definitions/symbiotic/OperatorVaultOptInService_event_OptIn.json
dags/resources/stages/parse/table_definitions/symbiotic/OperatorVaultOptInService_event_OptOut.json
dags/resources/stages/parse/table_definitions/symbiotic/SlasherFactory_event_AddEntity.json
dags/resources/stages/parse/table_definitions/symbiotic/SlasherFactory_event_Blacklist.json
dags/resources/stages/parse/table_definitions/symbiotic/SlasherFactory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/symbiotic/SlasherFactory_event_Whitelist.json
dags/resources/stages/parse/table_definitions/symbiotic/VaultFactory_event_AddEntity.json
dags/resources/stages/parse/table_definitions/symbiotic/VaultFactory_event_Blacklist.json
dags/resources/stages/parse/table_definitions/symbiotic/VaultFactory_event_Migrate.json
dags/resources/stages/parse/table_definitions/symbiotic/VaultFactory_event_OwnershipTransferred.json
dags/resources/stages/parse/table_definitions/symbiotic/VaultFactory_event_Whitelist.json

ie: Add support for symbiotic contract events 

Symbiotic Factory Events

---

dags/resources/stages/parse/table_definitions/symbiotic/DelegatorFactory_call_create.json
dags/resources/stages/parse/table_definitions/symbiotic/NetworkRestakeDelegator_event_SetMaxNetworkLimit.json
dags/resources/stages/parse/table_definitions/symbiotic/SlasherFactory_call_create.json
dags/resources/stages/parse/table_definitions/symbiotic/VaultConfigurator_call_create.json
dags/resources/stages/parse/table_definitions/symbiotic/VaultFactory_call_create.json
dags/resources/stages/parse/table_definitions/symbiotic/VaultFactory_call_migrate.json

ie: Add support for symbiotic contract traces 

Symbiotic Create Traces

---

dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_AcceptedOperationsRole.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_AcceptedRegistrarRole.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_AcceptedTechnicalRole.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_AddressesFrozen.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_AddressesUnFrozen.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_AdminChanged.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_Approval.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_BeaconUpgraded.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_ImplementationAuthorized.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_Initialized.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_NamedNewOperators.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_Paused.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_Transfer.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_TransferRejected.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_TransferRequested.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_TransferValidated.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_UnPaused.json
dags/resources/stages/parse/table_definitions/eurcv/eurcv_event_Upgraded.json

Add support for eurcv contract events 
I used [abi-parser]

add eurcv events

---

dags/resources/stages/parse/table_definitions/morpho/PublicAllocator_event_PublicReallocateTo.json
dags/resources/stages/parse/table_definitions/morpho/PublicAllocator_event_PublicWithdrawal.json
dags/resources/stages/parse/table_definitions/morpho/PublicAllocator_event_SetAdmin.json
dags/resources/stages/parse/table_definitions/morpho/PublicAllocator_event_SetFee.json
dags/resources/stages/parse/table_definitions/morpho/PublicAllocator_event_SetFlowCaps.json
dags/resources/stages/parse/table_definitions/morpho/PublicAllocator_event_TransferFee.json

ie: Add support for morpho public allocator contract events 

add morpho public allocator events
