dags/export_dag.py, dags/load_dag.py, dags/resources/stages/enrich/sqls/blocks.sql, dags/resources/stages/enrich/sqls/contracts.sql, dags/resources/stages/enrich/sqls/logs.sql, dags/resources/stages/enrich/sqls/token_transfers.sql, dags/resources/stages/enrich/sqls/tokens.sql, dags/resources/stages/enrich/sqls/traces.sql, dags/resources/stages/enrich/sqls/transactions.sql, dags/resources/stages/verify/sqls/blocks_count.sql, dags/resources/stages/verify/sqls/blocks_have_latest.sql, dags/resources/stages/verify/sqls/logs_have_latest.sql, dags/resources/stages/verify/sqls/token_transfers_have_latest.sql, dags/resources/stages/verify/sqls/traces_blocks_count.sql, dags/resources/stages/verify/sqls/traces_contracts_count.sql, dags/resources/stages/verify/sqls/traces_transactions_count.sql, dags/resources/stages/verify/sqls/transactions_count.sql, dags/resources/stages/verify/sqls/transactions_have_latest.sql
This PR will aim to solve 2 things:
1) It allows passing the parameters for traces as ENV VARs, specifically `--genesis-traces` & `--daofork-traces`. That is the default. It allows passing instead `--no-daofork-traces` in the ENV VAR as an option in `$EXPORT_DAOFORK_TRACES' & `$EXPORT_GENESIS_TRACES` for `--genesis-traces`.
2) It allows the passing of the ENV VAR `DATASET_NAME`, which is default as `ethereum_blockchain`. It then parses all SQL files and replaces the default `blockchain` datasetname with the one passed.
The script for the dataset name is super hacky, which I can refactor before merging. Just wanted to check which approach you're looking for before we can finalize this PR.
=> Parametrize Dataset Names and Traces

dags/resources/stages/parse/table_definitions/zeroex/Exchange_v3_0_event_AssetProxyRegistered.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v3_0_event_Cancel.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v3_0_event_CancelUpTo.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v3_0_event_Fill.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v3_0_event_OwnershipTransferred.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v3_0_event_ProtocolFeeCollectorAddress.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v3_0_event_ProtocolFeeMultiplier.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v3_0_event_SignatureValidatorApproval.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v3_0_event_TransactionExecution.json
0x just launched their new Exchange contract (v3.0): `0x61935cbdd02287b511119ddb11aeb42f1593b7ef`.
This PR adds event tables for this contract to the `zeroex` dataset.
=> Add new 0x exchange contract (v3.0)

dags/resources/stages/parse/table_definitions/ens/ETHRegistrarController2_event_NameRegistered.json, dags/resources/stages/parse/table_definitions/ens/ETHRegistrarController2_event_NameRenewed.json, dags/resources/stages/parse/table_definitions/ens/ETHRegistrarController2_event_NewPriceOracle.json, dags/resources/stages/parse/table_definitions/ens/ETHRegistrarController2_event_OwnershipTransferred.json
This contract is marked as "ENS: ETH Registrar Controller 2" on Etherscan: `0xb22c1c159d12461ea124b0deb4b5b93020e6ad16`
I'm adding it to have a complete view of the ENS addresses.
=> Add 2nd ENS registrar controller

dags/resources/stages/parse/table_definitions/aragon/DAOFactory_event_DeployDAO.json, dags/resources/stages/parse/table_definitions/aragon/DAOFactory_event_DeployEVMScriptRegistry.json, dags/resources/stages/parse/table_definitions/aragon/Kernel_event_NewAppProxy.json, dags/resources/stages/parse/table_definitions/aragon/Kernel_event_RecoverToVault.json, dags/resources/stages/parse/table_definitions/aragon/Kernel_event_SetApp.json
Added events from Aragon contracts DAOFactory and Kernel.
DAOFactory produces child contracts which are identified via the `DeployDAO` events.
Kernel events take place in child contracts, and thus uses the `DeployDAO` table to identify the relevant contracts.
Note that the `DAOFactory` makes use of 3 distinct contract addresses since it currently has 3 different versions.
=> Aragon events from DAOFactory and Kernel

dags/resources/stages/parse/table_definitions/maker/Vat_call_move.json
This function is called when stablecoins are moved between users (including in/out of DSR).
More info here: https://docs.makerdao.com/smart-contract-modules/core-module/vat-detailed-documentation
=> Added Vat_call_move

dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_AdminClaimed.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_AlerterAdded.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_AssignBurnFees.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_AssignFeeToWallet.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_BurnAssignedFees.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_EtherWithdraw.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_KNCRateSet.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_OperatorAdded.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_ReserveDataSet.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_SendTaxFee.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_SendWalletFees.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_TaxFeesSet.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_TaxWalletSet.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_TokenWithdraw.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_TransferAdminPending.json, dags/resources/stages/parse/table_definitions/kyber/FeeBurner_event_WalletFeesSet.json
Currently we can't calculate how much KNC is burnt from our events.
This PR adds parsing for Kyber's FeeBurner contract, documented here: https://developer.kyber.network/docs/Integrations-ContractEvents/#feeburnerdocsenvironments-mainnetfeeburner
Used [Contract Parser](http://contract-parser.d5.ai/) but manually updated `contract_address` to include all versions of the contract.
=> Add Kyber's FeeBurner contract

dags/ethereumetl_airflow/parse.py, dags/resources/stages/parse/sqls/parse_logs.sql, dags/resources/stages/parse/table_definitions/dydx/SoloMargin_event_LogTrade.json, requirements.txt, tests/ethereumetl_airflow/test_parse.py, tests/resources/ethereumetl_airflow/test_parse/expected_dydx_SoloMargin_event_LogTrade.json.sql, tests/resources/ethereumetl_airflow/test_parse/expected_ens_Registrar0_event_NewBid.json.sql, tests/resources/ethereumetl_airflow/test_parse/expected_idex_Exchange_call_trade.json.sql, tests/resources/ethereumetl_airflow/test_parse/expected_uniswap_Uniswap_event_AddLiquidity.json.sql
ethers.js library is used now for parsing logs, which allows parsing events with tuple parameters. As an example SoloMargin_event_LogTrade.json is provided as well as the test cases with the expected query.
=> Use ethers.js for parsing logs

dags/resources/stages/parse/table_definitions/multis/GSNMultiSigWalletWithDailyLimit_event_Confirmation.json, dags/resources/stages/parse/table_definitions/multis/GSNMultiSigWalletWithDailyLimit_event_DailyLimitChange.json, dags/resources/stages/parse/table_definitions/multis/GSNMultiSigWalletWithDailyLimit_event_Deposit.json, dags/resources/stages/parse/table_definitions/multis/GSNMultiSigWalletWithDailyLimit_event_Execution.json, dags/resources/stages/parse/table_definitions/multis/GSNMultiSigWalletWithDailyLimit_event_ExecutionFailure.json, dags/resources/stages/parse/table_definitions/multis/GSNMultiSigWalletWithDailyLimit_event_OwnerAddition.json, dags/resources/stages/parse/table_definitions/multis/GSNMultiSigWalletWithDailyLimit_event_OwnerRemoval.json, dags/resources/stages/parse/table_definitions/multis/GSNMultiSigWalletWithDailyLimit_event_RelayHubChanged.json, dags/resources/stages/parse/table_definitions/multis/GSNMultiSigWalletWithDailyLimit_event_RequirementChange.json, dags/resources/stages/parse/table_definitions/multis/GSNMultiSigWalletWithDailyLimit_event_Revocation.json, dags/resources/stages/parse/table_definitions/multis/GSNMultiSigWalletWithDailyLimit_event_Submission.json, dags/resources/stages/parse/table_definitions/multis/GSNMultisigFactory_event_ContractInstantiation.json, dags/resources/stages/parse/table_definitions/multis/GSNMultisigFactory_event_MinterAdded.json, dags/resources/stages/parse/table_definitions/multis/GSNMultisigFactory_event_MinterRemoved.json, dags/resources/stages/parse/table_definitions/multis/GSNMultisigFactory_event_OwnershipTransferred.json, dags/resources/stages/parse/table_definitions/multis/GSNMultisigFactory_event_RelayHubChanged.json
Used [Contract Parser](https://contract-parser.d5.ai) on `0x58ccd381c5162c6d40f40de03d5d2eb779f87bb6` which is the implementation of this proxy: `0x16154f7e9de01e6b39dac3159805e9b1531ee3cf`.
I then manually replaced the implementation address with the proxy address.
Then for the child contracts I picked one, ran it through the Contract Parser, and then replaced the address field manually with `SELECT instantiation FROM ref('GSNMultisigFactory_event_ContractInstantiation')`.
=> Add Multis factory + child events

dags/resources/stages/parse/table_definitions/compound/GovernorAlpha_event_ProposalCanceled.json, dags/resources/stages/parse/table_definitions/compound/GovernorAlpha_event_ProposalCreated.json, dags/resources/stages/parse/table_definitions/compound/GovernorAlpha_event_ProposalExecuted.json, dags/resources/stages/parse/table_definitions/compound/GovernorAlpha_event_ProposalQueued.json, dags/resources/stages/parse/table_definitions/compound/GovernorAlpha_event_VoteCast.json
Used [Contract Parser](https://contract-parser.d5.ai) on `0xc0da01a04c3f3e0be433606045bb7017a7323e38`
See https://compound.finance/governance for more context.
NOTE: there's a `string[]` datatype in there - not 100% sure this will work out of the box.
=> Add GovernorAlpha event parsing

dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogAccountSettled.json, dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogDeposit.json, dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogFinalSettlementEnabled.json, dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogIndex.json, dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogSetFunder.json, dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogSetGlobalOperator.json, dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogSetLocalOperator.json, dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogSetMinCollateral.json, dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogSetOracle.json, dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogTrade.json, dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogWithdraw.json, dags/resources/stages/parse/table_definitions/dydx/PerpetualV1_event_LogWithdrawFinalSettlement.json
Used [Contract Parser](https://contract-parser.d5.ai) on `0x364508a5ca0538d8119d3bf40a284635686c98c4` with `0x07abe965500a49370d331ecd613c7ac47dd6e547` as proxy.
=> Add PerpetualV1 event parsing for dYdX

dags/resources/stages/parse/table_definitions/uniswap/UniswapV2Factory_event_PairCreated.json, dags/resources/stages/parse/table_definitions/uniswap/UniswapV2Pair_event_Approval.json, dags/resources/stages/parse/table_definitions/uniswap/UniswapV2Pair_event_Burn.json, dags/resources/stages/parse/table_definitions/uniswap/UniswapV2Pair_event_Mint.json, dags/resources/stages/parse/table_definitions/uniswap/UniswapV2Pair_event_Swap.json, dags/resources/stages/parse/table_definitions/uniswap/UniswapV2Pair_event_Sync.json, dags/resources/stages/parse/table_definitions/uniswap/UniswapV2Pair_event_Transfer.json
Used http://contract-parser.d5.ai/
Made two manual changes:
1. In `UniswapV2Factory_event_PairCreated`, the last argument was an anonymous `uint` so I named this `_uint`
2. Inside all `UniswapV2Pair_...` events, replaced the `contract_address` with the a factory reference: `SELECT pair FROM ref('UniswapV2Factory_event_PairCreated')`
=> Add UniswapV2 event parsing

dags/resources/stages/parse/table_definitions/maker/Flipper_ETH_call_dent.json
Add the `dent` phase of the Maker collateral auction.
=> Add Maker collateral auction dent call parsing

dags/resources/stages/parse/table_definitions/opyn/OptionsFactory_event_AssetAdded.json, dags/resources/stages/parse/table_definitions/opyn/OptionsFactory_event_AssetChanged.json, dags/resources/stages/parse/table_definitions/opyn/OptionsFactory_event_AssetDeleted.json, dags/resources/stages/parse/table_definitions/opyn/OptionsFactory_event_OptionsContractCreated.json, dags/resources/stages/parse/table_definitions/opyn/OptionsFactory_event_OwnershipTransferred.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_Approval.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_BurnOTokens.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_ERC20CollateralAdded.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_ETHCollateralAdded.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_Exercise.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_IssuedOTokens.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_Liquidate.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_OwnershipTransferred.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_RedeemVaultBalance.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_RemoveCollateral.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_RemoveUnderlying.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_Transfer.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_TransferFee.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_UpdateParameters.json, dags/resources/stages/parse/table_definitions/opyn/oToken_event_VaultOpened.json
OptionsFactory: `0xcc5d905b9c2c8c9329eb4e25dc086369d6c7777c`
oToken contracts are child contracts of that, so I've replaced the reference of contract address with:
`SELECT addr FROM ref('OptionsFactory_event_OptionsContractCreated')`.
=> Add OptionsFactory and oToken events

dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_Approval.json, dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_Burned.json, dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_Issued.json, dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_OwnerChanged.json, dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_OwnerNominated.json, dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_ProxyUpdated.json, dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_SelfDestructBeneficiaryUpdated.json, dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_SelfDestructInitiated.json, dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_SelfDestructTerminated.json, dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_SelfDestructed.json, dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_TokenStateUpdated.json, dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_Transfer.json
sBTC used to be in this contract: `0x9073ee83b6ce96c444547ddcaf777b9352163581` so we have to include this to capture all sBTC events.
Previously I included the 'target' address of the new proxy for sBTC, but this didn't have any events (they all go to the proxy) so we can safely remove this and replace it with the above one.
We need to re-run jobs though to get the correct history.
=> Replaced 'target' address with old sBTC contract to capture all events

dags/resources/stages/parse/table_definitions/sushiswap/UniswapV2Factory_event_PairCreated.json, dags/resources/stages/parse/table_definitions/sushiswap/UniswapV2Pair_event_Approval.json, dags/resources/stages/parse/table_definitions/sushiswap/UniswapV2Pair_event_Burn.json, dags/resources/stages/parse/table_definitions/sushiswap/UniswapV2Pair_event_Mint.json, dags/resources/stages/parse/table_definitions/sushiswap/UniswapV2Pair_event_Swap.json, dags/resources/stages/parse/table_definitions/sushiswap/UniswapV2Pair_event_Sync.json, dags/resources/stages/parse/table_definitions/sushiswap/UniswapV2Pair_event_Transfer.json
Copied UniswapV2 and just replaced the Factory address.
The contracts are forked from UniswapV2 which is why the names are the same. I think that's OK given that they'll be on their own `ethereum_sushiswap` namespace.
=> Add SushiSwap pool events

dags/ethereumetl_airflow/parse/parse_logic.py, dags/resources/stages/parse/sqls/parse_logs.sql, dags/resources/stages/parse/sqls/parse_traces.sql, dags/resources/stages/parse/sqls/parse_traces_udf.sql
Uses partitioned tables for live part for stitched view for parsed logs and traces which makes is 10x to 100x time more efficient in terms of cost.
=> Use partitioned tables for live parsed logs and traces

dags/ethereumetl_airflow/parse/parse_logic.py, dags/resources/stages/parse/sqls/parse_traces.sql, tests/resources/ethereumetl_airflow/test_parse/idex/Exchange_call_trade.json_True_1.sql, tests/resources/ethereumetl_airflow/test_parse/idex/Exchange_call_trade.json_True_2.sql
@medvedev1088 there are often multiple calls in the same block and the order the calls occurred in might be important. In our case at Balancer, we need to know what the last call in the block to some functions was. I'm a bit out of my depth here, but I tried to mimic what you did in 36663d9 and 33036c4. Let me know what you think. Thanks!
=> Add transaction_index to parse_traces.sql and parse_logic.py

dags/resources/stages/parse/table_definitions/mooniswap/MooniswapDeployer_call_deploy.json
- The deploy function call on 1inch passes name and symbol of pool which I require 
```
contract MooniswapDeployer {
function deploy(
IERC20 token1,
IERC20 token2,
string calldata name,
string calldata symbol,
address poolOwner
) external returns(Mooniswap pool) {
pool = new Mooniswap(
token1,
token2,
name,
symbol,
IMooniswapFactoryGovernance(msg.sender)
);
pool.transferOwnership(poolOwner);
}
}
```
=> Add mooniswap deploy function call

dags/resources/stages/parse/table_definitions/mooniswap/Mooniswap_v2_event_Swapped.json
- Added this based on looking at source code here: https://etherscan.io/address/0xa31bb36c5164b165f9c36955ea4ccbab42b3b28e#code
```
event Swapped(
address indexed sender,
address indexed receiver,
address indexed srcToken,
address dstToken,
uint256 amount,
uint256 result,
uint256 srcAdditionBalance,
uint256 dstRemovalBalance,
address referral
);
```
- and ABI from here https://github.com/wellttllew/1inch-flow
Use:
```
"contract_address": "SELECT mooniswap FROM ref('MooniswapFactory_event_Deployed')",
```
to work across all deployed pools
=> Added Swap Events for Mooniswap across all deployed Pools 

dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v1_event_OwnershipTransferred.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v1_event_Paused.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v1_event_Payed.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v1_event_Swapped.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v1_event_Unpaused.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v1_event_WhitelistAdded.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v1_event_WhitelistRemoved.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v2_event_OwnershipTransferred.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v2_event_Paused.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v2_event_Payed.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v2_event_Swapped.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v2_event_Unpaused.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v2_event_WhitelistAdded.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v2_event_WhitelistRemoved.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v3_event_OwnershipTransferred.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v3_event_Paused.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v3_event_Payed.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v3_event_Swapped.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v3_event_Unpaused.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v3_event_WhitelistAdded.json, dags/resources/stages/parse/table_definitions/paraswap/AugustusSwapperOld_v3_event_WhitelistRemoved.json
Added the legacy contracts for paraswap labelled by etherscan over here:
https://etherscan.io/accounts/label/paraswap?subcatid=2&size=7&start=0&col=1&order=asc
=> add older paraswap contracts

dags/resources/stages/parse/table_definitions/lido/Voting_event_CastVote.json, dags/resources/stages/parse/table_definitions/lido/Voting_event_ChangeMinQuorum.json, dags/resources/stages/parse/table_definitions/lido/Voting_event_ChangeSupportRequired.json, dags/resources/stages/parse/table_definitions/lido/Voting_event_ExecuteVote.json, dags/resources/stages/parse/table_definitions/lido/Voting_event_RecoverToVault.json, dags/resources/stages/parse/table_definitions/lido/Voting_event_ScriptResult.json, dags/resources/stages/parse/table_definitions/lido/Voting_event_StartVote.json
Used https://contract-parser.d5.ai and then replaced implementation address with proxy address as follows:
```
sed -i '.bak' 's/0xb935c3d80229d5d92f3761b17cd81dc2610e3a45/0x2e59a20f205bb85a89c53f1936454680651e618e/g' Voting*
```
=> Add Lido Voting events

dags/resources/stages/parse/table_definitions/bancor_network/BancorConverterFactory_event_NewConverter.json, dags/resources/stages/parse/table_definitions/bancor_network/BancorConverterFactory_v2_event_NewConverter.json, dags/resources/stages/parse/table_definitions/bancor_network/ContractRegistry_event_AddressUpdate.json, dags/resources/stages/parse/table_definitions/bancor_network/ContractRegistry_event_OwnerUpdate.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_event_Activation.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_event_Conversion.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_event_ConversionFeeUpdate.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_event_LiquidityAdded.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_event_LiquidityRemoved.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_event_OwnerUpdate.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_event_PriceDataUpdate.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_event_TokenRateUpdate.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_v2_event_Activation.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_v2_event_Conversion.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_v2_event_ConversionFeeUpdate.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_v2_event_LiquidityAdded.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_v2_event_LiquidityRemoved.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_v2_event_OwnerUpdate.json, dags/resources/stages/parse/table_definitions/bancor_network/Converter_v2_event_TokenRateUpdate.json
Created a new data set called `bancor_network` to try test improved coverage for two different versions of newConverter events.
In my hypothesis this should improve coverage, compared to the existing `bancor` dataset. This also cleans up the names of the contracts
=> Testing cleaning up bancor

dags/resources/stages/parse/table_definitions/bancor_network/Converter_v2_event_Conversion.json
Some of the contracts exist here ``` SELECT _contractAddress AS _converter FROM ref('ContractRegistry_event_AddressUpdate') WHERE _contractName = '0x424e54436f6e7665727465720000000000000000000000000000000000000000'  ``` are v2, so added in here for complete coverage
=> Add the same contracts for v2_event_Conversion , incase some are v2

dags/resources/stages/enrich/sqls/amended_tokens.sql
Hi, 
First, I am sorry about the typo introduce by me in the PR #216 
I saw you added a validation, but seems it is missing the address alias in the column.
This has caused that the `address` column currently is `f0_`
=> Missing address alias in token_amendaments

dags/resources/stages/parse/table_definitions/zeroex/Exchange_v4_0_event_LimitOrderFilled.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v4_0_event_RfqOrderFilled.json
- Manually created these files, since ExchangeProxy is a proxy contract, and the following instructions did not work: https://medium.com/@ASvanevik/how-to-add-proxy-ethereum-addresses-to-bigquery-d842ed001449
- Looked at zeroex github: https://github.com/0xProject/protocol/blob/e8ae64673f55e4dfd93eae12f67f36b7b267fe0e/docs/basics/events.rst#limitorderfilled and manually built these files.
- Currently address is set to the ExchangeProxy
=> Add 0x v4 events

dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_call_batchSwapExactIn.json, dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_call_batchSwapExactOut.json, dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_call_multihopBatchSwapExactIn.json, dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_call_multihopBatchSwapExactOut.json, dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_call_smartSwapExactIn.json, dags/resources/stages/parse/table_definitions/balancer/ExchangeProxy2_call_smartSwapExactOut.json
@medvedev1088  Sorry about the new PR, but I didn't realize before that the table definitions downloaded from contract parser had "event" instead of "call" in the table name.
=> Rename tables and files

dags/ethereum_sessions_dag.py, dags/ethereumetl_airflow/build_sessions_dag.py, dags/resources/stages/sessions/sqls/root_call_traces.sql, dags/resources/stages/sessions/sqls/sessions.sql
This PR adds a `ethereum_sessions_dag` DAG and corresponding `sessions` table to the `crypto_ethereum` dataset.  It builds on the work started in the [blockchain-etl/data-studio-connectors repo](https://github.com/blockchain-etl/data-studio-connectors) to extend the concept of a web analytics session to smart contracts.
I'm seeking initial feedback on at least the following aspects of this code:
1.  There's a staging table used in each DAG run for the "root call traces".  Should this be materialized in this manner within the destination dataset (`crypto_ethereum` in prod)?  Or is there a alternative way this should be done?
2. The DAG triggers at `14:00` daily and will start with the `wait_for_ethereum_load_dag` task.   This is also how the partitioned DAG is scheduled.  Is this a good …
=> Sessions DAG

dags/ethereumetl_airflow/build_partition_dag.py
=> Fix ethereum_balances_live view

dags/resources/stages/parse/table_definitions/opensea/WyvernExchangeWithBulkCancellations_event_NonceIncremented.json, dags/resources/stages/parse/table_definitions/opensea/WyvernExchangeWithBulkCancellations_event_OrderApprovedPartOne.json, dags/resources/stages/parse/table_definitions/opensea/WyvernExchangeWithBulkCancellations_event_OrderApprovedPartTwo.json, dags/resources/stages/parse/table_definitions/opensea/WyvernExchangeWithBulkCancellations_event_OrderCancelled.json, dags/resources/stages/parse/table_definitions/opensea/WyvernExchangeWithBulkCancellations_event_OrdersMatched.json, dags/resources/stages/parse/table_definitions/opensea/WyvernExchangeWithBulkCancellations_event_OwnershipRenounced.json, dags/resources/stages/parse/table_definitions/opensea/WyvernExchangeWithBulkCancellations_event_OwnershipTransferred.json
OpenSea is going to migrate to a new contract starting tomorrow: https://opensea.io/blog/developers/wyvern-2-3-developer-upgrade-guide/
The events are mostly the same as before.
=> Add events of new OpenSea contract

dags/resources/stages/parse/table_definitions/zeroex/Exchange_v4_0_event_ERC1155OrderCancelled.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v4_0_event_ERC1155OrderFilled.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v4_0_event_ERC721OrderCancelled.json, dags/resources/stages/parse/table_definitions/zeroex/Exchange_v4_0_event_ERC721OrderFilled.json
Add ERC721 and ERC1155 Order Filled events for the 0x Exchange. Coinbase is using 0x for their NFT marketplace.
=> Add ERC721 and ERC1155 Order Filled events

dags/resources/stages/parse/table_definitions/common/All_event_Upgraded.json
Used to get the per account address of the OpenSea contract deployments.
=> Create Upgraded event

dags/resources/stages/parse/table_definitions/curve/CryptoSwapThreeAssets_event_AddLiquidity.json, dags/resources/stages/parse/table_definitions/curve/CryptoSwapThreeAssets_event_RemoveLiquidity.json, dags/resources/stages/parse/table_definitions/curve/CryptoSwapTwoAssets_event_AddLiquidity.json, dags/resources/stages/parse/table_definitions/curve/CryptoSwapTwoAssets_event_RemoveLiquidity.json, dags/resources/stages/parse/table_definitions/curve/CryptoSwap_event_RemoveLiquidityOne.json, dags/resources/stages/parse/table_definitions/curve/CryptoSwap_event_TokenExchange.json, dags/resources/stages/parse/table_definitions/curve/PegSwapFourAssets_event_AddLiquidity.json, dags/resources/stages/parse/table_definitions/curve/PegSwapFourAssets_event_RemoveLiquidity.json, dags/resources/stages/parse/table_definitions/curve/PegSwapFourAssets_event_RemoveLiquidityImbalance.json, dags/resources/stages/parse/table_definitions/curve/PegSwapThreeAssets_event_AddLiquidity.json, dags/resources/stages/parse/table_definitions/curve/PegSwapThreeAssets_event_RemoveLiquidity.json, dags/resources/stages/parse/table_definitions/curve/PegSwapThreeAssets_event_RemoveLiquidityImbalance.json, dags/resources/stages/parse/table_definitions/curve/PegSwapTwoAssets_event_AddLiquidity.json, dags/resources/stages/parse/table_definitions/curve/PegSwapTwoAssets_event_RemoveLiquidity.json, dags/resources/stages/parse/table_definitions/curve/PegSwapTwoAssets_event_RemoveLiquidityImbalance.json, dags/resources/stages/parse/table_definitions/curve/PegSwap_event_RemoveLiquidityOne.json, dags/resources/stages/parse/table_definitions/curve/PegSwap_event_TokenExchange.json, dags/resources/stages/parse/table_definitions/curve/PegSwap_event_TokenExchangeUnderlying.json
There is no easy way to collect metapools now, so I added the snapshot at the current moment. Potentially we could combine data for peg- and crypto-contracts for swaps and one-side liquidity removals
=> Add aggregated Curve events

dags/resources/stages/parse/table_definitions/synthetix/Synth_event_Approval.json, dags/resources/stages/parse/table_definitions/synthetix/Synth_event_OwnerChanged.json, dags/resources/stages/parse/table_definitions/synthetix/Synth_event_OwnerNominated.json, dags/resources/stages/parse/table_definitions/synthetix/Synth_event_TargetUpdated.json, dags/resources/stages/parse/table_definitions/synthetix/Synth_event_Transfer.json, dags/resources/stages/parse/table_definitions/synthetix/Synthetix_event_Approval.json, dags/resources/stages/parse/table_definitions/synthetix/Synthetix_event_OwnerChanged.json, dags/resources/stages/parse/table_definitions/synthetix/Synthetix_event_OwnerNominated.json, dags/resources/stages/parse/table_definitions/synthetix/Synthetix_event_TargetUpdated.json, dags/resources/stages/parse/table_definitions/synthetix/Synthetix_event_Transfer.json
Add support for contract events from the Synthetix contract (SNX token) and Synth contracts (sUSD, sEUR, sJPY, sAUD, sGPB, sCHF, sKRW, sBTC, sETH, sLINK, sAAVE, sADA, sDOT, sETHBTC).
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table definitions, and grouped together the Synths. Contract addresses are from https://docs.synthetix.io/addresses/#mainnet. 
I opened a similar PR for Synthetix on Optimism here: https://github.com/nansen-ai/evmchain-etl-table-definitions/pull/71
=> Synthetix SNX token and Synth event table definitions

dags/ethereumetl_airflow/build_verify_streaming_dag.py, dags/ethereumetl_airflow/variables.py, dags/resources/stages/verify_streaming/sqls/extra_streaming_tables_have_latest.sql
Add extra_streaming_tables_have_latest.sql verification
Added a new variable `extra_streaming_tables`- comma separated list of fully qualified BigQuery table names e.g. `myproject.streamers.blocks1,myproject.streamers.blocks2`. Each table must have a column data containing a JSON object with field timestamp containing unix seconds. Used in combination with https://cloud.google.com/blog/products/data-analytics/pub-sub-launches-direct-path-to-bigquery-for-streaming-analytics to verify lag of streaming jobs that output to Pub/Sub
=> Add extra_streaming_tables_have_latest.sql verification

dags/ethereumetl_airflow/build_load_dag.py
Disable trace verification tasks
For some blocks tracing currently fails, see https://github.com/blockchain-etl/ethereum-etl/pull/392
=> Disable trace verification tasks until Erigon issue is fixed 

dags/ethereumetl_airflow/build_load_dag.py, dags/resources/stages/verify/sqls/traces_blocks_count.sql
Fix traces_blocks_count verification post-merge
There is no block rewards post-merge. It's taken into account in traces_blocks_count.sql
=> Fix traces_blocks_count verification post-merge

dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_DisableVaultFees.json, dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_FeeExclusion.json, dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_NewEligibilityManager.json, dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_NewFeeDistributor.json, dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_NewVault.json, dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_NewZapContract.json, dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_OwnershipTransferred.json, dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_SetIsGuardian.json, dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_SetPaused.json, dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_UpdateFactoryFees.json, dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_UpdateVaultFees.json, dags/resources/stages/parse/table_definitions/nftx/NFTXVaultFactoryUpgradeable_event_Upgraded.json
Add support for NFTX Vault factory events
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table definitions. Since this is a proxy contract, I ran the parser on the implementation contract, and replaced it with the proxy contract in the table definition files.
=> added events from the nftx vault factory

dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactory_call_createPairERC20.json
We currently do not parse nested fields correctly for traces, turning them into nulls in BigQuery. To mitigate we cast them to `STRING` instead.
Related PR to apply this mitigation by default for now in abi-parser: https://github.com/nansen-ai/abi-parser/pull/70.
cc @ben-xu001
=> Mitigate issue with parsing of tuples in sudoswap trace definition

dags/resources/stages/verify/sqls/traces_blocks_count.sql
- Quick fix to unblock the load_dag
Production `ethereum_load_dag` failing  on task `verify_traces_blocks_count`
[Airflow Log](https://8d2acbaf88c940708d5d71686aef80d2-dot-us-central1.composer.googleusercontent.com/log?dag_id=ethereum_load_dag&task_id=verify_traces_blocks_count&execution_date=2022-10-23T12%3A30%3A00%2B00%3A00)
- As a quick fix, exclude traces with rewards whose value is 0
- Longer term, we need to look at whether the node should be returning block rewards with value 0
- If so, we may need to backfill the export
- But this is just a quick fix to unblock the production `load_dag`
=> Quick fix for `load_dag` task `traces_blocks_count`

dags/ethereum_parse_v2_dag.py, dags/ethereum_parse_v2_datasets.py, dags/ethereumetl_airflow/build_parse_v2_dag.py, dags/ethereumetl_airflow/common.py, dags/ethereumetl_airflow/parse/parse_dataset_folder_logic.py, dags/ethereumetl_airflow/parse/toposort.py, run_parse_dataset.py
- Run all table definitions in a single task to reduce load on Ariflow scheduler
- Don't read table definitions during DAG building stage to reduce load on Airflow scheduler
Airflow scheduler is the bottleneck
This is a multistage deployment. In this PR only `aelf` and `curve` use parse_v2 DAG. If no issues are found, the remaining datasets will be upgraded
TODOs:
- Include toposort in requirements.txt, remove toposort.py
- Parse table definitions in parallel
- Add tests
=> Parse v2 DAG

dags/ethereum_parse_dag.py, dags/ethereumetl_airflow/build_parse_dag.py, dags/ethereumetl_airflow/variables.py
Don't read variables in a loop to prevent timeouts
It makes a call to the db every time Variable.get() is called which can cause timeouts if done in a loop
=> Don't read variables in a loop to prevent timeouts

dags/resources/stages/parse/table_definitions/curve/FactoryCryptoSwap_event_CryptoPoolDeployed.json, dags/resources/stages/parse/table_definitions/curve/FactoryCryptoSwap_event_LiquidityGaugeDeployed.json, dags/resources/stages/parse/table_definitions/curve/FactoryCryptoSwap_event_TransferOwnership.json, dags/resources/stages/parse/table_definitions/curve/FactoryCryptoSwap_event_UpdateFeeReceiver.json, dags/resources/stages/parse/table_definitions/curve/FactoryCryptoSwap_event_UpdateGaugeImplementation.json, dags/resources/stages/parse/table_definitions/curve/FactoryCryptoSwap_event_UpdatePoolImplementation.json, dags/resources/stages/parse/table_definitions/curve/FactoryCryptoSwap_event_UpdateTokenImplementation.json, dags/resources/stages/parse/table_definitions/curve/FactoryStableSwap_event_BasePoolAdded.json, dags/resources/stages/parse/table_definitions/curve/FactoryStableSwap_event_LiquidityGaugeDeployed.json, dags/resources/stages/parse/table_definitions/curve/FactoryStableSwap_event_MetaPoolDeployed.json, dags/resources/stages/parse/table_definitions/curve/FactoryStableSwap_event_PlainPoolDeployed.json
Add table definitions for Curve's cryptoswap and stableswap factories.
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table defenitions
cryptoswap factory: 0xF18056Bbd320E96A48e3Fbf8bC061322531aac99
stableswap factory: 0xB9fC157394Af804a3578134A6585C0dc9cc990d4
=> Add cryptoswap factory and stableswap factory for curve

dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_FlashLoanCompleted.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_FundsMigrated.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_NetworkFeesWithdrawn.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_Paused.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_PoolAdded.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_PoolCollectionAdded.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_PoolCollectionRemoved.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_PoolCreated.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_PoolRemoved.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_RoleAdminChanged.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_RoleGranted.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_RoleRevoked.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_TokensTraded.json, dags/resources/stages/parse/table_definitions/bancor/BancorNetworkV3_event_Unpaused.json
ie: Add support for Bancor V3 contract events 
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table defenitions and also changed the address manually from the implementation address to the proxy
=> :sparkles: add Bancor V3 events

dags/resources/stages/parse/table_definitions/maker/mcdFab_call_exit.json, dags/resources/stages/parse/table_definitions/maker/mcdFab_call_join.json
Reintroduce maker call definitions originally added in https://github.com/blockchain-etl/ethereum-etl-airflow/pull/437 and removed in https://github.com/blockchain-etl/ethereum-etl-airflow/pull/439 because of issues with parsing. The issue was in the query used in the `contract_address`: `join` is a reserved SQL keyword, so it needed to be quoted in backticks.
Tables have already been parsed:
```sql
SELECT * FROM `blockchain-etl.ethereum_maker.mcdFab_call_exit`;
SELECT * FROM `blockchain-etl.ethereum_maker.mcdFab_call_join`;
```
cc @AyadiGithub
=> Reintroduce maker call definitions

dags/ethereumetl_airflow/build_load_dag.py
Increase load_task wait timeout to 6 hr
Incident where export_dag failure was quickly cleared and succeeded, but load_dag had already failed, and user forgot to clear load_dag. This resulted in downstream failure of partition and parse dags.
=> Increase load_task wait timeout to 6 hr

dags/resources/stages/parse/table_definitions/bancor/PoolCollection_event_DefaultTradingFeePPMUpdated.json, dags/resources/stages/parse/table_definitions/bancor/PoolCollection_event_DepositingEnabled.json, dags/resources/stages/parse/table_definitions/bancor/PoolCollection_event_OwnerUpdate.json, dags/resources/stages/parse/table_definitions/bancor/PoolCollection_event_TokensDeposited.json, dags/resources/stages/parse/table_definitions/bancor/PoolCollection_event_TokensWithdrawn.json, dags/resources/stages/parse/table_definitions/bancor/PoolCollection_event_TotalLiquidityUpdated.json, dags/resources/stages/parse/table_definitions/bancor/PoolCollection_event_TradingEnabled.json, dags/resources/stages/parse/table_definitions/bancor/PoolCollection_event_TradingFeePPMUpdated.json, dags/resources/stages/parse/table_definitions/bancor/PoolCollection_event_TradingLiquidityUpdated.json
ie: Add support for Bancor V3's PoolCollection contracts 
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/) 
For contract address, I got all the distinct poolcollection addresses returned by the PoolCreated event in the bancornetowrkv3 contract
=> adding support for Bancor v3 PoolCollection

dags/resources/stages/parse/table_definitions/convex/FraxBooster_call_addPool.json, dags/resources/stages/parse/table_definitions/convex/FraxBooster_call_createVault.json
Add support for Convex Frax booster pools
=> add calls for Convex-Frax pool creation

dags/resources/stages/parse/table_definitions/convex/ConvexFraxPool_call_getReward.json, dags/resources/stages/parse/table_definitions/convex/ConvexFraxPool_call_getReward2.json, dags/resources/stages/parse/table_definitions/convex/ConvexFraxPool_call_lockAdditional.json, dags/resources/stages/parse/table_definitions/convex/ConvexFraxPool_call_stakeLocked.json, dags/resources/stages/parse/table_definitions/convex/ConvexFraxPool_call_withdrawLocked.json
Add missing Convex-Frax calls (events do not cover some pools)
None
=> Add missing convex frax calls

dags/resources/stages/parse/table_definitions/compound/cWETHv3_event_AbsorbCollateral.json, dags/resources/stages/parse/table_definitions/compound/cWETHv3_event_AbsorbDebt.json, dags/resources/stages/parse/table_definitions/compound/cWETHv3_event_BuyCollateral.json, dags/resources/stages/parse/table_definitions/compound/cWETHv3_event_PauseAction.json, dags/resources/stages/parse/table_definitions/compound/cWETHv3_event_Supply.json, dags/resources/stages/parse/table_definitions/compound/cWETHv3_event_SupplyCollateral.json, dags/resources/stages/parse/table_definitions/compound/cWETHv3_event_Transfer.json, dags/resources/stages/parse/table_definitions/compound/cWETHv3_event_TransferCollateral.json, dags/resources/stages/parse/table_definitions/compound/cWETHv3_event_Withdraw.json, dags/resources/stages/parse/table_definitions/compound/cWETHv3_event_WithdrawCollateral.json, dags/resources/stages/parse/table_definitions/compound/cWETHv3_event_WithdrawReserves.json
Adds cWETHv3 events for Compound V3
Copied the files for cUSDCv3 from https://github.com/blockchain-etl/ethereum-etl-airflow/commit/c428a8a69d9d3e3b91e06b42cd9d488179750034 and replaced the contract_address with the value from https://docs.compound.finance/ and changed the table name to match.
=> Add cWETHv3 events

dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Approval.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Borrow.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Deposit.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Liquidate.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Repay.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Transfer.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Withdraw.json
Bug fix 
Changed contract address to WETH router proxy instead of Market ETH implementation ([Exactly website](https://docs.exact.ly/guides/smart-contract-addresses))
Previous tables that were created would need to be deleted and re-populated
Used CLI tools to build the `implementation contract` table definitions but transactions were occurring on the `proxy address`
Kitemaker Task: https://toil.kitemaker.co/sKwq6E-Nansen/OdAY7o-Squad__Ecosystem/items/81
=> SQU5-81: Exactly Custom Dashboard Scoping Work

dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketDAI_event_Borrow.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketDAI_event_BorrowAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketDAI_event_Deposit.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketDAI_event_DepositAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketDAI_event_Liquidate.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketDAI_event_Repay.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketDAI_event_RepayAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketDAI_event_Transfer.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketDAI_event_Withdraw.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketDAI_event_WithdrawAtMaturity.json
Added MarketDAI events using implementation address but changed `contract-address` to proxy address ([Documentation and links from Exactly website](https://docs.exact.ly/guides/smart-contract-addresses))
Used CLI tools to build the `implementation contract` table definitions but transactions were occurring on the `proxy address`
=> SQU5-88: Exactly Custom Dashboard Scoping Work - DAI

dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketUSDC_event_Borrow.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketUSDC_event_BorrowAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketUSDC_event_Deposit.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketUSDC_event_DepositAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketUSDC_event_Liquidate.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketUSDC_event_Repay.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketUSDC_event_RepayAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketUSDC_event_Transfer.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketUSDC_event_Withdraw.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketUSDC_event_WithdrawAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWBTC_event_Borrow.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWBTC_event_BorrowAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWBTC_event_Deposit.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWBTC_event_DepositAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWBTC_event_Liquidate.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWBTC_event_Repay.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWBTC_event_RepayAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWBTC_event_Transfer.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWBTC_event_Withdraw.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWBTC_event_WithdrawAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWstETH_event_Borrow.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWstETH_event_BorrowAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWstETH_event_Deposit.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWstETH_event_DepositAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWstETH_event_Liquidate.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWstETH_event_Repay.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWstETH_event_RepayAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWstETH_event_Transfer.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWstETH_event_Withdraw.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWstETH_event_WithdrawAtMaturity.json
Following up for Exactly Dashboard [Kitemaker SQU5-81](https://toil.kitemaker.co/sKwq6E-Nansen/OdAY7o-Squad__Ecosystem/items/81)
Add support for other markets (USDC, WBTC, WstETH)
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) or cli tools to build the table defenitions
=> Added other markets - USDC, WBTC, WstETH

dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Borrow.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_BorrowAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Deposit.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_DepositAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Liquidate.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_RepayAtMaturity.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Transfer.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_Withdraw.json, dags/resources/stages/parse/table_definitions/exactly/ExactlyMarketWETH_event_WithdrawAtMaturity.json
Bug fix to use WETH proxy address instead of WETH router proxy address
Would have to delete existing `ExactlyMarketWETH_event_xxx` tables in BigQuery and reload
Added a few tables ExactlyMarketWETH_event_xxxAtMaturity`
=> Bug fix for WETH tables

dags/resources/stages/parse/table_definitions/compound/cTokenv3_event_AbsorbCollateral.json, dags/resources/stages/parse/table_definitions/compound/cTokenv3_event_AbsorbDebt.json, dags/resources/stages/parse/table_definitions/compound/cTokenv3_event_BuyCollateral.json, dags/resources/stages/parse/table_definitions/compound/cTokenv3_event_PauseAction.json, dags/resources/stages/parse/table_definitions/compound/cTokenv3_event_Supply.json, dags/resources/stages/parse/table_definitions/compound/cTokenv3_event_SupplyCollateral.json, dags/resources/stages/parse/table_definitions/compound/cTokenv3_event_Transfer.json, dags/resources/stages/parse/table_definitions/compound/cTokenv3_event_TransferCollateral.json, dags/resources/stages/parse/table_definitions/compound/cTokenv3_event_Withdraw.json, dags/resources/stages/parse/table_definitions/compound/cTokenv3_event_WithdrawCollateral.json, dags/resources/stages/parse/table_definitions/compound/cTokenv3_event_WithdrawReserves.json
Add support for cToken (right now just cUSDCv3 and cWETHv3) events for compound v3
I copied the json files for cUSDCv3 and replaced the table names to be cTokenv3_event_{event name} and replaced contract_address with "SELECT DISTINCT(cometProxy) FROM ref('Configurator_v3_event_CometDeployed')"
hi! there's no Comptroller for Compound v3 so there was no mirror to the "MarketListed" used for the cToken events in v2 - in general v3 is just very different from v2 but I do think looking at the distinct cometProxys from the CometDeployed events should get both v3 cToken addresses!
=> overarching cToken events for compound v3

README.md, dags/ethereum_amend_dag.py, dags/ethereum_export_dag.py, dags/ethereum_load_dag.py, dags/ethereum_parse_dag.py, dags/ethereum_partition_dag.py, dags/ethereumetl_airflow/build_clean_dag.py
Push the daily dag schedules back by 4 hours.
Also, after Parse v2 DAG, Composer resources can be down-rated significantly. This PR to update docs with suggested config.
- updated schedules working in our Dev Composer
- downrated config already working in both Dev and Prod Composers
https://github.com/blockchain-etl/ethereum-etl-airflow/pull/466
https://github.com/blockchain-etl/ethereum-etl-airflow/pull/467
https://github.com/blockchain-etl/ethereum-etl-airflow/pull/470
=> Update composer schedules and config

dags/resources/stages/parse/table_definitions/dodo/DPPFactory_event_NewDPP.json
In the `DPPFactory_event_NewDPP` table add another version of the `DPP_Factory` contract which also emits `NewDPP` events
I added the alternate version in the `contract` field of the existing table, i.e. `"SELECT * FROM UNNEST(['0x5336ede8f971339f6c0e304c66ba16f1296a2fbe', '0x6b4fa0bc61eddc928e0df9c7f01e407bfcd3e5ef'])"`
If it's preferable to create a separate new table (e.g. `DPPFactory_V1` and `DPPFactory_V2`), let me know. 
This modifies a table created in PR #461: https://github.com/blockchain-etl/ethereum-etl-airflow/pull/461/commits/bdbc514a02d82c571ac74234dd071f4de16dad55
=> add Dodo contract version

dags/resources/stages/parse/table_definitions/balancer/V2_MetaStablePool_event_AmpUpdateStarted.json, dags/resources/stages/parse/table_definitions/balancer/V2_MetaStablePool_event_AmpUpdateStopped.json, dags/resources/stages/parse/table_definitions/balancer/V2_MetaStablePool_event_Approval.json, dags/resources/stages/parse/table_definitions/balancer/V2_MetaStablePool_event_OracleEnabledChanged.json, dags/resources/stages/parse/table_definitions/balancer/V2_MetaStablePool_event_PausedStateChanged.json, dags/resources/stages/parse/table_definitions/balancer/V2_MetaStablePool_event_PriceRateCacheUpdated.json, dags/resources/stages/parse/table_definitions/balancer/V2_MetaStablePool_event_PriceRateProviderSet.json, dags/resources/stages/parse/table_definitions/balancer/V2_MetaStablePool_event_SwapFeePercentageChanged.json, dags/resources/stages/parse/table_definitions/balancer/V2_StablePool_event_AmpUpdateStarted.json, dags/resources/stages/parse/table_definitions/balancer/V2_StablePool_event_AmpUpdateStopped.json, dags/resources/stages/parse/table_definitions/balancer/V2_StablePool_event_Approval.json, dags/resources/stages/parse/table_definitions/balancer/V2_StablePool_event_PausedStateChanged.json, dags/resources/stages/parse/table_definitions/balancer/V2_StablePool_event_SwapFeePercentageChanged.json
Added missing events for Balancer V2_MetaStablePool and V2_StablePool 
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table defenitions
We will use those events to estimate price impact on balancer stable pools (e.g. StablePool, ComposableStablePool, MetaStablePool and also Curve pools)
=> Added missed events for balancer_v2 MetaStable and Stable pools

compose.yaml, dags/ethereumetl_airflow/build_load_dag.py, dags/resources/stages/enrich/schemas/blocks.json, dags/resources/stages/enrich/sqls/blocks.sql, dags/resources/stages/enrich/sqls/merge/merge_blocks.sql, dags/resources/stages/raw/schemas/blocks.json, docs/eip_4895_migration.md, requirements_airflow.txt
See https://github.com/blockchain-etl/ethereum-etl/pull/434 for more context.
Updates schemas and SQL to support the new `withdrawals` and `withdrawals_root` fields that will be introduced as part of the Shanghai/Shapella upgrade. See [EIP-4895](https://eips.ethereum.org/EIPS/eip-4895).
New columns should be added automatically.
=> Add withdrawals (EIP-4895) 

README.md, dags/ethereumetl_airflow/build_export_dag.py, dags/ethereumetl_airflow/build_load_dag.py, dags/ethereumetl_airflow/variables.py, requirements_airflow.txt, requirements_dev.txt, requirements_local.txt, requirements_test.txt
- update dependencies to match `` and/or latest versions
- also, add `(export|load)_end_date` & `load_catchup` parameters to help with running backfills
- retain the now-deprecated-but-still-working `schedule_interval` and not change these to the new syntax `schedule`, preferring some backwards compatibility ... for now
=> Upgrade composer

dags/resources/stages/parse/table_definitions/compound/cToken_event_AccrueInterest_combined.sql
Add cToken_event_AccrueInterest_combined.sql that combines AccrueInterest events with different signatures.
Some compound v2 tokens have a different signature for AccrueInterest event. Here is an example from this page https://docs.compound.finance/v2/:
cCOMP	0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4 - has cashPrior in AccrueInterest
cUSDC	0x39AA39c021dfbaE8faC545936693aC917d5E7563 - doesn’t have cashPrior in AccrueInterest
=> Add cToken_event_AccrueInterest_combined.sql

dags/resources/stages/parse/table_definitions/arbitrum/SequencerInbox_call_addSequencerL2BatchFromOrigin.json
Ecosystem team is in the process of upgrading the Chain Paradise feature, among others with Financial Analysis data that includes chain revenue calculations. To do the calculation for Arbitrum, we are trying to match [this query](https://dune.com/queries/1611505/2672828) on Dune and one of the tables there that we currently don't have is call events for L2 batches called `addSequencerL2BatchFromOrigin`.
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) on Arbitrum Sequencer Inbox's implementation contract (`0xd03bfe2ce83632f4e618a97299cc91b1335bb2d9`) to get this table definition file.
=> Add call events for L2 batches

dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactoryV2_event_NewERC1155Pair.json, dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactoryV2_event_NewERC721Pair.json
Add support for sudoswap v2 pool creation events. Recover the files that should be merged in a previous [PR](https://github.com/blockchain-etl/ethereum-etl-airflow/pull/566).
=> Add back the two sudoswap v2 pool creation events.

dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactoryV2_call_createPairERC1155ERC20.json, dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactoryV2_call_createPairERC1155ETH.json, dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactoryV2_call_createPairERC721ERC20.json, dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactoryV2_call_createPairERC721ETH.json, dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairV2ERC1155ETH_call_swapNFTsForToken.json, dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairV2ERC1155ETH_call_swapTokenForSpecificNFTs.json, dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairV2ERC721ERC20_call_swapNFTsForToken.json, dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairV2ERC721ERC20_call_swapTokenForSpecificNFTs.json
add support for sudoswap v2 pair and factory contract calls
used [abi-parser](https://contract-parser.d5.ai/)
rename a couple of tables from PR #567 wherein i forgot to specify the action ('_call_'). not essential - just for others' benefit
=> add more sudoswap v2 calls

dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactoryV2_call_createPairERC1155ERC20.json, dags/resources/stages/parse/table_definitions/sudoswap/LSSVMPairFactoryV2_call_createPairERC721ERC20.json
Data inside the params struct is currently not parsing for LSSVMPairFactoryV2_call_createPairERC1155ERC20 and LSSVMPairFactoryV2_call_createPairERC721ERC20. Initially I used https://contract-parser.d5.ai/ but now resubmitting these function calls parsed with nansen decoder
I used [Nansen abi parser](https://nansen-contract-parser-prod.web.app/)
PR #569
=> switch to nansen decoder to fix struct parsing issue

dags/resources/stages/parse/table_definitions/blur/BlendV2_call_buyToBorrowV2.json, dags/resources/stages/parse/table_definitions/blur/BlendV2_call_buyToBorrowV2ETH.json, dags/resources/stages/parse/table_definitions/blur/BlendV2_call_takeBidV2.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_call_cancelTrades.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_call_takeAsk.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_call_takeAskPool.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_call_takeAskSingle.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_call_takeAskSinglePool.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_call_takeBid.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_call_takeBidSingle.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_event_CancelTrade.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_event_Execution.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_event_Execution721MakerFeePacked.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_event_Execution721Packed.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_event_Execution721TakerFeePacked.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_event_NewProtocolFee.json, dags/resources/stages/parse/table_definitions/blur/BlurExchangeV2_event_Upgraded.json
- Add support for Blur v2 contract events and calls
- Add new Blend v2 calls (from the new v2 implementation)
-- no new Blend v2 events
I used the [abi-parser](https://nansen-contract-parser-prod.web.app/)  tools to build the table definitions
None
=> Blur V2  events and calls

dags/resources/stages/parse/table_definitions/base/L2OutputOracle_event_OutputProposed.json
add support for Base L2OutputOracle
=> add support for Base L2OutputOracle

dags/ethereumetl_airflow/parse/parse_dataset_folder_logic.py, dags/ethereumetl_airflow/parse/parse_state_manager.py
Fix race condition when deploying table definitions
https://linear.app/nansen/issue/ECINT-501/fix-race-condition-in-table-definition-deployments
Sleep for 10 minutes if running in Airflow
=> Fix race condition when deploying table definitions

dags/resources/stages/parse/table_definitions/curve/TricryptoOptimized_event_TokenExchange.json
Added support for Curve TokenExchange events for the 5 [Tricrypto Optimized](https://github.com/curvefi/tricrypto-ng/blob/main/contracts/main/CurveTricryptoOptimizedWETH.vy) pools, which use a non-standard event abi
address | name
-- | --
0x4ebdf703948ddcea3b11f675b4d1fba9d2414a14 | TriCRV
0x7f86bf177dd4f3494b841a37e810a34dd56c829b | TricryptoUSDC
0xf5f5b97624542d72a9e06f04804bf81baa15e2b4 | TricryptoUSDT
0x2889302a794da87fbf1d6db415c1492194663d13 | TricryptoLLAMA
0x5426178799ee0a0181a89b4f57efddfab49941ec | TricryptoINV
I used the [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table definition, and added the rest of the pool contracts to it
=> Added TokenExchange events for Curve TricryptoOptimized pools

dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_AdminChanged.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_BatchPriceFeedUpdate.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_BeaconUpgraded.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_ContractUpgraded.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_DataSourcesSet.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_FeeSet.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_GovernanceDataSourceSet.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_Initialized.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_OwnershipTransferred.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_PriceFeedUpdate.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_Upgraded.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_ValidPeriodSet.json, dags/resources/stages/parse/table_definitions/pyth/PythOracle_event_WormholeAddressSet.json
Add support for Pyth events.
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) build the table definitions. The address is listed here https://docs.pyth.network/documentation/pythnet-price-feeds/evm I replaced the implementation address with the proxy address
=> Add PythOracle contract

dags/resources/stages/parse/table_definitions/uniswap/ExclusiveDutchOrderReactor_call_execute.json, dags/resources/stages/parse/table_definitions/uniswap/ExclusiveDutchOrderReactor_call_executeBatch.json, dags/resources/stages/parse/table_definitions/uniswap/ExclusiveDutchOrderReactor_call_executeBatchWithCallback.json, dags/resources/stages/parse/table_definitions/uniswap/ExclusiveDutchOrderReactor_call_executeWithCallback.json
Added support for Uniswap X execute calls: `execute`, `executeBatch`, `executeWithCallback`, `executeBatchWithCallback`
=> Uniswap X execute calls

dags/ethereum_verify_streaming_dag.py, dags/ethereumetl_airflow/build_verify_streaming_dag.py, requirements_airflow.txt
Reduce max_lag_in_minutes for streaming and reduce number of retries
To get alerted on streaming issues earlier
=> Reduce max_lag_in_minutes for streaming and reduce number of retries

dags/resources/stages/parse/table_definitions/seaport/SeaportV14_call_fulfillAdvancedOrder.json, dags/resources/stages/parse/table_definitions/seaport/SeaportV14_call_fulfillAvailableAdvancedOrders.json, dags/resources/stages/parse/table_definitions/seaport/SeaportV14_call_fulfillAvailableOrders.json, dags/resources/stages/parse/table_definitions/seaport/SeaportV14_call_fulfillBasicOrder.json, dags/resources/stages/parse/table_definitions/seaport/SeaportV14_call_fulfillBasicOrder_efficient_6GL6yc.json, dags/resources/stages/parse/table_definitions/seaport/SeaportV14_call_fulfillOrder.json, dags/resources/stages/parse/table_definitions/seaport/SeaportV14_call_matchAdvancedOrders.json, dags/resources/stages/parse/table_definitions/seaport/SeaportV14_call_matchOrders.json
add definitions for Seaport 1.4 & 1.5 call functions
n/a
=> add definitions for Seaport 1.4 & 1.5 call functions

dags/resources/stages/parse/table_definitions/equalizer/FlashLoanProviderOld_call_flashLoan.json, dags/resources/stages/parse/table_definitions/equalizer/FlashLoanProviderOld_event_FlashLoan.json, dags/resources/stages/parse/table_definitions/equalizer/FlashLoanProvider_call_flashLoan.json, dags/resources/stages/parse/table_definitions/equalizer/FlashLoanProvider_event_FlashLoan.json, dags/resources/stages/parse/table_definitions/maker/DssFlash_call_flashLoan.json, dags/resources/stages/parse/table_definitions/maker/DssFlash_call_vatDaiFlashLoan.json, dags/resources/stages/parse/table_definitions/maker/DssFlash_event_Deny.json, dags/resources/stages/parse/table_definitions/maker/DssFlash_event_File.json, dags/resources/stages/parse/table_definitions/maker/DssFlash_event_FlashLoan.json, dags/resources/stages/parse/table_definitions/maker/DssFlash_event_Rely.json, dags/resources/stages/parse/table_definitions/maker/DssFlash_event_VatDaiFlashLoan.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_call_addLiquidity.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_call_flashLoan.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_call_removeLiquidity.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_call_removeLiquidityImbalance.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_call_removeLiquidityOneToken.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_call_swap.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_event_AddLiquidity.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_event_FlashLoan.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_event_RemoveLiquidity.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_event_RemoveLiquidityImbalance.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_event_RemoveLiquidityOne.json, dags/resources/stages/parse/table_definitions/synapse/SwapFlashLoan_event_TokenSwap.json
=> Flashloans events

dags/resources/stages/parse/table_definitions/lido/Lido_event_TokenRebased.json
Add, please, lido.TokenRebased event to data schema
=> adding lido.TokenRebased event table

dags/resources/stages/parse/table_definitions/eigenlayer/DelayedWithdrawalRouter_call_claimDelayedWithdrawals.json, dags/resources/stages/parse/table_definitions/eigenlayer/DelayedWithdrawalRouter_call_createDelayedWithdrawal.json, dags/resources/stages/parse/table_definitions/eigenlayer/DelayedWithdrawalRouter_event_DelayedWithdrawalCreated.json, dags/resources/stages/parse/table_definitions/eigenlayer/DelayedWithdrawalRouter_event_DelayedWithdrawalsClaimed.json, dags/resources/stages/parse/table_definitions/eigenlayer/DelayedWithdrawalRouter_event_Initialized.json, dags/resources/stages/parse/table_definitions/eigenlayer/DelayedWithdrawalRouter_event_OwnershipTransferred.json, dags/resources/stages/parse/table_definitions/eigenlayer/DelayedWithdrawalRouter_event_Paused.json, dags/resources/stages/parse/table_definitions/eigenlayer/DelayedWithdrawalRouter_event_PauserRegistrySet.json, dags/resources/stages/parse/table_definitions/eigenlayer/DelayedWithdrawalRouter_event_Unpaused.json, dags/resources/stages/parse/table_definitions/eigenlayer/DelayedWithdrawalRouter_event_WithdrawalDelayBlocksSet.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_call_stake.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_call_verifyAndProcessWithdrawal.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_call_verifyOvercommittedStake.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_call_verifyWithdrawalCredentialsAndBalance.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_call_withdrawBeforeRestaking.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_call_withdrawRestakedBeaconChainETH.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_event_EigenPodStaked.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_event_FullWithdrawalRedeemed.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_event_Initialized.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_event_PartialWithdrawalRedeemed.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_event_RestakedBeaconChainETHWithdrawn.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_event_ValidatorOvercommitted.json, dags/resources/stages/parse/table_definitions/eigenlayer/EigenPod_event_ValidatorRestaked.json, dags/resources/stages/parse/table_definitions/eigenlayer/StrategyBaseTVLLimits_call_deposit.json, dags/resources/stages/parse/table_definitions/eigenlayer/StrategyBaseTVLLimits_call_withdraw.json
- Add EigenLayer Withdrawal Router events and calls
- Fix existing Pod events contract address source and add calls
- Add EigenLayer strategy calls 
None
**Some of the tables will need to be refreshed (EigenPod events tables) due to changing the "contract_address" field.**
=> EigenLayer events and calls

requirements_test.txt
Fix pendulum version in tests
Prevents an error in tests https://github.com/blockchain-etl/ethereum-etl-airflow/actions/runs/8027295703/job/21932297315
```
==================================== ERRORS ====================================
________________ ERROR collecting tests/test_dag_validation.py _________________
tests/test_dag_validation.py:4: in <module>
from airflow.models import DagBag, Variable
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/airflow/__init__.py:42: in <module>
from airflow import settings
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/airflow/settings.py:49: in <module>
TIMEZONE = pendulum.tz.timezone("UTC")
E   TypeError: 'module' object is not callable
=========================== short test summary info …
```
=> Fix pendulum version in tests

dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStakingOld_event_AssetDeposit.json, dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStakingOld_event_Initialized.json, dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStakingOld_event_MaxNodeDelegatorLimitUpdated.json, dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStakingOld_event_MinAmountToDepositUpdated.json, dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStakingOld_event_NodeDelegatorAddedinQueue.json, dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStakingOld_event_Paused.json, dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStakingOld_event_Unpaused.json, dags/resources/stages/parse/table_definitions/eigenpie/EigenpieStakingOld_event_UpdatedEigenpieConfig.json
Topic: Adding Eigenpie staking events for the old proxy contract. The current Staking contract events tables, for ex. `AssetDeposit`, do not pick up logs for the old Proxy contract due to having different topics/ABI. 
Add support for Eigenpie Staking events for the old proxy contract
#675
=> Eigenpie Staking events for Old Proxy

dags/resources/stages/parse/table_definitions/balancer/GearboxLinearPoolFactory_event_FactoryDisabled.json, dags/resources/stages/parse/table_definitions/balancer/GearboxLinearPoolFactory_event_GearboxLinearPoolCreated.json, dags/resources/stages/parse/table_definitions/balancer/GearboxLinearPoolFactory_event_PoolCreated.json, dags/resources/stages/parse/table_definitions/balancer/V2_ComposableStablePoolFactory_event_PoolCreated.json
Add support for balancer factory contract addresses for existing events 
=> [Gauntlet] Add balancer factory contracts

dags/ethereumetl_airflow/parse/parse_dataset_folder_logic.py
After merging https://github.com/blockchain-etl/ethereum-etl-airflow/pull/739, CI/CD [failed on merge](https://github.com/blockchain-etl/ethereum-etl-airflow/actions/runs/9703086086/job/26780423989) due to too many updated table definitions -- though in this case I think it's not accidental, just a lot of definitions in a folder, 59 in total.
I think increasing the limit from 50 to 60 will cover this.
=> increase max_num_updated_table_definitions

dags/resources/stages/parse/table_definitions/ajna/ERC20PoolFactory_event_PoolCreated.json, dags/resources/stages/parse/table_definitions/ajna/ERC721PoolFactory_event_PoolCreated.json
Reverts blockchain-etl/ethereum-etl-airflow#745
Which is the same as re-applying blockchain-etl/ethereum-etl-airflow#739
Inelegant, but a solution to making CI/CD fire and update these tables after last time it got stuck.
=> Re-apply "Update Ajna Factory Pool Addresses"

dags/resources/stages/parse/table_definitions/ajna_v2/ERC20PoolFactory_event_PoolCreated.json, dags/resources/stages/parse/table_definitions/ajna_v2/ERC721PoolFactory_event_PoolCreated.json
Add support for Ajna v2 ERC20 and ERC721 Pool Factory
Will be added in future , once this is parsed
=> Ajna v2 pools

dags/resources/stages/enrich/sqls/traces.sql, dags/resources/stages/raw/schemas/traces.json
Hotfix for failing load_traces task due to value not fitting in the NUMERIC data type
Change the datatype STRING when loading, use SAFE_CAST() when merging
Example tx with large value: https://etherscan.io/tx/0x00ed8efcf66cc13022770c253de4f15edbf53a07471e3ce49913fae12098d6aa
More transactions with large value:
```
select *
from bigquery-public-data.crypto_ethereum.traces
where date(block_timestamp) = '2024-07-03'
and value is null
```
=> Hotfix for failing load_traces task due to value not fitting in the NUMERIC data type

dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_event_AssetWithdrawalQueued_Upgrade.json
Add event for LRT Withdrawal Manager for rseth after upgrade
=> Add event for LRT Withdrawal Manager for rseth after upgrade

dags/resources/stages/parse/table_definitions/kelpdao/LRTWithdrawalManager_event_AssetWithdrawalQueued.json
Trigger full refresh of table LRTWithdrawalManager_event_AssetWithdrawalQueued to fix the error:
```
google.api_core.exceptions.BadRequest: 400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/blockchain-etl/datasets/ethereum_kelpdao/tables/LRTWithdrawalManager_event_AssetWithdrawalQueued?prettyPrint=false: Queries in UNION ALL have mismatched column count; query 1 has 9 columns, query 2 has 8 columns at [5:1]
```
=> Refresh kelpdao table

dags/resources/stages/parse/table_definitions/cove/CoveYearnGaugeFactory_event_CoveGaugesDeployed.json
Add support for Cove gauge deployment events (https://etherscan.io/address/0x842b22eb2a1c1c54344eddbe6959f787c2d15844#events).
=> Add Cove GaugeFactory deployment event

.github/workflows/cicd-on-pr.yml
Updating the python version in the CI/CD because it was failing. An example of a failing check is [here](https://github.com/blockchain-etl/ethereum-etl-airflow/actions/runs/11333174317/job/31516802669).
Updated python version to latest in 3.8
=> Update python 3.8 version in CI/CD

dags/resources/stages/parse/table_definitions/stakedao/Platform_event_BountyClosed.json, dags/resources/stages/parse/table_definitions/stakedao/Platform_event_BountyCreated.json, dags/resources/stages/parse/table_definitions/stakedao/Platform_event_BountyDurationIncrease.json, dags/resources/stages/parse/table_definitions/stakedao/Platform_event_BountyDurationIncreaseQueued.json, dags/resources/stages/parse/table_definitions/stakedao/Platform_event_Claimed.json, dags/resources/stages/parse/table_definitions/stakedao/Platform_event_FeeCollectorUpdated.json, dags/resources/stages/parse/table_definitions/stakedao/Platform_event_FeeUpdated.json, dags/resources/stages/parse/table_definitions/stakedao/Platform_event_FeesCollected.json, dags/resources/stages/parse/table_definitions/stakedao/Platform_event_ManagerUpdated.json, dags/resources/stages/parse/table_definitions/stakedao/Platform_event_OwnershipTransferred.json, dags/resources/stages/parse/table_definitions/stakedao/Platform_event_PeriodRolledOver.json, dags/resources/stages/parse/table_definitions/stakedao/Platform_event_RecipientSet.json
Add support for StakeDAO CRV VoteMarket events (https://etherscan.io/address/0x000000073D065Fc33a3050C2d0E19C393a5699ba#events).
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table definitions.
=> Add StakeDAO CRV VoteMarket events

.github/workflows/cicd-on-pr.yml, dags/ethereumetl_airflow/parse/parse_dataset_folder_logic.py
Increase max number of updated table definitions to 70
Fix build failure https://github.com/blockchain-etl/ethereum-etl-airflow/actions/runs/13707714519/job/38336987329
=> Increase max number of updated table definitions to 70
